Kong/public-ui-components

CODEOWNERS
packages/core/cli/src/__template__/vite.config.ts
packages/core/i18n/vite.config.ts

fix: trigger release

---

CODEOWNERS
packages/portal/spec-renderer/src/components/SpecRenderer.vue
packages/portal/spec-renderer/src/swagger-ui-web-component.d.ts
packages/portal/swagger-ui-web-component/LICENSE
packages/portal/swagger-ui-web-component/README.md
packages/portal/swagger-ui-web-component/package.json
packages/portal/swagger-ui-web-component/public/index.html
packages/portal/swagger-ui-web-component/public/petstore_v3.json
packages/portal/swagger-ui-web-component/src/element.js
packages/portal/swagger-ui-web-component/src/index.js
packages/portal/swagger-ui-web-component/src/register.js
packages/portal/swagger-ui-web-component/src/utils.js
packages/portal/swagger-ui-web-component/webpack.config.js
pnpm-lock.yaml

Created `swagger-ui-web-component package`

feat(portal): create swagger-ui-web-component package

---

packages/portal/spec-renderer-mini/sandbox/App.vue
packages/portal/spec-renderer-mini/src/components/SpecRendererMini.vue
packages/portal/spec-renderer-mini/src/types/specs.ts

Fix handling of tags to not bug if no description provided for a tag.

fix(mini-spec-renderer): handling tags correctly

---

packages/portal/spec-details/sandbox/App.vue
packages/portal/swagger-ui-web-component/src/element.js

Fixes:
- checkbox visibility in `spec-details` sandbox
- misc TS warnings/errors
- hide the schemes container when `essentialsOnly` in `swagger-ui-web-component`

fix(spec-details): misc fixes

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

A minor bump for a styling fix

chore: bump swagger ui kong theme for minor style fix

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

chore: bump swagger ui kong theme

---

CODEOWNERS
packages/core/app-layout/README.md
packages/core/app-layout/docs/sidebar.md
packages/core/copy-uuid/LICENSE
packages/core/copy-uuid/README.md
packages/core/copy-uuid/package.json
packages/core/copy-uuid/sandbox/App.vue
packages/core/copy-uuid/sandbox/index.html
packages/core/copy-uuid/sandbox/index.ts
packages/core/copy-uuid/sandbox/tsconfig.json
packages/core/copy-uuid/src/components/CopyUuid.cy.ts
packages/core/copy-uuid/src/components/CopyUuid.vue
packages/core/copy-uuid/src/const.ts
packages/core/copy-uuid/src/global-components.d.ts
packages/core/copy-uuid/src/index.ts
packages/core/copy-uuid/src/locales/en.json
packages/core/copy-uuid/src/types/index.ts
packages/core/copy-uuid/src/types/notify.ts
packages/core/copy-uuid/tsconfig.build.json
packages/core/copy-uuid/tsconfig.json
packages/core/copy-uuid/vite.config.ts
pnpm-lock.yaml

This PR migrates `copy-uuid` from `@kong-ui/copy-uuid`.

feat(copy-uuid): create component

---

pnpm-lock.yaml

This PR fixes the lockfile to resolve failed CI pipeline: https://github.com/Kong/public-ui-components/actions/runs/4049752568/jobs/6966465179

fix(copy-uuid): broken lockfile

---

packages/core/copy-uuid/package.json
pnpm-lock.yaml

fix(deps): resolve proper dependencies

---

README.md
docs/package-publishing.md
packages/core/cli/src/__template__/package.json

Add docs for package publishing.

docs: publishing

---

packages/portal/document-viewer/src/components/nodes/Code.vue
packages/portal/document-viewer/src/components/nodes/CodeBlock.vue
packages/portal/document-viewer/src/components/nodes/Text.vue
packages/portal/document-viewer/src/components/nodes/TextBlock.vue
packages/portal/document-viewer/src/components/renderChildren.tsx

Minor fixes for padding / margin, and then fixes issue with rendering `TextBlock`

chore: fix spacing issues for code, render for textblock

---

packages/portal/spec-renderer/docs/spec-operations-list.md
packages/portal/spec-renderer/package.json
packages/portal/spec-renderer/sandbox/pages/SpecOperationsList.vue
packages/portal/spec-renderer/src/components/SpecDetails.vue
packages/portal/spec-renderer/src/components/SpecOperationsList.vue
packages/portal/spec-renderer/src/components/SpecRenderer.vue
packages/portal/spec-renderer/src/components/operations-list/OperationsListItem.vue
packages/portal/spec-renderer/src/components/operations-list/OperationsListSectionHeader.vue
packages/portal/spec-renderer/src/composables/index.ts
packages/portal/spec-renderer/src/composables/useI18n.ts
packages/portal/spec-renderer/src/composables/useUtilities.spec.ts
packages/portal/spec-renderer/src/composables/useUtilities.ts
packages/portal/spec-renderer/src/locales/en.json
pnpm-lock.yaml

Fixes:
- i18n
- move helper logic into composable + test
- general code hygiene

fix(spec-renderer): i18n + code hygiene

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

Bumping package for minor style fixes

chore: bump swagger-ui-kong-theme-universal

---

packages/portal/spec-renderer/src/components/SpecDetails.vue

chore: remove leftover h1 in spec details

---

packages/portal/document-viewer/src/components/DocumentViewer.vue
packages/portal/document-viewer/src/components/nodes/Heading.vue
packages/portal/document-viewer/src/index.ts
packages/portal/document-viewer/src/utils/addUniqueHeadingSlugs.ts
packages/portal/document-viewer/src/utils/index.ts
packages/portal/document-viewer/src/utils/toSlug.ts

This is a convenience that I think folks would expect to find, and allows for linking section headings directly via anchor tags

feat(portal): add id to headings [TDX-2849]

---

renovate.json

Update Renovate settings to add stability days with kong package override

chore(renovate): add stability days with kong package override

---

packages/core/cli/README.md

docs(cli): add documentation

---

package.json
packages/core/app-layout/README.md
packages/core/app-layout/docs/navbar.md
packages/core/app-layout/docs/sidebar.md
packages/core/app-layout/package.json
packages/core/app-layout/sandbox/components/NavLinks.vue
packages/core/app-layout/sandbox/pages/LayoutPage.vue
packages/core/app-layout/sandbox/pages/NavbarPage.vue
packages/core/app-layout/sandbox/pages/SidebarPage.vue
packages/core/app-layout/src/components/AppLayout.cy.ts
packages/core/app-layout/src/components/AppLayout.vue
packages/core/app-layout/src/components/navbar/AppNavbar.cy.ts
packages/core/app-layout/src/components/navbar/AppNavbar.vue
packages/core/app-layout/src/components/sidebar/AppSidebar.cy.ts
packages/core/app-layout/src/components/sidebar/AppSidebar.vue
packages/core/app-layout/src/components/sidebar/SidebarItem.vue
packages/core/app-layout/src/components/sidebar/SidebarToggle.vue
packages/core/app-layout/src/styles/_variables.scss
packages/core/app-layout/src/styles/variables/_app-layout.scss
packages/core/app-layout/src/styles/variables/_app-navbar.scss
packages/core/app-layout/src/styles/variables/_app-sidebar.scss
packages/core/app-layout/src/styles/variables/_breakpoints.scss
packages/core/copy-uuid/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

Update the AppLayout component for the unification UX
> **Note**: the updates to the search component and navbar items will be handled separately

feat(app-layout): unification ux updates [KHCP-5798]

---

.github/workflows/ci.yaml
packages/core/i18n/README.md

fix: do not attempt to generate changelog when publishing previews

---

packages/core/app-layout/sandbox/pages/LayoutPage.vue
packages/core/app-layout/src/components/sidebar/SidebarItem.vue

Update specific icon stroke CSS rule -- this will need to be supplemented later by less-specific rules but is fine for now.

fix(icons): update stroke rule

---

packages/analytics/metric-cards/sandbox/App.vue
packages/analytics/metric-cards/src/components/MetricCardContainer.vue
packages/analytics/metric-cards/src/components/display/MetricsCard.vue
packages/analytics/metric-cards/src/styles/variables/_utilities.scss
packages/analytics/metric-cards/src/types/metric-card.ts

fix(metric-cards): recursively define card size [MA-1446]

---

packages/portal/spec-renderer/docs/spec-operations-list.md
packages/portal/spec-renderer/src/components/operations-list/OperationsListItem.vue

Addresses:
[https://konghq.atlassian.net/browse/KHCP-5779](https://konghq.atlassian.net/browse/KHCP-5779)

fix(spec-operations): update badge colors [khcp-5779]

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

fix(web-component): bump swagger ui kong theme universal pkg

---

packages/core/i18n/README.md
packages/core/i18n/sandbox/index.ts

fix(i18n): plugin usage

---

packages/portal/document-viewer/fixtures/markdown-data.ts
packages/portal/document-viewer/src/components/nodes/List.vue
packages/portal/document-viewer/src/components/nodes/ListItem.vue
packages/portal/document-viewer/src/components/nodes/TaskCheckbox.vue
packages/portal/document-viewer/src/components/renderChildren.tsx
packages/portal/document-viewer/src/types/index.ts

Supports GFM - which includes a task list (and nested ones too)

feat(document-viewer): support task lists (TDX-2943)

---

.github/workflows/ci.yaml

upload bundle analyzer result as artifact

chore: upload bundle analyzer result as artifact [KHCP-6645]

---

packages/core/app-layout/src/components/navbar/AccountDropdown.vue

…per team discussion https://kongstrong.slack.com/archives/C04L827S4KE/p1679506097682559

fix(accountDropdown): adjust accountDropdown icon size and font-size [KHCP-6613]

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

Bumps the version of the `swagger-ui-kong-theme-universal` to include various style fixes for some inputs, as well as setting a fixed font color for the `CodeSnippetWidget`

fix(web-component): various style fixes for swagger ui web component

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

Bump version package to include fixes for some styling issues regarding buttons

fix: bump swagger ui kong theme in web component (TDX-2991) (TDX-2992)

---

packages/analytics/metric-cards/src/components/MetricCardContainer.cy.ts
packages/analytics/metric-cards/src/components/MetricCardContainer.vue

fix(metric-cards): round approximate numbers by default

---

package.json
packages/analytics/metric-cards/package.json
packages/core/app-layout/package.json
packages/core/copy-uuid/package.json
packages/core/misc-widgets/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

Adopt the latest kongponents to pick up https://github.com/Kong/kongponents/pull/1263.
- bump all packages to the latest version of Kongponents
Part of https://konghq.atlassian.net/browse/KHCP-6528

chore(*): kongponents v8.47.0

---

package.json
pnpm-lock.yaml
renovate.json

fix(deps): update vue-tsc to 1.5.3

---

packages/core/app-layout/src/components/AppLayout.vue
packages/core/app-layout/src/styles/_base.scss
packages/core/app-layout/src/styles/variables/_app-layout.scss

Change the app layout main content area background color to white.

feat(app-layout): update main content background color

---

packages/core/app-layout/src/components/AppLayout.vue
packages/core/app-layout/src/styles/_base.scss
packages/core/app-layout/src/styles/variables/_app-layout.scss

This reverts commit 17840405787129e17a5ef68187967637c759fba0.
Waiting to roll out when the card borders, etc. are ready.

revert(app-layout): main content background color

---

.github/workflows/ci.yaml
.github/workflows/pr-closed.yml
packages/core/app-layout/src/index.ts

chore: use public npm token [KHCP-7211]

---

.github/workflows/ci.yaml

Packages should be public, not private.

fix(cli): publish as public

---

.github/actions/setup-pnpm-with-dependencies/action.yaml

To keep node version in development controlled by Volta and node version in CI in sync.

chore: reading node version from volta section of package.json [KHCP-7234]

---

.github/workflows/pr-closed.yml

fix: npm token reference

---

packages/analytics/analytics-utilities/src/types/analytics-data.ts

New interface to describe the v2 return type

fix(explore-v2-meta): Adding explore-v2 meta blob. start->startMs, end->endMs

---

packages/analytics/analytics-utilities/src/queryTime.ts

feat(query-time): add `startMs` and `endMs` helpers to QueryTime

---

packages/analytics/analytics-utilities/src/types/analytics-data.ts

feat: also allow v2 meta in explore result [MA-1675]

---

packages/analytics/analytics-utilities/src/types/query-time.ts

fix(analytics-utilities): Add `startMs` and `endMs` to interface

---

packages/analytics/analytics-utilities/package.json
packages/analytics/analytics-utilities/vite.config.ts

Bundle .cjs file into the `dist/` to support CommonJS environments (i.e. NodeJS apps).

fix(analytics-utilities): support commonjs

---

packages/core/copy-uuid/vite.config.ts
vite.config.shared.ts

fix(copy-uuid): externalize i18n

---

.github/workflows/ci.yaml
.github/workflows/pr-closed.yml

Silence pnpm for lerna commands

fix(ci): silence pnpm for lerna commands

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

Updates the `swagger-ui-kong-theme-universal` package to fix some styling issues

fix(spec-renderer): update package to fix servers container styling

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

Updates the package to fix an issue with font color in the `servers` container of a spec.

feat(swagger-ui-web-component): update swagger ui kong theme pkg

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

Updates theme to fix spacing between the `.servers` elements

feat(spec-renderer): update theme to fix spacing between elements

---

packages/analytics/analytics-chart/sandbox/App.vue
packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
packages/analytics/analytics-chart/src/composables/useLineChartOptions.ts
packages/analytics/analytics-chart/src/types/chartjs-options.ts

also update sandbox to mimic explorev2
https://konghq.atlassian.net/browse/MA-1725

fix: handle ms timerange [MA-1725]

---

packages/analytics/analytics-utilities/src/types/analytics-data.ts

Sometimes we don't return the record version. This should be optional.

fix(version-optional): AnalyticsRecord versions are optional

---

packages/portal/spec-renderer/src/components/SpecOperationsList.vue

[Jira task](https://konghq.atlassian.net/browse/KHCP-7933)

fix(spec-renderer): fix if value is empty [KHCP-7933]

---

packages/analytics/analytics-chart/sandbox/App.vue
packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
packages/analytics/analytics-chart/src/components/chart-types/DoughnutChart.vue
packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
packages/analytics/analytics-chart/src/styles/base.scss

https://konghq.atlassian.net/browse/MA-1849

feat: move chart title to outer shell [MA-1849]

---

packages/analytics/analytics-chart/src/types/chart-data.ts

Encountered an issue when trying to use this package in the new konnect-portal:

fix: use relative path for enums [MA-1788]

---

packages/core/cli/README.md
packages/core/cli/src/__template__/sandbox/tsconfig.json
packages/core/cli/src/core/package.ts
packages/core/cli/src/questions.ts
vite.config.shared.ts

Add the new `entities` workspace in preparation for moving the `shared-ui-components/packages/entities/*` packages to this repository.

feat(cli): add entities workspace [KHCP-7981]

---

tsconfig.json

dont generate sourcemap as part of npm package
https://konghq.atlassian.net/browse/KHCP-7565

feat(sourcemaps): dont generate sourcemap as part of npm package [KHCP-7565]

---

packages/core/app-layout/src/components/sidebar/SidebarItem.vue

Tweak the sidebar item truncation

fix(app-layout): tweak sidebar item truncation

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

Updates the `swagger-ui-kong-theme-universal` package to have styling fixes

feat(spec-renderer): update package to have style fixes for responses

---

package.json
packages/core/app-layout/src/components/AppLayout.vue
pnpm-lock.yaml

https://konghq.atlassian.net/browse/KHCP-7734
Disable Uncaught "ResizeObserver loop limit exceeded" error

fix(app-layout): add fix for ResizeObserver [KHCP-7734]

---

package.json
packages/analytics/analytics-chart/package.json
packages/analytics/metric-cards/package.json
packages/core/app-layout/package.json
packages/core/copy-uuid/package.json
packages/core/core/package.json
packages/core/i18n/package.json
packages/core/misc-widgets/package.json
packages/portal/document-viewer/package.json
packages/portal/document-viewer/src/components/nodes/TaskCheckbox.vue
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

Upgrade Vue to `3.3.x` and related dependencies.

feat(*): upgrade to vue 3.3.x [KHCP-7567]

---

docs/moving-packages.md

chore(docs): pull in changes from shared-ui-components

---

packages/core/app-layout/src/components/pageHeader/AppPageHeader.vue

fix(app-page-header): min height style

---

packages/core/app-layout/src/components/pageHeader/AppPageHeader.vue

Add default margin bottom to `AppPageLayout` component

fix(app-layout): add default spacing to AppPageLayout

---

.github/workflows/ci.yaml

ci: update change files logic

---

packages/analytics/analytics-utilities/src/types/analytics-data.ts

feat(analytics): add interface for explore v3 types

---

packages/analytics/analytics-chart/docs/top-n-table.md
packages/analytics/analytics-chart/sandbox/App.vue
packages/analytics/analytics-chart/src/components/TopNTable.cy.ts
packages/analytics/analytics-chart/src/components/TopNTable.vue
packages/analytics/analytics-chart/src/enums/chart-types-simple.enum.ts
packages/analytics/analytics-chart/src/index.ts
packages/analytics/analytics-chart/src/locales/en.json

Create new `TopNTable` component for [KHCP-8612](https://konghq.atlassian.net/browse/KHCP-8612).
[KHCP-8612]: https://konghq.atlassian.net/browse/KHCP-8612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(top-n-table): new component [khcp-8612]

---

packages/analytics/analytics-chart/src/locales/en.json

https://konghq.atlassian.net/browse/MA-1955

fix(analytics-chart): runtime group rename to control plane [MA-1955]

---

packages/analytics/analytics-chart/src/locales/en.json

fix(analytics-chart): new translation key for control plane

---

packages/analytics/analytics-chart/sandbox/App.vue
packages/analytics/analytics-chart/src/components/AnalyticsChart.cy.ts
packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
packages/analytics/analytics-chart/src/components/SimpleChart.vue
packages/analytics/analytics-chart/src/components/chart-plugins/ChartTooltip.vue
packages/analytics/analytics-chart/src/components/chart-plugins/HighlightPlugin.ts
packages/analytics/analytics-chart/src/components/chart-plugins/VerticalLinePlugin.ts
packages/analytics/analytics-chart/src/components/chart-types/DoughnutChart.vue
packages/analytics/analytics-chart/src/components/chart-types/GaugeChart.vue
packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
packages/analytics/analytics-chart/src/composables/useChartJSCommon.ts
packages/analytics/analytics-chart/src/utils/commonOptions.ts

See loom linked on the ticket to see the issues
https://konghq.atlassian.net/browse/MA-1984
https://konghq.atlassian.net/browse/MA-1903
https://konghq.atlassian.net/browse/MA-1987
- There was no reason for `StackedBarChart` to reference the `VerticalLinePlugin` in any way. Removed.
- Reset tooltip show/locked state when chart type changes on `TimeSeriesChart`
- Reset tooltip show/locked state when chart orientation changes in `StackedBarChart`
- Highlight plugin - perform cleanup when plugin is destroyed
- Vertical line plugin - perform cleanup when plugin is destroyed
- Set minimum height on tooltip title container
- Some refactoring/cleanup of unnecessary `toRef` calls on props which are already reactive by default.
https://www.loom.com/share/57a075219bde46a48415417c5d346ce7

fix(analytics-chart): fix tooltip bugs [MA-1984]

---

packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue

https://konghq.atlassian.net/browse/MA-1942

fix(analytics-chart): centering issue with legend item icon [MA-1942]

---

packages/core/app-layout/src/components/sidebar/AppSidebar.vue

fix(app-layout): update default z-index

---

packages/analytics/analytics-chart/sandbox/App.vue

fix: analytics-chart sandbox empty state toggle was confusing

---

packages/core/forms/src/forms/ExitTransformer.vue
packages/core/forms/src/forms/PostFunction.vue
packages/entities/entities-plugins/src/composables/usePluginMeta.ts

fix(forms): check if translation exists

---

packages/entities/entities-consumer-groups/src/locales/en.json
packages/entities/entities-consumers/src/locales/en.json
packages/entities/entities-gateway-services/src/locales/en.json
packages/entities/entities-vaults/src/locales/en.json

Fix spelling in strings for [KHCP-8676](https://konghq.atlassian.net/browse/KHCP-8676).
[KHCP-8676]: https://konghq.atlassian.net/browse/KHCP-8676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(entities): spelling [khcp-8676]

---

packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
packages/analytics/analytics-chart/src/components/chart-plugins/ChartTooltip.vue

https://konghq.atlassian.net/browse/MA-2076

fix(analytics-chart): tooltip clipping issue

---

.github/workflows/ci.yaml

Create PR package previews for PRs with the label `create preview package`

ci: create previews for pr with label

---

vite.config.shared.ts

Update the proxy for `au` region

chore(vite): update proxies for au region [KHCP-9346]

---

packages/entities/entities-certificates/src/components/CACertificateConfigCard.vue
packages/entities/entities-certificates/src/components/CertificateConfigCard.vue
packages/entities/entities-gateway-services/src/components/GatewayServiceConfigCard.vue
packages/entities/entities-plugins/src/components/PluginConfigCard.vue
packages/entities/entities-routes/src/components/RouteConfigCard.vue
packages/entities/entities-shared/docs/config-card-display.md
packages/entities/entities-shared/docs/entity-base-config-card.md
packages/entities/entities-shared/package.json
packages/entities/entities-shared/sandbox/pages/ConfigCardDisplayPage.vue
packages/entities/entities-shared/sandbox/routes.ts
packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardDisplay.cy.ts
packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardDisplay.vue
packages/entities/entities-shared/src/components/entity-base-config-card/EntityBaseConfigCard.cy.ts
packages/entities/entities-shared/src/components/entity-base-config-card/EntityBaseConfigCard.vue
packages/entities/entities-shared/src/composables/index.ts
packages/entities/entities-shared/src/composables/useHelpers.ts
packages/entities/entities-shared/src/index.ts
packages/entities/entities-shared/src/locales/en.json
packages/entities/entities-shared/src/types/app-config.ts
packages/entities/entities-shared/src/types/entity-base-config-card.ts
packages/entities/entities-upstreams-targets/src/components/UpstreamsConfigCard.vue
pnpm-lock.yaml

Addresses:
[https://konghq.atlassian.net/browse/KHCP-9212](https://konghq.atlassian.net/browse/KHCP-9212)
Test PR in Konnect: [https://github.com/Kong/khcp-ui/pull/6910](https://github.com/Kong/khcp-ui/pull/6910)
`FF: khcp-8778-json-yaml-configurations`

feat(config-card-display): json-yaml format [khcp-9212]

---

packages/entities/entities-certificates/docs/ca-certificate-config-card.md
packages/entities/entities-certificates/docs/certificate-config-card.md
packages/entities/entities-certificates/src/components/CACertificateConfigCard.vue
packages/entities/entities-certificates/src/components/CertificateConfigCard.vue
packages/entities/entities-consumer-groups/docs/consumer-group-config-card.md
packages/entities/entities-consumer-groups/src/components/ConsumerGroupConfigCard.vue
packages/entities/entities-consumers/docs/consumer-config-card.md
packages/entities/entities-consumers/src/components/ConsumerConfigCard.vue
packages/entities/entities-gateway-services/docs/gateway-service-config-card.md
packages/entities/entities-gateway-services/src/components/GatewayServiceConfigCard.vue
packages/entities/entities-key-sets/docs/key-set-config-card.md
packages/entities/entities-key-sets/src/components/KeySetConfigCard.vue
packages/entities/entities-keys/docs/key-config-card.md
packages/entities/entities-keys/src/components/KeyConfigCard.vue
packages/entities/entities-plugins/docs/plugin-config-card.md
packages/entities/entities-plugins/src/components/PluginConfigCard.vue
packages/entities/entities-routes/docs/route-config-card.md
packages/entities/entities-routes/src/components/RouteConfigCard.vue
packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardDisplay.vue
packages/entities/entities-shared/src/components/entity-base-config-card/EntityBaseConfigCard.vue
packages/entities/entities-upstreams-targets/docs/upstreams-config-card.md
packages/entities/entities-upstreams-targets/src/components/UpstreamsConfigCard.vue
packages/entities/entities-vaults/docs/vault-config-card.md
packages/entities/entities-vaults/src/components/VaultConfigCard.vue

Addresses:
[https://konghq.atlassian.net/browse/KHCP-9356](https://konghq.atlassian.net/browse/KHCP-9356)
- Adopt `ConfigCardDisplay` component in all the entities in public-ui-components by adding in new prop.
- Updates the md files

feat(config-card-display): adopt in all entities [khcp-9356]

---

packages/core/app-layout/README.md
packages/core/app-layout/sandbox/pages/NavbarPage.vue
packages/core/app-layout/sandbox/pages/SidebarPage.vue
packages/core/app-layout/src/components/AppLayout.vue
packages/core/app-layout/src/styles/_base.scss
packages/core/app-layout/src/styles/variables/_app-layout.scss
packages/entities/entities-shared/src/components/entity-base-form/EntityBaseForm.vue
packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue

Style updates to support white background.
Part of [KHCP-8591](https://konghq.atlassian.net/browse/KHCP-8591).
[KHCP-8591]: https://konghq.atlassian.net/browse/KHCP-8591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(app-layout): body background to white [khcp-8591]

---

packages/core/error-boundary/sandbox/App.vue
packages/core/error-boundary/src/components/ErrorBoundary.vue
packages/core/error-boundary/src/types/error-boundary.ts

Include the component `data-testid` attribute, if it exists, in the `context`

feat(error-boundary): include data-testid [KHCP-9478]

---

packages/entities/entities-vaults/src/components/VaultForm.vue
packages/entities/entities-vaults/src/locales/en.json
packages/entities/entities-vaults/src/types/vault-form.ts

This PR updates Azure vault form fields according to [the gateway schema](https://github.com/Kong/kong-ee/blob/master/kong/vaults/azure/schema.lua).

fix(vault): update form fields for Azure vault

---

README.md

chore(readme): update pnpm version

---

packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue

fix(entities-consumer-credential): disable row click for the list

---

packages/entities/entities-routes/src/components/RouteForm.cy.ts
packages/entities/entities-routes/src/routes-endpoints.ts

This PR removes an unnecessary trailing slash.

fix(entities-routes): remove a trailing slash

---

packages/analytics/analytics-utilities/docs/analytics-utils.md
packages/analytics/analytics-utilities/docs/classes/DeltaQueryTime.md
packages/analytics/analytics-utilities/docs/classes/Timeframe.md
packages/analytics/analytics-utilities/docs/classes/TimeseriesQueryTime.md
packages/analytics/analytics-utilities/docs/classes/UnaryQueryTime.md
packages/analytics/analytics-utilities/docs/enums/ChartTypes.md
packages/analytics/analytics-utilities/docs/interfaces/AnalyticsExploreRecord.md
packages/analytics/analytics-utilities/docs/interfaces/AnalyticsExploreResult.md
packages/analytics/analytics-utilities/docs/interfaces/AnalyticsExploreV2Meta.md
packages/analytics/analytics-utilities/docs/interfaces/AnalyticsExploreV2Result.md
packages/analytics/analytics-utilities/docs/interfaces/AnalyticsExploreV3Meta.md
packages/analytics/analytics-utilities/docs/interfaces/AnalyticsExploreV3Result.md
packages/analytics/analytics-utilities/docs/interfaces/BaseExploreMeta.md
packages/analytics/analytics-utilities/docs/interfaces/QueryTime.md

https://konghq.atlassian.net/browse/MA-2211
Just catching us up on documentation updates

docs(analytics-utilities): generate docs [MA-2211]

---

packages/portal/swagger-ui-web-component/src/element.js

This adds properties to override swagger defaults from `swagger-ui-kong-theme-universal`

feat: add customizable properties to swagger-ui-web-component

---

packages/portal/spec-renderer/docs/spec-details.md
packages/portal/spec-renderer/sandbox/pages/SpecDetails.vue
packages/portal/spec-renderer/src/components/SpecDetails.vue
packages/portal/swagger-ui-web-component/src/element.js

Adds props to pass them down to swagger

feat(spec-details): add customizable code snippet languages for swagger

---

packages/analytics/analytics-chart/src/components/TopNTable.cy.ts
packages/analytics/analytics-chart/src/components/TopNTable.vue
packages/analytics/analytics-utilities/src/types/analytics-data.ts

Part 1 of a breaking change to explore v3 to allow better deleted entity handling.

feat(analytics-*): support additional explore v3 variation [MA-2094]

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

BUmps the `swagger-ui-kong-theme` version

fix(swagger): bump swagger ui kong theme version

---

packages/entities/entities-consumer-groups/src/components/ConsumerGroupForm.vue
packages/entities/entities-keys/src/components/KeyForm.vue
packages/entities/entities-shared/src/composables/useDebouncedFilter.ts
packages/entities/entities-shared/src/composables/useHelpers.ts

This PR adds fuzzy search support to `useDebouncedFilter` when in Kong Manager if we have more than 100 records.

feat(entities-shared): fuzzy search filter

---

packages/core/copy-uuid/src/components/CopyUuid.vue

https://konghq.atlassian.net/browse/KHCP-9762
DD link: https://app.datadoghq.com/rum/error-tracking?query=%40application.id%3A6e430333-9e0f-4d6b-ac63-5f7d4ad9a641%20env%3Aprod%20-%40browser.name%3AHeadlessChrome%20%40issue.age%3A%3C%3D300000&issueId=db3ef672-8255-11ee-9ff0-da7ad0900002&view=spans&from_ts=1699901309000&to_ts=1699901609000&live=false

fix(copy-uuid): add optional chaining [KHCP-9762]

---

package.json
packages/analytics/analytics-chart/package.json
packages/analytics/analytics-metric-provider/package.json
packages/analytics/metric-cards/package.json
packages/core/app-layout/package.json
packages/core/copy-uuid/package.json
packages/core/forms/package.json
packages/core/misc-widgets/package.json
packages/core/sandbox-layout/package.json
packages/entities/entities-certificates/package.json
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumers/package.json
packages/entities/entities-gateway-services/package.json
packages/entities/entities-key-sets/package.json
packages/entities/entities-keys/package.json
packages/entities/entities-plugins/package.json
packages/entities/entities-routes/package.json
packages/entities/entities-shared/package.json
packages/entities/entities-snis/package.json
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-vaults/package.json
packages/entities/entities-vaults/src/components/VaultForm.vue
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

Fix KRadio card occurrences in VaultsForm.vue (screenshots)
Before
After

fix(entities-vaults): fix kradio card occurrences

---

packages/entities/entities-plugins/src/components/PluginEntityForm.vue
packages/entities/entities-plugins/src/components/PluginForm.vue
packages/entities/entities-plugins/src/components/PluginSelect.vue
packages/entities/entities-plugins/src/components/select/PluginSelectCard.vue
packages/entities/entities-plugins/src/components/select/PluginSelectGrid.vue
packages/entities/entities-plugins/src/types/plugin.ts

Misc. fixes for unification plugin forms for [KHCP-9513](https://konghq.atlassian.net/browse/KHCP-9513).
[KHCP-9513]: https://konghq.atlassian.net/browse/KHCP-9513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(plugins-form): general fixes [khcp-9513]

---

packages/analytics/analytics-chart/src/components/AnalyticsChart.vue

https://konghq.atlassian.net/browse/MA-2333

fix: remove default border and margins let host app dictate

---

packages/entities/entities-plugins/src/components/select/PluginSelectCard.vue

Fix KDropdownItem `danger` occurrences

fix(entities-plugins): fix kdropdownitem danger

---

packages/analytics/analytics-chart/src/components/AnalyticsChart.vue

fix: fix analytics chart dimensions make more predictable

---

packages/analytics/analytics-chart/sandbox/styles/charts-sandbox.scss
packages/core/forms/src/forms/OIDCForm.vue
packages/core/forms/src/generator/fields/advanced/FieldRadio.vue
packages/core/forms/src/generator/fields/advanced/FieldSelectionGroup.vue
packages/entities/entities-gateway-services/src/components/GatewayServiceForm.vue
packages/entities/entities-gateway-services/src/locales/en.json
packages/entities/entities-routes/src/components/RouteForm.vue
packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.vue
packages/entities/entities-shared/src/components/entity-base-config-card/EntityBaseConfigCard.vue

fix(*): misc style updates

---

packages/core/app-layout/src/styles/_base.scss

fix(app-layout): remove base font size

---

packages/entities/entities-plugins/src/components/PluginForm.vue

Don't try to verify the schema before create/editing an instance of a custom plugin.

fix(plugins): create custom instance

---

packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardDisplay.vue

https://konghq.atlassian.net/browse/KHCP-9837
Deploy Preview https://pr-7220--khcp-ui.cloud-preview.konghq.tech/

fix(entities-shared): remove dates from JSON/YAML config [KHCP-9837]

---

packages/entities/entities-plugins/src/plugins-endpoints.ts

Jira task [https://konghq.atlassian.net/browse/KHCP-9905](https://konghq.atlassian.net/browse/KHCP-9905)

feat(entities-plugins): endpoint fixes

---

packages/entities/entities-plugins/sandbox/pages/PluginConfigCardPage.vue
packages/entities/entities-plugins/sandbox/pages/PluginFormPage.vue
packages/entities/entities-plugins/sandbox/pages/PluginSelectPage.vue
packages/entities/entities-plugins/src/components/PluginSelect.cy.ts
packages/entities/entities-plugins/src/plugins-endpoints.ts

Update all plugin related endpoints to use `control-planes` endpoint

Update plugins endpoint

---

packages/entities/entities-plugins/src/components/custom-plugins/DeleteCustomPluginSchemaModal.vue

Change the delete custom plugin modal endpoint

Fix the delete custom modal endpoint

---

packages/analytics/analytics-chart/package.json
packages/analytics/analytics-metric-provider/package.json
packages/analytics/metric-cards/package.json
packages/core/app-layout/package.json
packages/core/copy-uuid/package.json
packages/core/forms/package.json
packages/core/misc-widgets/package.json
packages/core/sandbox-layout/package.json
packages/entities/entities-certificates/package.json
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumers/package.json
packages/entities/entities-gateway-services/package.json
packages/entities/entities-key-sets/package.json
packages/entities/entities-keys/package.json
packages/entities/entities-plugins/package.json
packages/entities/entities-routes/package.json
packages/entities/entities-shared/package.json
packages/entities/entities-snis/package.json
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-vaults/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json

Fixes peer dependencies kongponents version

chore(deps): fix peer dependencies kongponents version

---

packages/analytics/analytics-chart/src/components/chart-plugins/ChartTooltip.vue

CSS transform better for performance. 
You can generate the 4x4 DOMMatrix of a particular element's `transform` style and access the translation from the 4th column. `m41` and `m42` for x and y translation respectively.

refactor: use css transforms for tooltip positioning

---

packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.vue

This PR fixes method badges wrapping in config card.
|Before|After|
|  ----  | ----  |
|<img width="1704" alt="image" src="https://github.com/Kong/public-ui-components/assets/10095631/c7ec76d3-4286-4b1c-8094-04e373507b32">|<img width="1611" alt="image" src="https://github.com/Kong/public-ui-components/assets/10095631/9aee1471-3c8f-4d5f-bda1-f35476ced8f1">|

fix(entities-shared): method badges wrapping

---

packages/entities/entities-shared/sandbox/pages/ConfigCardDisplayPage.vue
packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardDisplay.cy.ts
packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardDisplay.vue
packages/entities/entities-shared/src/components/entity-base-config-card/EntityBaseConfigCard.vue
packages/entities/entities-shared/src/locales/en.json

https://konghq.atlassian.net/browse/KHCP-9930
Figma: https://www.figma.com/file/lMlPMQbyV3PX1VFVOVF7Kz/YAML-%26-JSON-Format-in-konnect?type=design&node-id=1689-1293&mode=design&t=C3d8M4Ek2348yy8U-0
Deploy Preview: https://pr-7280--khcp-ui.cloud-preview.konghq.tech/

feat(entities-shared): add the get endpoint in the config tables [KHCP-9930]

---

packages/entities/entities-plugins/src/components/PluginSelect.vue
packages/entities/entities-plugins/src/plugins-endpoints.ts

In KM OSS, the endpoint for fetching available plugins is `/`.

fix(entities-plugins): endpoint for KM OSS

---

packages/entities/entities-plugins/fixtures/mockData.ts
packages/entities/entities-plugins/src/components/PluginForm.cy.ts
packages/entities/entities-plugins/src/components/PluginForm.vue
packages/entities/entities-plugins/src/components/PluginSelect.cy.ts

Add component tests for `PluginForm`.
For [KHCP-9775](https://konghq.atlassian.net/browse/KHCP-9775).
[KHCP-9775]: https://konghq.atlassian.net/browse/KHCP-9775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(plugins/form): add component tests [khcp-9775]

---

packages/entities/entities-plugins/src/components/PluginConfigCard.vue

[Jira task](https://konghq.atlassian.net/browse/KHCP-10007)

feat(entities-plugins): replace copyUuid to InternalLinkItem

---

packages/analytics/analytics-chart/package.json
pnpm-lock.yaml

https://konghq.atlassian.net/browse/MA-1926
This PR fixed a chartjs internal tooltip-related bug 
https://github.com/apertureless/vue-chartjs/pull/1064

feat: update vue-chartjs version to fix tooltip bug [MA-1926]

---

packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue

https://konghq.atlassian.net/browse/MA-2421

fix: reactivity issue in computing the chart height

---

packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
packages/analytics/analytics-chart/src/components/chart-types/DoughnutChart.vue
packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
packages/analytics/analytics-chart/src/composables/index.ts
packages/analytics/analytics-chart/src/composables/useChartLegendValues.ts
packages/analytics/analytics-chart/src/composables/useTranslatedUnits.spec.ts
packages/analytics/analytics-chart/src/composables/useTranslatedUnits.ts
packages/analytics/analytics-chart/src/locales/en.json
packages/analytics/analytics-chart/src/types/chartjs-options.ts
packages/analytics/analytics-chart/src/utils/commonOptions.ts

fix(charts): properly pluralize tooltip and legend values [MA-2360]

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

Bumps version of `swagger-ui-kong-theme` to fix a bug with some responses causing the section to error and have issues rendering.

fix: bump version of swagger ui kong theme (TDX-3699)

---

packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue

https://konghq.atlassian.net/browse/MA-2453

fix: legend offset pluse tweaks and improvements to legend styling

---

packages/entities/entities-certificates/src/components/CACertificateList.vue
packages/entities/entities-certificates/src/components/CertificateList.vue
packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue
packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
packages/entities/entities-consumers/src/components/ConsumerList.vue
packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-key-sets/src/components/KeySetList.vue
packages/entities/entities-keys/src/components/KeyList.vue
packages/entities/entities-plugins/src/components/PluginList.vue
packages/entities/entities-routes/src/components/RouteList.vue
packages/entities/entities-snis/src/components/SniList.vue
packages/entities/entities-upstreams-targets/src/components/TargetsList.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
packages/entities/entities-vaults/src/components/VaultList.vue

This PR clears the following warning:
We don't have `#kong-ui-app-page-header-action-button` in KM.

fix(entities): teleport warning

---

packages/entities/entities-routes/src/components/RouteForm.vue

Small fixes for DD errors for [KHCP-10204](https://konghq.atlassian.net/browse/KHCP-10204).
[KHCP-10204]: https://konghq.atlassian.net/browse/KHCP-10204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(routes): datadog errors [khcp-10204]

---

packages/entities/entities-plugins/src/index.ts

Export plugin endpoints for use in `khcp-ui` plugin e2e's.

fix(plugins): export endpoints [khcp-10220]

---

packages/entities/entities-shared/docs/entity-base-config-card.md
packages/entities/entities-shared/docs/entity-base-form.md

Document the jsonYamlMilestone2Enabled prop in the EntityBaseForm README as well as the EntityBaseConfigCard README.
Follow-up to https://github.com/Kong/public-ui-components/pull/1006

fix(*): update readme [khcp-9892]

---

packages/entities/entities-shared/src/composables/useErrors.ts

Suppress `401` error messages from the UI, and instead allow the host app to respond accordingly.

fix(entities-shared): suppress 401 errors [KHCP-10222]

---

packages/entities/entities-plugins/src/components/PluginIcon.vue

Fix 403s caused by attempting to fetch an `undefined` asset.

fix(plugins): icon rendering conditionals

---

packages/entities/entities-plugins/src/components/PluginEntityForm.vue

This PR fixes the following bug:
https://github.com/Kong/public-ui-components/assets/10095631/121a8c2e-9f07-495d-89a7-d9c33ababa13
A regression test will be added in KM: https://github.com/Kong/kong-admin/pull/3137

fix(entities-plugins): schema watcher

---

packages/entities/entities-plugins/sandbox/pages/PluginFormPage.vue
packages/entities/entities-plugins/src/components/PluginForm.vue
packages/entities/entities-shared/docs/entity-base-config-card.md
packages/entities/entities-shared/docs/entity-base-form.md
packages/entities/entities-shared/sandbox/pages/ConfigCardDisplayPage.vue
packages/entities/entities-shared/sandbox/pages/EntityBaseFormPage.vue
packages/entities/entities-shared/src/components/common/JsonCodeBlock.cy.ts
packages/entities/entities-shared/src/components/common/JsonCodeBlock.vue
packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardDisplay.cy.ts
packages/entities/entities-shared/src/components/entity-base-form/EntityBaseForm.cy.ts
packages/entities/entities-shared/src/components/entity-base-form/EntityBaseForm.vue
packages/entities/entities-shared/src/types/entity-base-config-card.ts
packages/entities/entities-shared/src/types/entity-base-form.ts

From slack thread feedback https://kongstrong.slack.com/archives/C03ANC23AQK/p1704474391613789
Consuming app https://github.com/Kong/khcp-ui/pull/7373

fix(*): rename ff and update docs

---

lerna.json

fix: lerna config

---

packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts

fix(dashboard-renderer): default in the schema makes prop required

---

package.json
packages/analytics/analytics-chart/package.json
packages/analytics/analytics-metric-provider/package.json
packages/analytics/dashboard-renderer/package.json
packages/analytics/metric-cards/package.json
packages/core/app-layout/package.json
packages/core/copy-uuid/package.json
packages/core/documentation/package.json
packages/core/forms/package.json
packages/core/misc-widgets/package.json
packages/core/sandbox-layout/package.json
packages/entities/entities-certificates/package.json
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumers/package.json
packages/entities/entities-gateway-services/package.json
packages/entities/entities-key-sets/package.json
packages/entities/entities-keys/package.json
packages/entities/entities-plugins/package.json
packages/entities/entities-routes/package.json
packages/entities/entities-shared/package.json
packages/entities/entities-snis/package.json
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-vaults/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

chore(app-layout): bump kongponents

---

.github/workflows/ci.yaml

bumping upload / download artifacts to V4

chore: use v4 of artifact actions [KHCP-10250]

---

packages/entities/entities-plugins/src/components/PluginConfigCard.vue

fix(entities-plugins): `schema.value.fields` undefined

---

package.json
packages/analytics/analytics-chart/package.json
packages/analytics/analytics-metric-provider/package.json
packages/analytics/dashboard-renderer/package.json
packages/analytics/metric-cards/package.json
packages/core/app-layout/package.json
packages/core/copy-uuid/package.json
packages/core/documentation/package.json
packages/core/forms/package.json
packages/core/misc-widgets/package.json
packages/core/sandbox-layout/package.json
packages/entities/entities-certificates/package.json
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumers/package.json
packages/entities/entities-gateway-services/package.json
packages/entities/entities-key-sets/package.json
packages/entities/entities-keys/package.json
packages/entities/entities-plugins/package.json
packages/entities/entities-routes/package.json
packages/entities/entities-shared/package.json
packages/entities/entities-snis/package.json
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-vaults/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

Jira: https://konghq.atlassian.net/browse/KHCP-10381
Phase 5 adoption of components reskinned in alpha version of Kongponents v9 release. Includes these components:
- `KFileUpload`
- `KSegmentedControl` (unused)

fix(*): kongponents alpha phase 5 [KHCP-10381]

---

packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue

fix(dashboard-renderer): `console.warn` if query bridge is missing

---

packages/core/app-layout/src/components/sidebar/SidebarToggle.vue

fix(app-layout): prevent default click

---

packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
packages/analytics/analytics-chart/src/styles/base.scss
packages/analytics/analytics-chart/src/styles/mixins.scss

fix: scrollbar track was always showing in the legend

---

packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue

https://konghq.atlassian.net/browse/MA-2544
https://konghq.atlassian.net/browse/MA-2545

fix: some chart style tweaks + debounce ResizeObserver callback

---

packages/analytics/analytics-chart/src/composables/useExploreResultToTimeDatasets.ts
packages/analytics/analytics-chart/src/composables/useExploreResultToTimedDatasets.spec.ts
packages/analytics/analytics-chart/src/utils/defaultLineOptions.ts

fix: show border when not filled

---

packages/entities/entities-plugins/src/composables/usePluginMeta.ts

The `ai-prompt-template` plugin cannot be scoped to a consumer entity: https://github.com/Kong/kong-ee/blob/f589220d3b2692e589b36e1b9bcf3927671f41df/kong/plugins/ai-prompt-template/schema.lua#L33

fix(entities-plugins): ai-prompt-template scope

---

packages/analytics/analytics-chart/sandbox/pages/BarChartDemo.vue
packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
packages/analytics/analytics-chart/src/components/chart-plugins/ChartTooltip.vue

fix: style improvements + scrollbar updates in tooltip for consistency

---

packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue

fix: values should not display when legend snaps to the bottom

---

packages/entities/entities-plugins/src/components/PluginConfigCard.vue

fix(entities-plugins): add optional chaining [KHCP-10516]

---

.github/workflows/pr-packages.yaml

Jira: https://konghq.atlassian.net/browse/KHCP-10604
Adds workflow to verify PR doesn't reference any preview packages

ci: add verify pr workflow [KHCP-10604]

---

packages/analytics/analytics-utilities/src/types/explore-v4.ts

- `granularity_ms` is always present
- `granularity` is never present

fix(explore-types): update granularity in response meta [MA-2303]

---

packages/analytics/analytics-utilities/src/types/explore-v4.ts

fix(explore-types): add granularity values [MA-2594]

---

packages/analytics/analytics-utilities/src/granularity.ts
packages/analytics/analytics-utilities/src/types/granularity-keys.ts

feat(query-time): add second-level granularity [MA-2594]

---

packages/entities/entities-shared/src/components/common/YamlCodeBlock.vue

https://konghq.atlassian.net/browse/KHCP-10642
Also trims trailing newline from the yaml codeblock.
Deploy Preview https://pr-7583--khcp-ui.cloud-preview.konghq.tech/

fix(entities-shared): filter out null values and empty arrays from yaml in entity forms [KHCP-10642]

---

packages/core/documentation/src/components/DocumentationDisplay.vue

**Ticket:**
https://konghq.atlassian.net/browse/KHCP-10711

fix(documentation): align document meta and actions

---

packages/analytics/analytics-metric-provider/src/components/MetricsProvider.cy.ts
packages/analytics/analytics-metric-provider/src/components/MetricsProviderInternal.vue
packages/analytics/analytics-metric-provider/src/components/metricsProviderUtil.ts
packages/analytics/analytics-metric-provider/src/composables/useMetricFetcher.ts
packages/analytics/analytics-metric-provider/src/types/fetcher-types.ts
packages/analytics/analytics-utilities/src/timeframes.ts

fix(metric-provider): include timezone in v4 queries

---

packages/analytics/dashboard-renderer/package.json
packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue
packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts
packages/analytics/dashboard-renderer/vite.config.ts
pnpm-lock.yaml

Currently just supports golden signals.  Styling TBD.

feat(dashboard-renderer): add metric card renderer [MA-2307]

---

packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue

https://konghq.atlassian.net/browse/MA-2630

fix: metric-card styling in dashboards

---

packages/entities/entities-plugins/src/components/PluginForm.vue
packages/entities/entities-shared/src/components/entity-base-form/EntityBaseForm.vue

style(*): add offsetTop to kslideouts in json yaml forms

---

packages/analytics/analytics-metric-provider/package.json
packages/analytics/analytics-metric-provider/vite.config.ts
pnpm-lock.yaml

Reduces package size; potentially avoids versioning bugs.

chore(metric-provider): externalize analytics-utilities

---

packages/analytics/analytics-chart/src/styles/chart.scss

feat(analytics-chart): forgot the height [MA-2536]

---

packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue

fix: legend item labels should not wrap

---

packages/entities/entities-certificates/src/components/CACertificateList.vue
packages/entities/entities-certificates/src/components/CertificateList.vue
packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue
packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
packages/entities/entities-consumers/src/components/ConsumerList.vue
packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-key-sets/src/components/KeySetList.vue
packages/entities/entities-keys/src/components/KeyList.vue
packages/entities/entities-plugins/src/components/PluginList.vue
packages/entities/entities-routes/src/components/RouteList.vue
packages/entities/entities-snis/src/components/SniList.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
packages/entities/entities-vaults/src/components/VaultList.vue

https://konghq.atlassian.net/browse/KHCP-9907
Deploy Preview: https://pr-2549--gateway-manager.cloud-preview.konghq.tech/gateway-manager
Deploy Preview: https://pr-7672--khcp-ui.cloud-preview.konghq.tech/

fix(*): make filter input width take up max available space [KHCP-9907]

---

packages/entities/entities-shared/src/components/entity-filter/EntityFilter.vue

Adding a clear icon in `EntityFilter` when `isExactMatch` is `true`.
https://github.com/Kong/public-ui-components/assets/10095631/9a24665f-ae80-4958-aaa2-e00a2b5a1fc9
KHCP-10910

feat(entities-shared): add clear icon for EntityFilter in exact mode

---

packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
packages/analytics/analytics-chart/src/styles/chart.scss

https://konghq.atlassian.net/browse/MA-2670

feat(analytics-chart): title and legend [MA-2670]

---

packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
packages/analytics/analytics-chart/src/styles/chart.scss

fix: adjust legend height

---

packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
packages/analytics/analytics-chart/src/styles/chart.scss

fix: adjust one more time

---

packages/entities/entities-shared/docs/entity-base-config-card.md
packages/entities/entities-shared/src/components/entity-base-config-card/EntityBaseConfigCard.cy.ts
packages/entities/entities-shared/src/components/entity-base-config-card/EntityBaseConfigCard.vue
packages/entities/entities-shared/src/types/entity-base-config-card.ts

https://konghq.atlassian.net/browse/KHCP-10815
**konnect-ui-apps: https://pr-2584--gateway-manager.cloud-preview.konghq.tech/gateway-manager** 
**khcp-ui: https://pr-7704--khcp-ui.cloud-preview.konghq.tech/**

feat(*): remove json/yaml milestone 1 config table ff post GA [KHCP-10815]

---

packages/entities/entities-gateway-services/docs/gateway-service-list.md
packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-gateway-services/src/locales/en.json
packages/entities/entities-gateway-services/src/types/gateway-service-list.ts

Adding the ability to show a column of belonged control plane.

feat(entities-gateway-services): support control plane column

---

packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts
packages/analytics/dashboard-renderer/src/types/grid-layout-types.ts

https://konghq.atlassian.net/browse/MA-2663

feat(dashboard-renderer): add support for slottable tiles

---

CODEOWNERS
packages/analytics/analytics-config-store/LICENSE
packages/analytics/analytics-config-store/README.md
packages/analytics/analytics-config-store/package.json
packages/analytics/analytics-config-store/src/constants.ts
packages/analytics/analytics-config-store/src/index.ts
packages/analytics/analytics-config-store/src/stores/analytics-config.ts
packages/analytics/analytics-config-store/src/stores/index.ts
packages/analytics/analytics-config-store/tsconfig.build.json
packages/analytics/analytics-config-store/tsconfig.json
packages/analytics/analytics-config-store/vite.config.ts
packages/analytics/analytics-metric-provider/README.md
packages/analytics/analytics-metric-provider/package.json
packages/analytics/analytics-metric-provider/sandbox/App.vue
packages/analytics/analytics-metric-provider/sandbox/index.ts
packages/analytics/analytics-metric-provider/src/components/MetricsConsumer.vue
packages/analytics/analytics-metric-provider/src/components/MetricsProvider.cy.ts
packages/analytics/analytics-metric-provider/src/components/MetricsProviderInternal.vue
packages/analytics/analytics-metric-provider/src/components/MetricsTestHarness.vue
packages/analytics/analytics-metric-provider/src/components/metricsProviderUtil.ts
packages/analytics/analytics-metric-provider/src/composables/useMetricFetcher.spec.ts
packages/analytics/analytics-metric-provider/src/composables/useMetricFetcher.ts
packages/analytics/analytics-metric-provider/src/types/fetcher-types.ts
packages/analytics/analytics-utilities/src/types/query-bridge.ts
packages/analytics/dashboard-renderer/README.md
pnpm-lock.yaml

- Add new analytics config store package to handle caching results
- Make `hasTrendAccess` a ref to ensure changes propagate
- Don't issue a metric card query until we have org config

feat(analytics): get config from analytics endpoint [MA-2532]

---

packages/analytics/dashboard-renderer/package.json
packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
pnpm-lock.yaml

CI wasn't up to date when 3a1ae09827dd5797d4fd5e93fe60935758c1c6bc merged.

fix(analytics): fix dashboard renderer test

---

packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue

- Fix typo
- Add component test for filters in dashboards

fix(dashboards): fix metric card filter [MA-2719]

---

packages/analytics/analytics-utilities/src/types/analytics-config.ts

fix: standardize analytics retention

---

packages/entities/entities-shared/src/components/entity-filter/EntityFilter.cy.ts
packages/entities/entities-shared/src/components/entity-filter/EntityFilter.vue

chore(entities-shared): refactor EntityFilter to not utilize KMenu

---

packages/analytics/analytics-chart/src/composables/useExploreResultToTimeDatasets.ts
packages/analytics/analytics-chart/src/composables/useExploreResultToTimedDatasets.spec.ts

https://konghq.atlassian.net/browse/MA-2724 

fix: dont need to darken color for line chart border anymore

---

packages/analytics/analytics-utilities/src/types/analytics-config.ts

feat(analytics): add types for config V2

---

packages/analytics/dashboard-renderer/sandbox/pages/DynamicDashboardDemo.vue
packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
packages/analytics/dashboard-renderer/src/components/layout/GridLayout.vue
packages/analytics/dashboard-renderer/src/types/grid-layout-types.ts

https://www.loom.com/share/b0580ef23a1e448d9789f85549a3e0af

feat: use css grid instead for grid layout

---

packages/analytics/analytics-config-store/README.md
packages/analytics/analytics-config-store/src/components/AnalyticsConfigCheck.cy.ts
packages/analytics/analytics-config-store/src/components/AnalyticsConfigCheck.vue
packages/analytics/analytics-config-store/src/index.ts

feat(analytics): add `AnalyticsConfigCheck` component [MA-2715]

---

packages/core/documentation/sandbox/App.vue
packages/core/documentation/sandbox/index.ts
packages/core/documentation/sandbox/sample_data.ts
packages/core/documentation/src/components/DocumentationContent.vue
packages/core/documentation/src/components/DocumentationDisplay.vue
packages/core/documentation/src/components/ProductDocumentModal.vue

Fix for [KHCP-10984](https://konghq.atlassian.net/browse/KHCP-10984).
Also adds a sandbox and fixes some TS issues.
[KHCP-10984]: https://konghq.atlassian.net/browse/KHCP-10984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(documentation): mobile view [khcp-10984]

---

packages/core/copy-uuid/src/components/CopyUuid.vue

Warn in console that this package is deprecated.

fix(copy-uuid): deprecated warning

---

packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
packages/analytics/dashboard-renderer/src/components/BarChartRenderer.vue
packages/analytics/dashboard-renderer/src/components/TimeseriesChartRenderer.vue
packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts

https://konghq.atlassian.net/browse/MA-2742

feat(dashboard-renderer): pass through allowCsvExport to charts in dashboard

---

packages/entities/entities-shared/src/composables/useFetcher.ts
packages/entities/entities-shared/src/types/app-config.ts

To add `validateStatus` in host apps:
```ts
const config = {
// other options
// ...
axiosRequestConfig: {
validateStatus: (status: number) => status === 404 || (status >= 200 && status < 300),
}
}
```

feat(entities): add axiosRequestConfig

---

packages/entities/entities-shared/src/composables/useDebouncedFilter.ts

Increase pagesize from `100` -> `1000` for filter inputs with no backend filter support.
Part of [KHCP-11008](https://konghq.atlassian.net/browse/KHCP-11008).
[KHCP-11008]: https://konghq.atlassian.net/browse/KHCP-11008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(entities): default filter size to 1000

---

packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue

fix: remove unnecessary class

---

packages/core/i18n/src/Translation.ts

Fix [datadog alert](https://app.datadoghq.com/rum/error-tracking?fromUser=false&issueId=f43f8dc0-e5ed-11ee-a27c-da7ad0900002&view=spans&from_ts=1710853065663&to_ts=1710856665663&live=true).

fix(i18n): datadog alert

---

packages/analytics/dashboard-renderer/README.md

Update the dashboard-renderer Readme with better examples, more up-to-date documentation.

fix: update dashboard-renderer docs

---

packages/analytics/dashboard-renderer/src/components/TopNTableRenderer.vue

fix(dashboard-tile): needed Entity Link css

---

packages/entities/entities-plugins/src/composables/useSchemas.ts

Fixing the issue where the plugin form is broken for plugins with custom layouts
KM-54

fix(entities-plugins): do not group fields for plugins with custom layouts [KM-54]

---

packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue

fix(dashboard-renderer): golden signals renderer refresh interval

---

packages/analytics/analytics-utilities/src/types/explore-v4.ts

fix: filter values can be null

---

packages/analytics/dashboard-renderer/README.md
packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
packages/analytics/dashboard-renderer/sandbox/sandbox-query-provider.ts
packages/analytics/dashboard-renderer/src/components/layout/GridLayout.vue
packages/analytics/dashboard-renderer/src/components/layout/grid-utils.spec.ts
packages/analytics/dashboard-renderer/src/components/layout/grid-utils.ts
packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts

- Add new `fitToContent` option.
- Only apply option if criteria are met for a given row.
- Add unit test for row def calculation.

feat(dashboard): allow rows to fit content [MA-2744]

---

packages/core/expressions/LICENSE
packages/core/expressions/README.md
packages/core/expressions/docs/expressions-editor.md
packages/core/expressions/package.json
packages/core/expressions/sandbox/App.vue
packages/core/expressions/sandbox/index.html
packages/core/expressions/sandbox/index.ts
packages/core/expressions/sandbox/tsconfig.json
packages/core/expressions/src/components/ExpressionsEditor.vue
packages/core/expressions/src/global-components.d.ts
packages/core/expressions/src/index.ts
packages/core/expressions/src/monaco.ts
packages/core/expressions/src/schema.ts
packages/core/expressions/tsconfig.build.json
packages/core/expressions/tsconfig.json
packages/core/expressions/vite.config.ts
pnpm-lock.yaml

This pull request aims to add shared components to support [Kong's Expressions language](https://docs.konghq.com/gateway/latest/reference/expressions-language/).
This package mainly provides `ExpressionsEditor.vue`–A `monaco-editor` based component that supports syntax highlighting and autocomplete for the Expressions language.
KM-19

feat(expressions): expressions language support and editor [KM-19]

---

package.json
packages/analytics/analytics-chart/package.json
packages/analytics/analytics-metric-provider/package.json
packages/analytics/dashboard-renderer/package.json
packages/analytics/metric-cards/package.json
packages/core/app-layout/package.json
packages/core/documentation/package.json
packages/core/expressions/package.json
packages/core/forms/package.json
packages/core/misc-widgets/package.json
packages/core/sandbox-layout/package.json
packages/entities/entities-certificates/package.json
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumers/package.json
packages/entities/entities-consumers/src/components/ConsumerForm.vue
packages/entities/entities-gateway-services/package.json
packages/entities/entities-key-sets/package.json
packages/entities/entities-keys/package.json
packages/entities/entities-plugins/package.json
packages/entities/entities-routes/package.json
packages/entities/entities-shared/package.json
packages/entities/entities-snis/package.json
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-vaults/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

Changes:
* bump kongponents version
* wrap consumer identification fields in `fieldset` element and associate heading element to it using `aria-labelledby` attribute (screenshot)

fix(entities-consumers): group form fields [KHCP-11029]

---

packages/analytics/analytics-config-store/CHANGELOG.md
packages/analytics/analytics-metric-provider/CHANGELOG.md
packages/analytics/analytics-metric-provider/README.md
packages/analytics/analytics-metric-provider/sandbox/App.vue
packages/analytics/analytics-metric-provider/src/components/MetricsProvider.vue
packages/analytics/analytics-metric-provider/src/components/MetricsTestHarness.vue
packages/analytics/analytics-metric-provider/src/constants.ts
packages/analytics/analytics-metric-provider/src/index.ts
packages/analytics/analytics-utilities/CHANGELOG.md
packages/analytics/dashboard-renderer/CHANGELOG.md
packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue

https://konghq.atlassian.net/browse/MA-2705
rename MetricsProviderInternal to MetricsProvider
BREAKING CHANGE: component rename

refactor(analytics-metric-provider): rename MetricsProvider component

---

packages/analytics/analytics-utilities/src/types/explore-v4.ts

Add in `active_services` into the aggregation/metrics enum list

feat(active-services): Active services metric

---

packages/entities/entities-plugins/src/composables/usePluginMeta.ts

Adding missing `name` prop for credential metadata.

fix(entities-plugins): add missing name for credentials

---

packages/entities/entities-shared/src/components/entity-link/EntityLink.vue

Ticket: https://konghq.atlassian.net/browse/KHCP-11425
Fix cannot read properties of undefined (reading 'toString')

fix(entity-link): add optional chaining [KHCP-11425]

---

packages/core/forms/src/generator/fields/advanced/FieldArrayMultiItem.vue

Convert to setup syntax and use design tokens.
Address [KHCP-11348](https://konghq.atlassian.net/browse/KHCP-11348).
[KHCP-11348]: https://konghq.atlassian.net/browse/KHCP-11348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(vfg): field-array-multi-item refactor [khcp-11348]

---

packages/core/forms/src/generator/fields/advanced/FieldArrayItem.vue

Convert to setup syntax and use design tokens.
Address [KHCP-11347](https://konghq.atlassian.net/browse/KHCP-11347).
[KHCP-11347]: https://konghq.atlassian.net/browse/KHCP-11347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(vfg): field-array-item refactor [khcp-11347]

---

packages/core/forms/src/generator/fields/advanced/FieldArrayCardContainer.vue

Convert to setup syntax and use design tokens.
Address [KHCP-11346](https://konghq.atlassian.net/browse/KHCP-11346).
[KHCP-11346]: https://konghq.atlassian.net/browse/KHCP-11346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(vfg): field-array-card-container refactor [khcp-11346]

---

packages/analytics/analytics-utilities/src/types/chart-types.ts

fix: export new chart types

---

packages/entities/entities-shared/src/components/common/YamlCodeBlock.vue

https://konghq.atlassian.net/browse/KHCP-11409
Consumed in https://github.com/Kong/konnect-ui-apps/pull/3012

fix(yamlCodeBlock): disabled fields missing from yaml configs [KHCP-11409]

---

.github/workflows/ci.yaml

Check if the `GH_TOKEN` env variable is set since we can't check for `secrets` in an `if` block.

ci: check secret value

---

packages/core/forms/src/composables/useAbstractFields.ts

fix(*): keep model reactive and remove watcher

---

packages/core/forms/sandbox/FieldTester.vue
packages/core/forms/src/composables/useAbstractFields.ts
packages/core/forms/src/generator/fields/core/FieldInput.vue
packages/core/forms/src/generator/fields/core/FieldLabel.vue

Watch for programmatic changes to model.

fix(vfg): input model reactivity

---

packages/entities/entities-plugins/src/components/PluginForm.vue

**Ticket:**
https://konghq.atlassian.net/browse/KHCP-11775
**Changes:**
- Updates the RSA public key input field on the consumer JWT credential form to be a textarea instead of a regular text input field
**Screenshots:**
**Old form**
**New form**

fix(entities-plugins): fix consumer jwt rsa pub key input field [KHCP-11775]

---

packages/core/forms/src/generator/FormGroup.vue
packages/core/forms/src/generator/fields/advanced/FieldAutoSuggest.vue

This PR fixes `FieldAutoSuggest` due to [this change](https://github.com/Kong/kongponents/pull/2156). Also fixes form label style:

fix(forms): autosuggest

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

Bumps swagger-ui to [5.7.2](https://github.com/swagger-api/swagger-ui/releases/tag/v5.7.2) for multiple callbacks bug fix

feat(deps): bump swagger-ui to 5.7.2

---

packages/entities/entities-vaults/src/components/VaultForm.vue
packages/entities/entities-vaults/src/locales/en.json
packages/entities/entities-vaults/src/types/vault-form.ts

Adding missing AWS Vault fields: `endpoint_url`, `assume_role_arn`, and `role_session_name`.
KM-132

feat(entities-vaults): add aws vault fields

---

packages/entities/entities-certificates/package.json
packages/entities/entities-certificates/src/components/CACertificateList.vue
packages/entities/entities-certificates/src/components/CertificateList.vue
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
packages/entities/entities-consumers/package.json
packages/entities/entities-consumers/src/components/ConsumerList.vue
packages/entities/entities-gateway-services/package.json
packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-key-sets/package.json
packages/entities/entities-key-sets/src/components/KeySetList.vue
packages/entities/entities-keys/package.json
packages/entities/entities-keys/src/components/KeyList.vue
packages/entities/entities-plugins/src/components/PluginList.vue
packages/entities/entities-routes/src/components/RouteList.vue
packages/entities/entities-snis/package.json
packages/entities/entities-snis/src/components/SniList.vue
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-upstreams-targets/src/components/TargetsList.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
packages/entities/entities-vaults/package.json
packages/entities/entities-vaults/src/components/VaultList.vue
pnpm-lock.yaml

This PR removes the following warning:

fix(entities): icon prop warning of kbutton

---

packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTableCell.vue

fix(entities-shared): table cell display

---

packages/core/forms/src/generator/fields/advanced/FieldArray.vue
packages/entities/entities-plugins/package.json
packages/entities/entities-plugins/src/components/PluginForm.vue
pnpm-lock.yaml

This PR fixes KAG-4328 the right way. Reference: https://github.com/Kong/public-ui-components/pull/1375

fix(forms): remove array item reactivity

---

package.json
packages/analytics/analytics-chart/package.json
packages/analytics/analytics-metric-provider/package.json
packages/analytics/dashboard-renderer/package.json
packages/analytics/metric-cards/package.json
packages/core/app-layout/package.json
packages/core/documentation/package.json
packages/core/expressions/package.json
packages/core/forms/package.json
packages/core/misc-widgets/package.json
packages/core/sandbox-layout/package.json
packages/entities/entities-certificates/package.json
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumer-groups/src/components/AddToGroupModal.cy.ts
packages/entities/entities-consumers/package.json
packages/entities/entities-consumers/src/components/AddConsumerModal.cy.ts
packages/entities/entities-data-plane-nodes/package.json
packages/entities/entities-gateway-services/package.json
packages/entities/entities-key-sets/package.json
packages/entities/entities-keys/package.json
packages/entities/entities-plugins/package.json
packages/entities/entities-routes/package.json
packages/entities/entities-shared/package.json
packages/entities/entities-snis/package.json
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-vaults/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

Jira: https://konghq.atlassian.net/browse/KHCP-11882
Phase 13 adoption of components reskinned in alpha version of Kongponents v9 release. Includes these components:
- `KPop`

fix(*): kongponents alpha phase 13 [KHCP-11882]

---

packages/analytics/analytics-utilities/src/granularity.ts
packages/analytics/analytics-utilities/src/types/explore-v4.ts

feat: Include secondly granularity

---

packages/analytics/analytics-chart/package.json
packages/analytics/analytics-metric-provider/package.json
packages/analytics/dashboard-renderer/package.json
packages/analytics/metric-cards/package.json
packages/core/app-layout/package.json
packages/core/documentation/package.json
packages/core/expressions/package.json
packages/core/forms/package.json
packages/core/misc-widgets/package.json
packages/core/sandbox-layout/package.json
packages/entities/entities-certificates/package.json
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumers/package.json
packages/entities/entities-data-plane-nodes/package.json
packages/entities/entities-gateway-services/package.json
packages/entities/entities-key-sets/package.json
packages/entities/entities-keys/package.json
packages/entities/entities-plugins/package.json
packages/entities/entities-routes/package.json
packages/entities/entities-shared/package.json
packages/entities/entities-snis/package.json
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-vaults/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json

chore(*): bump kongponents peer dependencies

---

packages/analytics/analytics-utilities/src/types/analytics-config.ts

feat: allow 425 days of retention

---

packages/core/app-layout/sandbox/pages/PageHeaderPage.vue
packages/core/forms/src/generator/fields/advanced/FieldObjectAdvanced.vue
packages/entities/entities-routes/src/components/RouteFormMethodsFields.vue
packages/entities/entities-routes/src/components/RoutingRulesEntitiesControls.vue
packages/entities/entities-shared/sandbox/pages/EntityFormSectionPage.vue
packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsFormActiveHealthCheck.vue
packages/entities/entities-vaults/src/components/VaultForm.vue
packages/portal/spec-renderer/src/components/operations-list/OperationsListSectionHeader.vue

Replace usage of KIcon with icons from https://github.com/Kong/icons

fix(*): replace kicon instances [KHCP-11982]

---

CODEOWNERS
packages/analytics/analytics-config-store/README.md
packages/analytics/portal-analytics-bridge/LICENSE
packages/analytics/portal-analytics-bridge/README.md
packages/analytics/portal-analytics-bridge/package.json
packages/analytics/portal-analytics-bridge/src/index.ts
packages/analytics/portal-analytics-bridge/src/portal-analytics-bridge.ts
packages/analytics/portal-analytics-bridge/src/types/index.ts
packages/analytics/portal-analytics-bridge/src/types/provider-options.ts
packages/analytics/portal-analytics-bridge/tsconfig.build.json
packages/analytics/portal-analytics-bridge/tsconfig.json
packages/analytics/portal-analytics-bridge/vite.config.ts
pnpm-lock.yaml

- Add new package to implement analytics bridge in portal.
- Update config store docs and remove unnecessary peer dependency.

feat(analytics): analytics bridge for Portal [MA-2737]

---

packages/entities/entities-plugins/src/index.ts

https://konghq.atlassian.net/browse/KHCP-11766

feat(plugins): expose PluginSelectCard for reuse in serverless quickstart [KHCP-11766]

---

packages/entities/entities-plugins/docs/plugin-form.md
packages/entities/entities-plugins/src/components/PluginForm.vue

Updates to support display in a fullscreen modal instead of a full page form.
Part of [KHCP-11822](https://konghq.atlassian.net/browse/KHCP-11822).
Adoption PR: https://github.com/Kong/konnect-ui-apps/pull/3269
[KHCP-11822]: https://konghq.atlassian.net/browse/KHCP-11822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(serverless): hybrid flow modals [khcp-11822]

---

packages/core/app-layout/sandbox/pages/PageHeaderPage.vue
packages/core/forms/src/generator/fields/advanced/FieldObjectAdvanced.vue
packages/entities/entities-plugins/src/components/select/PluginSelectCard.vue
packages/entities/entities-routes/src/components/RouteFormMethodsFields.vue
packages/entities/entities-routes/src/components/RoutingRulesEntitiesControls.vue
packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsFormActiveHealthCheck.vue

This PR removes the `icon` slot and adds the `icon` prop for `KButton`.

refactor(*): kbutton icon

---

packages/entities/entities-certificates/src/components/CACertificateList.vue
packages/entities/entities-certificates/src/components/CertificateList.vue
packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue
packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
packages/entities/entities-consumers/src/components/ConsumerList.vue
packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-key-sets/src/components/KeySetList.vue
packages/entities/entities-keys/src/components/KeyList.vue
packages/entities/entities-plugins/src/components/PluginList.vue
packages/entities/entities-routes/src/components/RouteList.vue
packages/entities/entities-snis/src/components/SniList.vue
packages/entities/entities-upstreams-targets/src/components/TargetsList.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
packages/entities/entities-vaults/src/components/VaultList.vue

This PR reverts #1001.
KHCP-11277

fix(entities): dynamic teleport

---

packages/core/documentation/src/components/DocumentationContent.vue
packages/core/documentation/src/components/DocumentationDisplay.vue
packages/core/documentation/src/components/ProductDocumentModal.vue

Addresses:
[https://konghq.atlassian.net/browse/KHCP-11781](https://konghq.atlassian.net/browse/KHCP-11781)

feat(documentation): new doc create

---

package.json
packages/analytics/analytics-chart/package.json
packages/analytics/analytics-metric-provider/package.json
packages/analytics/dashboard-renderer/package.json
packages/analytics/metric-cards/package.json
packages/core/app-layout/package.json
packages/core/documentation/package.json
packages/core/expressions/package.json
packages/core/forms/package.json
packages/core/misc-widgets/package.json
packages/core/sandbox-layout/package.json
packages/entities/entities-certificates/package.json
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumers/package.json
packages/entities/entities-data-plane-nodes/package.json
packages/entities/entities-gateway-services/package.json
packages/entities/entities-key-sets/package.json
packages/entities/entities-keys/package.json
packages/entities/entities-plugins/package.json
packages/entities/entities-routes/package.json
packages/entities/entities-shared/package.json
packages/entities/entities-snis/package.json
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-vaults/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

chore(deps): bump @kong/kongponents to alpha.162

---

packages/core/forms/src/forms/RLAForm.vue
packages/core/forms/src/locales/en.json
packages/entities/entities-plugins/docs/plugin-form.md
packages/entities/entities-plugins/src/components/PluginEntityForm.vue
packages/entities/entities-plugins/src/components/PluginForm.vue
packages/entities/entities-shared/docs/entity-base-form.md
packages/entities/entities-shared/src/components/entity-base-form/EntityBaseForm.vue

Addressing feedback on the RLA form:
1. Marked all fields above Advanced Fields required
2. Hid View Configuration in the model action
3. Moved the content outside the card wrapper
4. Updated use case labels and texts
5. Updated misc texts and title letter case
KM-202

fix(*): apply suggestions on RLA form [KM-202]

---

packages/entities/entities-gateway-services/src/components/GatewayServiceForm.vue

Expose the `initForm` function to allow the consuming app to pre-populate form data

feat(gateway-service-form): expose initForm

---

packages/core/documentation/package.json
pnpm-lock.yaml

https://konghq.atlassian.net/browse/KHCP-12213

chore(documentation): bump markdown version [KHCP-12213]

---

package.json
packages/analytics/analytics-chart/package.json
packages/analytics/analytics-metric-provider/package.json
packages/analytics/dashboard-renderer/package.json
packages/analytics/metric-cards/package.json
packages/core/app-layout/package.json
packages/core/documentation/package.json
packages/core/expressions/package.json
packages/core/forms/package.json
packages/core/misc-widgets/package.json
packages/core/sandbox-layout/package.json
packages/entities/entities-certificates/package.json
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumers/package.json
packages/entities/entities-data-plane-nodes/package.json
packages/entities/entities-gateway-services/package.json
packages/entities/entities-key-sets/package.json
packages/entities/entities-keys/package.json
packages/entities/entities-plugins/package.json
packages/entities/entities-routes/package.json
packages/entities/entities-shared/package.json
packages/entities/entities-snis/package.json
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-vaults/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

Jira: https://konghq.atlassian.net/browse/KHCP-12342
Pre-release Kongponents v9 adoption

fix(*): pre-release @kong/kongponents adoption

---

docs/creating-a-package.md
package.json
packages/analytics/analytics-chart/package.json
packages/analytics/analytics-metric-provider/package.json
packages/analytics/dashboard-renderer/package.json
packages/analytics/metric-cards/package.json
packages/core/app-layout/package.json
packages/core/documentation/package.json
packages/core/expressions/package.json
packages/core/forms/package.json
packages/core/misc-widgets/package.json
packages/core/sandbox-layout/package.json
packages/entities/entities-certificates/package.json
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumers/package.json
packages/entities/entities-data-plane-nodes/package.json
packages/entities/entities-gateway-services/package.json
packages/entities/entities-key-sets/package.json
packages/entities/entities-keys/package.json
packages/entities/entities-plugins/package.json
packages/entities/entities-routes/package.json
packages/entities/entities-shared/package.json
packages/entities/entities-snis/package.json
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-vaults/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

fix(deps): bump @kong/kongponents to v9

---

packages/analytics/analytics-chart/src/components/AnalyticsChart.cy.ts
packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
packages/analytics/analytics-chart/src/components/chart-plugins/ChartTooltip.vue

https://konghq.atlassian.net/browse/MA-3016

feat(analytics-chart): square marker for legend and tooltip [MA-3016]

---

packages/entities/entities-plugins/src/components/PluginList.vue

Adding a timeout of 120s to plugin update requests. KM-267

fix(entities-plugins): add timeout to plugin update calls

---

packages/core/documentation/src/components/ProductDocumentModal.vue
packages/core/documentation/src/external-links.ts

Addresses:
[https://konghq.atlassian.net/browse/TDX-4292](https://konghq.atlassian.net/browse/TDX-4292)

fix(product-doc-modal): add asterisk to upload file field [tdx-4292]

---

package.json
packages/analytics/analytics-utilities/src/types/explore-v4.ts

fix: add iso_code to queryable dimensions

---

.vscode/settings.json

chore(vscode/settings): newline

---

packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
packages/entities/entities-consumers/src/components/ConsumerList.vue
packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-key-sets/src/components/KeySetList.vue
packages/entities/entities-keys/src/components/KeyList.vue
packages/entities/entities-plugins/src/components/PluginList.vue
packages/entities/entities-routes/src/components/RouteList.vue
packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue
packages/entities/entities-shared/src/types/base.ts
packages/entities/entities-shared/src/types/entity-base-table.ts
packages/entities/entities-snis/src/components/SniList.vue
packages/entities/entities-upstreams-targets/src/components/TargetsList.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
packages/entities/entities-vaults/src/components/VaultList.vue

Always display one of the columns in entity lists.
KM-289

feat(entities): preserve one column in entity lists

---

packages/entities/entities-certificates/src/components/CACertificateList.vue
packages/entities/entities-certificates/src/components/CertificateList.vue

feat(entities-certificates): preserve one column in lists

---

packages/entities/entities-plugins/src/components/PluginForm.vue
packages/entities/entities-shared/src/components/common/JsonCodeBlock.vue

| - | - |
| <img width="493" alt="image" src="https://github.com/Kong/public-ui-components/assets/10095631/a623ddec-5025-408b-b841-7b6b127c5f93"> | <img width="502" alt="image" src="https://github.com/Kong/public-ui-components/assets/10095631/300e0da1-826f-48ea-bae4-5669c246fa15"> |
KM-194

fix(entities-plugins): `config` section display in plugin forms

---

packages/entities/entities-plugins/docs/plugin-form.md
packages/entities/entities-plugins/src/components/PluginEntityForm.vue
packages/entities/entities-plugins/src/definitions/metadata.ts
packages/entities/entities-plugins/src/types/plugin-form.ts

Adding a new prop to accommodate https://github.com/Kong/kong-ee/pull/9399.
KM-305

feat(entities-plugins): add isNewOtelSchema prop

---

packages/analytics/analytics-geo-map/src/components/AnalyticsGeoMap.vue

fix: disable map rotation by default

---

packages/analytics/analytics-utilities/src/types/analytics-data.ts
packages/analytics/analytics-utilities/src/types/explore-v4.ts
packages/analytics/analytics-utilities/src/types/query-bridge.ts

- Implement necessary types to build out the new experience

feat(analytics): ai explore types

---

packages/entities/entities-plugins/src/definitions/metadata.ts
packages/entities/entities-plugins/src/types/plugin.ts

Move AI plugins into their own `AI` category on Plugin Select.
Adoption PR: https://github.com/Kong/konnect-ui-apps/pull/3680

feat(plugins): add ai category

---

packages/analytics/analytics-geo-map/README.md
packages/analytics/analytics-geo-map/sandbox/App.vue
packages/analytics/analytics-geo-map/src/components/AnalyticsGeoMap.vue

fix: some minor tweaks

---

packages/analytics/analytics-utilities/src/types/explore-v4.ts

Add `short_name` as part of explore query. I don't think it's necessary to add to the response as well (similar to `descending`). 

fix: add short_name to explore query

---

packages/entities/entities-certificates/src/components/CACertificateList.vue
packages/entities/entities-certificates/src/components/CertificateList.vue
packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue
packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
packages/entities/entities-consumers/src/components/ConsumerList.vue
packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-key-sets/src/components/KeySetList.vue
packages/entities/entities-keys/src/components/KeyList.vue
packages/entities/entities-plugins/src/components/PluginList.vue
packages/entities/entities-routes/src/components/RouteList.vue
packages/entities/entities-snis/src/components/SniList.vue
packages/entities/entities-upstreams-targets/src/components/TargetsList.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
packages/entities/entities-vaults/src/components/SecretList.vue
packages/entities/entities-vaults/src/components/VaultList.vue

Hide the create button initially and only show it when the table has data.
KM-342

fix(entities): create button visibility

---

packages/analytics/analytics-chart/src/locales/en.json

fix: add translations for new ai metrics

---

packages/analytics/analytics-utilities/src/types/explore-v4.ts

fix: route added twice in ai dimensions

---

packages/entities/entities-vaults/docs/vault-form.md
packages/entities/entities-vaults/sandbox/pages/VaultFormPage.vue
packages/entities/entities-vaults/src/components/VaultForm.cy.ts
packages/entities/entities-vaults/src/components/VaultForm.vue
packages/entities/entities-vaults/src/locales/en.json
packages/entities/entities-vaults/src/types/vault-form.ts

Adding STS endpoint url field in AWS vault form
KM-297
https://konghq.atlassian.net/browse/KM-297

feat(vault-form): add STS endpoint url in AWS vault form [KM-297]

---

packages/analytics/analytics-chart/src/composables/useChartLegendValues.ts
packages/analytics/analytics-chart/src/composables/useTranslatedUnits.ts
packages/analytics/analytics-chart/src/locales/en.json
packages/analytics/analytics-chart/src/utils/commonOptions.ts

https://konghq.atlassian.net/browse/MA-3103

fix: support new metrics dimensions and units for ai analytics

---

packages/entities/entities-shared/sandbox/index.html
packages/entities/entities-shared/src/components/common/JsonCodeBlock.vue

... to match the latest `<KCodeBlock />` change in kong/kongponents#2302
Minimum Kongponents version: 9.0.20
JIRA: KM-347

fix(entities-shared): update json code block style

---

packages/entities/entities-upstreams-targets/src/components/UpstreamsForm.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsFormActiveHealthCheck.cy.ts
packages/entities/entities-upstreams-targets/src/components/UpstreamsFormActiveHealthCheck.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsFormPassiveHealthCheck.cy.ts
packages/entities/entities-upstreams-targets/src/components/UpstreamsFormPassiveHealthCheck.vue

fix(entities-upstreams-targets): expose tcp_failures [FTI-6057]

---

package.json
packages/analytics/analytics-chart/src/components/TopNTable.vue
packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
packages/analytics/analytics-chart/src/components/chart-plugins/ChartTooltip.vue
packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
packages/core/app-layout/src/styles/variables/_app-sidebar.scss
packages/entities/entities-routes/src/styles/_mixins.scss
pnpm-lock.yaml

Addresses: https://konghq.atlassian.net/browse/KHCP-12715

fix(*): sass mixed decls deprecation [KHCP-12715]

---

packages/analytics/analytics-utilities/src/types/explore-v4.ts

adding new for ai analytics metrics and dimensions

feat(ai-analytics): AI Analytics new metrics/dimensions

---

packages/entities/entities-certificates/src/components/CertificateForm.vue

The request body should include the `snis` key only when the `snis` field is present.

fix(entities-certificates): remove snis if field not displayed

---

packages/core/forms/src/components/fields/FieldObject.vue
packages/entities/entities-plugins/src/components/PluginFieldRuleAlerts.vue
packages/entities/entities-plugins/src/components/PluginForm.vue
packages/entities/entities-plugins/src/definitions/schemas/StatsDAdvanced.ts
packages/entities/entities-plugins/src/types/plugins/stats-d-advanced.d.ts

| - | - |
| <img width="526" alt="image" src="https://github.com/user-attachments/assets/345c1ddc-fda8-429a-bd86-983f3ec01ad4"> | <img width="567" alt="image" src="https://github.com/user-attachments/assets/461eb7c4-10e5-4360-bc1d-1896e25e3b28"> |

fix(entities-plugins): nested array object labels

---

packages/entities/entities-plugins/src/components/PluginIcon.vue

fix(entities-plugins): wrong plugin icon [KM-354]

---

packages/entities/entities-plugins/src/definitions/metadata.ts
packages/entities/entities-plugins/src/locales/en.json

The backend has renamed `ai-semantic-caching` plugin to `ai-semantic-cache`.

fix(plugins): ai-semantic-caching rename

---

packages/core/app-layout/src/components/sidebar/SidebarItem.vue

Add `aria-current` to sidebar links

fix(app-layout): add aria-current to sidebar links [KHCP-12832]

---

packages/entities/entities-plugins/src/components/PluginForm.cy.ts
packages/entities/entities-plugins/src/definitions/metadata.ts

Reference: https://github.com/Kong/kong/pull/13209
KM-364

feat(entities-plugins): add plugin scopes

---

packages/core/forms/src/components/fields/FieldArray.vue
packages/entities/entities-plugins/src/components/PluginEntityForm.vue
packages/entities/entities-plugins/src/components/PluginForm.vue
packages/entities/entities-plugins/src/composables/useSchemas.ts
packages/entities/entities-plugins/src/definitions/metadata.ts
packages/entities/entities-plugins/src/definitions/schemas/ArrayInputFieldSchema.ts
packages/entities/entities-plugins/src/definitions/schemas/UpstreamOauth.ts
packages/entities/entities-plugins/src/locales/en.json
packages/entities/entities-plugins/src/types/plugin-form.ts
packages/entities/entities-plugins/src/types/plugins/upstream-oauth.d.ts

Adding support for the `upstream-oauth` plugin. Also fixes a bug(?) that array fields with number elements (e.g. `behavior. purge_token_on_upstream_status_codes`) are rendered as an text input.
KM-327

feat(entities-plugins): support upstream-oauth

---

packages/core/forms/sandbox/App.vue
packages/core/forms/src/components/FormGenerator.vue
packages/core/forms/src/components/fields/FieldSwitch.vue
packages/core/forms/src/components/fields/__tests__/FieldSwitch.cy.ts
packages/core/forms/src/composables/useAbstractFields.ts
packages/core/forms/src/locales/en.json
packages/entities/entities-plugins/src/components/PluginEntityForm.vue

Address [KHCP-11326](https://konghq.atlassian.net/browse/KHCP-11326).
Adoption PR (with passing plugins E2Es): https://github.com/Kong/konnect-ui-apps/pull/3911
[KHCP-11326]: https://konghq.atlassian.net/browse/KHCP-11326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(vfg): field-switch to kongponents [khcp-11326]

---

package.json
packages/analytics/analytics-chart/package.json
packages/analytics/analytics-geo-map/package.json
packages/analytics/analytics-metric-provider/package.json
packages/analytics/analytics-utilities/package.json
packages/analytics/dashboard-renderer/package.json
packages/analytics/metric-cards/package.json
packages/core/app-layout/package.json
packages/core/core/package.json
packages/core/documentation/package.json
packages/core/error-boundary/package.json
packages/core/expressions/package.json
packages/core/forms/package.json
packages/core/sandbox-layout/package.json
packages/entities/entities-certificates/package.json
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumers/package.json
packages/entities/entities-data-plane-nodes/package.json
packages/entities/entities-gateway-services/package.json
packages/entities/entities-keys/package.json
packages/entities/entities-plugins/package.json
packages/entities/entities-routes/package.json
packages/entities/entities-shared/package.json
packages/entities/entities-snis/package.json
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-vaults/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

chore(deps): bump @kong/design-tokens

---

packages/entities/entities-shared/src/composables/useDebouncedFilter.ts

This pull request simplifies the logic flow in `useDebouncedFilter`
KM-393

refactor(entities-shared): simplify logic in useDebouncedFilter

---

packages/core/forms/src/components/fields/FieldArrayItem.vue

| - | - |
| <img width="846" alt="image" src="https://github.com/user-attachments/assets/9f5e0103-17d1-43b6-bbc0-105c45b2caa8"> | <img width="846" alt="image" src="https://github.com/user-attachments/assets/42789cf7-7672-4b8f-bba5-3cd91e55ef70"> |

fix(forms): array item field width

---

packages/core/app-layout/src/components/sidebar/SidebarItem.vue

fix(app-layout): sidebar item aria current

---

packages/entities/entities-plugins/src/locales/en.json

This pull request updates the i18n string for the CTA of the vault secret picker.
KM-417

fix(entities-plugins): i18n string for vault secret picker CTA

---

packages/analytics/analytics-utilities/src/types/explore/requests.ts

fix: type for api-request time_ranges

---

packages/analytics/analytics-utilities/src/types/explore/requests.ts

fix: api-request datasource fixes

---

packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-gateway-services/src/locales/en.json

Correct service delete description
KM-425

fix: service delete description correction [KM-425]

---

packages/entities/entities-plugins/src/components/PluginForm.vue
packages/entities/entities-shared/src/components/common/TerraformCodeBlock.vue
packages/entities/entities-shared/src/components/entity-base-form/EntityBaseForm.vue
packages/entities/entities-shared/src/types/entity-base-config-card.ts
packages/entities/entities-vaults/src/components/SecretForm.vue

Misc fixes for terrafor, part of [KHCP-12445](https://konghq.atlassian.net/browse/KHCP-12445).
Fixes:
- `tags = []` not appearing on it's own line
- correctly handle terraform on consumer credential form
- add `other` type for unsupported terraform entities (Vault secrets) - terraform tab should NOT be displayed
- fix handling for key -> key_set relationship (use `set` instead)
Adoption PR: https://github.com/Kong/konnect-ui-apps/pull/3993
[KHCP-12445]: https://konghq.atlassian.net/browse/KHCP-12445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(terraform): misc cleanup [khcp-12445]

---

packages/analytics/analytics-utilities/src/types/explore/requests.ts

fix: metric filter values

---

packages/portal/spec-renderer/src/components/SpecOperationsList.vue

Fixes https://konghq.atlassian.net/browse/KHCP-12420

fix(spec-renderer): fix TypeError xe.tag.toLowerCase is not a function [KHCP-12420]

---

packages/entities/entities-certificates/src/components/CACertificateForm.cy.ts
packages/entities/entities-certificates/src/components/CertificateForm.cy.ts
packages/entities/entities-consumer-groups/src/components/ConsumerGroupForm.cy.ts
packages/entities/entities-consumers/src/components/ConsumerForm.cy.ts
packages/entities/entities-gateway-services/src/components/GatewayServiceForm.cy.ts
packages/entities/entities-key-sets/src/components/KeySetForm.cy.ts
packages/entities/entities-keys/src/components/KeyForm.cy.ts
packages/entities/entities-plugins/src/components/PluginForm.cy.ts
packages/entities/entities-plugins/src/components/PluginForm.vue
packages/entities/entities-routes/src/components/RouteForm.cy.ts
packages/entities/entities-shared/src/components/entity-base-form/EntityBaseForm.cy.ts
packages/entities/entities-shared/src/components/entity-base-form/EntityBaseForm.vue
packages/entities/entities-snis/src/components/SniForm.cy.ts
packages/entities/entities-upstreams-targets/src/components/UpstreamsForm.cy.ts
packages/entities/entities-vaults/src/components/SecretForm.cy.ts
packages/entities/entities-vaults/src/components/VaultForm.cy.ts

Update entity form action data-testid's to include form state (`create`/`edit`).
Part of [KHCP-13000](https://konghq.atlassian.net/browse/KHCP-13000).
[KHCP-13000]: https://konghq.atlassian.net/browse/KHCP-13000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(entities): form state data-testids [khcp-13000]

---

packages/entities/entities-snis/src/components/SniList.cy.ts

Expand test coverage to test `fetcher` params after deleting an item.

test(entities-snis): refetch after deletion

---

packages/analytics/analytics-utilities/src/types/explore/ai.ts
packages/analytics/analytics-utilities/src/types/explore/requests.ts

Addings new metrics for ai explore and columns for api-requests

feat(ai): ai related new metrics, columns

---

packages/entities/entities-consumer-groups/src/components/AddToGroupModal.vue
packages/entities/entities-consumer-groups/src/consumer-groups-endpoints.ts

`?counter=true` breaks URLs for requests in `AddToGroupModal`.
FTI-6205

fix(entities-consumer-groups): url for AddToGroupModal

---

packages/entities/entities-plugins/src/locales/en.json

Adjust disabled tooltip text for custom plugins.
Part of [KHCP-13166](https://konghq.atlassian.net/browse/KHCP-13166).
[KHCP-13166]: https://konghq.atlassian.net/browse/KHCP-13166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(plugins): custom plugins disabled text [khcp-13166]

---

packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
packages/analytics/analytics-chart/src/components/SimpleChart.vue
packages/analytics/analytics-chart/src/components/chart-plugins/ChartTooltip.vue
packages/analytics/analytics-chart/src/components/chart-types/GaugeChart.vue
packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
packages/analytics/analytics-chart/src/styles/base.scss
packages/analytics/analytics-chart/src/styles/chart-shell.scss
packages/analytics/analytics-chart/src/styles/colors.scss
packages/analytics/analytics-chart/src/styles/mixins.scss
packages/analytics/analytics-metric-provider/src/components/MetricCardContainer.vue

https://konghq.atlassian.net/browse/MA-2961

feat: analytics chart tokens [MA-2961]

---

packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
packages/analytics/analytics-chart/src/locales/en.json

https://konghq.atlassian.net/browse/MA-3195

fix: multiple metrics axis title

---

packages/analytics/analytics-chart/src/locales/en.json

fix: typo in metric axis title

---

packages/portal/spec-renderer/src/components/operations-list/OperationsListItem.vue
packages/portal/swagger-ui-web-component/src/styles/overrides.css

Fix spec renderer style issues for [KHCP-13104](https://konghq.atlassian.net/browse/KHCP-13104).
Before:
After:
[KHCP-13104]: https://konghq.atlassian.net/browse/KHCP-13104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(spec-renderer): style issues [khcp-13104]

---

packages/analytics/analytics-utilities/src/types/explore/common.ts
packages/analytics/analytics-utilities/src/types/explore/requests.ts

Update to cover new metrics and there operators from here: https://docs.google.com/spreadsheets/d/1XQW4sXPlR7_7kUKxhKGTNueeQUZF3Pr4FJnbRz00axE/edit?gid=5969125#gid=5969125

feat: update to new filter schema

---

packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
packages/analytics/analytics-chart/src/composables/useChartSelectedRange.ts
packages/analytics/analytics-chart/src/utils/constants.ts
packages/analytics/analytics-utilities/src/format.ts

Fix for this warning re: date-fns year format:
https://kongstrong.slack.com/archives/C01RF6STU2F/p1725915764341119

feat(analytics-utilities): date-fns warning fix

---

packages/analytics/analytics-utilities/src/types/explore/requests.ts

fix: upstream_status_code_grouped

---

packages/analytics/analytics-utilities/src/types/explore/requests.ts

fix: empty filter

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

chore(react): v18.2.0

---

packages/analytics/analytics-chart/src/locales/en.json

https://konghq.atlassian.net/browse/MA-3188
Deploy previews in consuming app:
https://github.com/Kong/konnect-ui-apps/pull/4177

fix(analytics-chart): lang keys for chart csv export [MA-3188]

---

package.json
packages/analytics/analytics-chart/package.json
packages/analytics/analytics-config-store/package.json
packages/analytics/analytics-geo-map/package.json
packages/analytics/dashboard-renderer/package.json
packages/analytics/metric-cards/package.json
packages/analytics/portal-analytics-bridge/package.json
packages/core/app-layout/package.json
packages/core/documentation/package.json
packages/core/error-boundary/package.json
packages/core/expressions/package.json
packages/core/misc-widgets/package.json
packages/core/sandbox-layout/package.json
packages/entities/entities-certificates/package.json
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumers/package.json
packages/entities/entities-data-plane-nodes/package.json
packages/entities/entities-gateway-services/package.json
packages/entities/entities-key-sets/package.json
packages/entities/entities-keys/package.json
packages/entities/entities-plugins/package.json
packages/entities/entities-routes/package.json
packages/entities/entities-shared/package.json
packages/entities/entities-snis/package.json
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-vaults/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

Updating
- types/node
- lerna
- vite
- vite-plugin-top-level-await
- vue

chore(*): push renovate along

---

packages/entities/entities-vaults/src/vaults-endpoints.ts

When deleting a config store, make sure its secrets are also deleted.

feat(entities-vaults): force delete secrets

---

packages/entities/entities-routes/src/locales/en.json

fix(entitites-routes): tooltip typo

---

packages/analytics/analytics-utilities/src/types/explore/requests.ts

fix: update to use operator in new style filters

---

packages/entities/entities-routes/src/components/RouteForm.vue

fix(entities-routes): fix unexpected indent for service select

---

packages/analytics/analytics-utilities/src/types/explore/requests.ts

fix: expand starts_with/ends_with filters

---

packages/analytics/analytics-utilities/src/types/explore/requests.ts

fix: wildcard operator clean up

---

packages/core/forms/src/components/fields/FieldInput.vue
packages/entities/entities-plugins/src/definitions/schemas/BasicAuth.ts
packages/entities/entities-plugins/src/definitions/schemas/KeyAuthEnc.ts
packages/entities/entities-plugins/src/definitions/schemas/OAuth2.ts

Converted encrypted fields to `password` type in the frontend override. Also did some refactor for `FieldInput`.

fix(entities-plugins): encrypted fields in credential forms

---

packages/analytics/analytics-utilities/src/types/explore/requests.ts

fix: include trace_id as string dimension

---

packages/entities/entities-plugins/src/components/PluginForm.vue

fix(entities-plugins): placeholder for empty string

---

.github/workflows/ci.yaml

ci: swap slack action

---

.github/workflows/ci.yaml

ci: bumping slack-notify version

---

.github/pull_request_template.md
.github/workflows/ci.yaml

Utilize the `public-shared-actions` package for Slack notifications
(also cleans up the PR template)

ci: slack notifications

---

packages/core/sandbox-layout/src/components/SandboxLayout.vue

Fixing the double scrollbar in Kongponents sandbox (screenshot)

fix(sandbox-layout): fix overflow

---

packages/analytics/analytics-utilities/src/types/explore/requests.ts

fix: add response_header_content_length as numeric field

---

packages/portal/swagger-ui-web-component/package.json
pnpm-lock.yaml

Revert to previous version before style break.
Adoption PR: https://github.com/Kong/konnect-ui-apps/pull/4451
Before:
After:

chore(swagger): rollback to previous version

---

packages/entities/entities-plugins/src/components/PluginForm.vue

fix(plugin-form): force reset password when edit credential [FTI-6248]

---

package.json
pnpm-lock.yaml
vite.config.shared.ts

* See https://github.com/Kong/shared-ui-components/pull/2872

chore(*): switch back to sass from sass-embedded

---

packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue

[KM-576](https://konghq.atlassian.net/browse/KM-576)
[KM-576]: https://konghq.atlassian.net/browse/KM-576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(consumer-credentials): remove credential column

---

packages/entities/entities-shared/src/components/entity-filter/EntityFilter.vue

fix(entities): fix clear icon button in input

---

packages/entities/entities-plugins/docs/plugin-form.md
packages/entities/entities-plugins/src/components/PluginForm.cy.ts
packages/entities/entities-plugins/src/components/PluginForm.vue

Addresses [KHCP-13673](https://konghq.atlassian.net/browse/KHCP-13673).
[KHCP-13673]: https://konghq.atlassian.net/browse/KHCP-13673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(plugins): ff removal [khcp-13673]

---

packages/entities/entities-plugins/src/components/PluginList.vue

Compatible with different data structures in the List and Filter APIs
[KM-590](https://konghq.atlassian.net/browse/KM-590)
[KM-590]: https://konghq.atlassian.net/browse/KM-590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(entities-plugins): plugin list display incorrect scopes [KM-590]

---

packages/analytics/analytics-chart/README.md
packages/analytics/analytics-chart/sandbox/pages/BarChartDemo.vue
packages/analytics/analytics-chart/sandbox/pages/ChartDemoSimple.vue
packages/analytics/analytics-chart/sandbox/pages/DonutChartDemo.vue
packages/analytics/analytics-chart/sandbox/pages/TimeSeriesChartDemo.vue
packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
packages/analytics/analytics-chart/src/components/chart-plugins/DragSelectPlugin.ts
packages/analytics/analytics-chart/src/components/chart-plugins/VerticalLinePlugin.ts
packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue

https://konghq.atlassian.net/browse/MA-3041
https://www.loom.com/share/74dc8af6086c434682fff43be22ce1a3

feat: add chart zoom custom plugin

---

packages/analytics/analytics-utilities/src/types/explore/requests.ts

feat: add DP version

---

packages/analytics/analytics-utilities/src/types/chart-types.ts

https://konghq.atlassian.net/browse/MA-3055

feat: add map chart type

---

cypress.config.ts
packages/entities/entities-certificates/sandbox/pages/CACertificateListPage.vue
packages/entities/entities-certificates/sandbox/pages/CertificateListPage.vue
packages/entities/entities-certificates/src/components/CACertificateList.vue
packages/entities/entities-certificates/src/components/CertificateList.vue
packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue
packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
packages/entities/entities-consumers/src/components/ConsumerList.vue
packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-key-sets/src/components/KeySetList.vue
packages/entities/entities-keys/src/components/KeyList.vue
packages/entities/entities-plugins/src/components/PluginList.vue
packages/entities/entities-routes/src/components/RouteList.vue
packages/entities/entities-shared/src/components/common/TableTags.cy.ts
packages/entities/entities-shared/src/components/common/TableTags.vue
packages/entities/entities-shared/src/composables/useHelpers.ts
packages/entities/entities-shared/src/index.ts
packages/entities/entities-snis/src/components/SniForm.cy.ts
packages/entities/entities-snis/src/components/SniList.vue
packages/entities/entities-upstreams-targets/src/components/TargetsList.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
packages/entities/entities-vaults/src/components/VaultList.vue

[KM-656](https://konghq.atlassian.net/browse/KM-656)
- Added a `<TableTags>` component to unify usage
- Added compatibility support for JSON stringified `tags` field as a temporary fix
[KM-656]: https://konghq.atlassian.net/browse/KM-656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(entities-*): unify table tags and add compat support for filter apis

---

packages/analytics/dashboard-renderer/src/components/BaseAnalyticsChartRenderer.vue

fix: go to explore - tile and context filters need to be merged

---

packages/analytics/analytics-chart/src/components/AnalyticsChart.vue

fix: chart title should not wrap

---

package.json
packages/analytics/analytics-chart/package.json
packages/analytics/analytics-geo-map/package.json
packages/analytics/analytics-metric-provider/package.json
packages/analytics/dashboard-renderer/package.json
packages/analytics/metric-cards/package.json
packages/core/app-layout/package.json
packages/core/documentation/package.json
packages/core/expressions/package.json
packages/core/forms/package.json
packages/core/misc-widgets/package.json
packages/core/sandbox-layout/package.json
packages/entities/entities-certificates/package.json
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumers/package.json
packages/entities/entities-data-plane-nodes/package.json
packages/entities/entities-gateway-services/package.json
packages/entities/entities-key-sets/package.json
packages/entities/entities-keys/package.json
packages/entities/entities-plugins/package.json
packages/entities/entities-routes/package.json
packages/entities/entities-shared/package.json
packages/entities/entities-snis/package.json
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-vaults/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

chore(deps): bump @kong/kongponents

---

packages/core/expressions/docs/expressions-editor.md
packages/core/expressions/src/components/ExpressionsEditor.vue

Adding `allowEmptyInput` and `editorOptions` for the sampling rules editor.
KM-713

feat(expressions): add allowEmptyInput and editorOptions

---

packages/analytics/analytics-chart/src/components/AnalyticsChart.vue

fix: tweak chart header with when there's no title

---

packages/analytics/analytics-chart/src/components/AnalyticsChart.cy.ts
packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
packages/analytics/analytics-chart/src/components/TopNTable.vue
packages/analytics/analytics-metric-provider/src/components/MetricCardContainer.vue
packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
packages/analytics/dashboard-renderer/sandbox/sandbox-query-provider.ts
packages/analytics/dashboard-renderer/src/components/BaseAnalyticsChartRenderer.vue
packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue
packages/analytics/dashboard-renderer/src/components/QueryDataProvider.vue
packages/analytics/dashboard-renderer/src/components/TopNTableRenderer.vue
packages/analytics/dashboard-renderer/src/composables/index.ts
packages/analytics/dashboard-renderer/src/composables/useEvauluateFeatureFlag.ts
packages/analytics/dashboard-renderer/src/locales/en.json

- introduce a header to dashboard tiles
- render title and kebab menu for tile actions in this header
- behind FF no need for major version upgrade

feat: new dashboard tile header

---

pnpm-lock.yaml

fix(*): lockfile

---

packages/core/forms/src/components/fields/FieldMultiselect.vue
packages/entities/entities-plugins/src/components/PluginForm.vue
packages/entities/entities-plugins/src/composables/useSchemas.ts
packages/entities/entities-plugins/src/definitions/schemas/InjectionProtection.ts
packages/entities/entities-plugins/src/types/plugin-form.ts
packages/entities/entities-plugins/src/types/plugins/injection-protection.d.ts

Support the updated schema of the `injection-protection` plugin.
https://github.com/user-attachments/assets/a4a8ce75-cf8b-482d-bacd-1a1fd7182311
KM-739

feat(entities-plugins): updated injection-protection schema

---

packages/analytics/dashboard-renderer/src/components/DashboardTile.vue

https://konghq.atlassian.net/browse/MA-3479

fix: use correct way to do external link from dropdown item

---

vite.config.shared.ts

Add me (Middle East) support in availableRegion,  it has announced GA release in Nov.

chore(viteconfig): add me in availableRegions

---

packages/analytics/analytics-metric-provider/src/composables/useMetricFetcher.ts
packages/analytics/dashboard-renderer/src/components/QueryDataProvider.vue

https://konghq.atlassian.net/browse/MA-3487

fix: show loading skeleton only when state pending

---

packages/analytics/analytics-chart/src/locales/en.json

feat(analytics-chart): add granularity translations [MA-2148]

---

packages/entities/entities-shared/src/index.ts

[KM-805](https://konghq.atlassian.net/browse/KM-805)
[KM-805]: https://konghq.atlassian.net/browse/KM-805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(entities-shared): export useFetcherCacheKey

---

packages/entities/entities-shared/docs/entity-empty-state.md
packages/entities/entities-shared/sandbox/pages/EntityEmptyStatePage.vue
packages/entities/entities-shared/src/components/entity-empty-state/EntityEmptyState.vue
packages/entities/entities-shared/src/types/entity-empty-state.ts

Minor fixes for `EntityEmptyState` (part of [KHCP-14355](https://konghq.atlassian.net/browse/KHCP-14355)).
Summary of changes:
- minor style fixes
- remove `icon-variant` support in favor of using slots for `features`
[KHCP-14355]: https://konghq.atlassian.net/browse/KHCP-14355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(entity-empty-state): minor fixes [khcp-14355]

---

packages/core/tracing/src/constants/spans.ts
packages/core/tracing/src/types/spans.ts

This pull request updates the types exported from core/tracing for more convenient usage.

fix(tracing): exported types

---

packages/entities/entities-shared/docs/entity-empty-state.md
packages/entities/entities-shared/sandbox/pages/EntityEmptyStatePage.vue
packages/entities/entities-shared/src/components/entity-empty-state/EntityEmptyState.vue

Refactor for `EntityEmptyState`.
Fixes:
- consolidate `title` and `title-after` slots
- allow passing `pricing` as a prop, don't require a boolean to show the slot
- fix logic for showing actions content and add `actions` slot
- require passing a `canCreate` function to show create action
- adjust emits and add type
- minor style fixes
- update docs

fix(entity-empty-state): refactor code

---

packages/analytics/analytics-metric-provider/src/components/metricsProviderUtil.ts
packages/analytics/analytics-utilities/src/types/explore/all.ts
packages/analytics/dashboard-renderer/src/components/QueryDataProvider.vue
packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts

https://konghq.atlassian.net/browse/MA-3522

fix: dashboard support new explore filter format

---

packages/entities/entities-shared/src/components/entity-empty-state/EntityEmptyState.vue

Fix mobile state styles.
Before:
After:

fix(entity-empty-state): mobile style

---

packages/core/expressions/docs/expressions-editor.md
packages/core/expressions/src/components/ExpressionsEditor.vue
packages/core/expressions/src/monaco.ts
packages/core/expressions/src/schema.ts

This PR supports autocompletion docs (provided through `schema.documentation`). A new prop (`defaultShowDetails`) is also added to show the details by default.
KM-846

feat(expressions): support token doc

---

packages/entities/entities-consumer-groups/src/locales/en.json
packages/entities/entities-consumers/src/locales/en.json

KM-862
Provide confirm texts for cascade delete of plugins in consumer and consumer_group.

fix(entities-consumers): provide correct description for cascade delete

---

packages/analytics/analytics-utilities/src/types/explore/advanced.ts

For new Advanced Analytics, add in definitions for newly available dimensions that will soon be used for querying.

feat(analytics): Type support for new dimensions for query and filter

---

packages/analytics/analytics-chart/sandbox/pages/BarChartDemo.vue
packages/analytics/analytics-chart/sandbox/pages/TimeSeriesChartDemo.vue
packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
packages/analytics/analytics-chart/src/locales/en.json
packages/analytics/analytics-chart/src/types/chart-data.ts
packages/analytics/analytics-chart/src/utils/commonOptions.ts

https://konghq.atlassian.net/browse/MA-3511

fix: show tooltip explaining an empty entity in the axis

---

packages/entities/entities-shared/docs/entity-empty-state.md
packages/entities/entities-shared/sandbox/pages/EntityEmptyStatePage.vue
packages/entities/entities-shared/src/components/entity-empty-state/EntityEmptyState.vue

Addresses: https://konghq.atlassian.net/browse/TDX-4934
Add `bottom` slot in EntityEmptyState

fix(entityemptystate): add bottom slot [TDX-4934]

---

packages/core/forms/src/components/fields/FieldArray.vue

Follow up on https://github.com/Kong/public-ui-components/pull/1898: we need to make the same changes in `FieldArray`.
KM-901

fix(forms): textarea resizable in FieldArray

---

packages/analytics/analytics-chart/src/locales/en.json

fix(analytics-chart): update empty text [MA-3574]

---

docs/package-publishing.md

docs(security): add info on approvals

---

packages/analytics/analytics-utilities/src/types/explore/advanced.ts

feat: add response/request size sum aggregations

---

packages/entities/entities-plugins/src/composables/useSchemas.ts
packages/entities/entities-plugins/src/definitions/schemas/OASValidation.ts
packages/entities/entities-plugins/src/types/plugins/oas-validation.d.ts

Update OAS Validation plugin schema to not set a max length on `API Spec` field.
Preview [PR](https://github.com/Kong/konnect-ui-apps/pull/5647) URL: https://pr-5647--gateway-manager.cloud-preview.konghq.tech/gateway-manager

fix(plugins): oas validation schema

---

packages/analytics/analytics-chart/src/components/chart-plugins/ChartTooltip.vue

fix: reduce font size and padding in tooltip

---

packages/core/app-layout/src/components/pageInfoSection/AppPageInfoSection.vue

Fix content section border-radius in AppPageInfoSection component

fix(app-layout): apppageinfosection content border radius

---

.vscode/settings.json

Tweak `scss.scannerExclude` in `.vscode/settings.json` to exclude duplicate tokens

chore(vscode): scss scanner exclude duplicate tokens

---

packages/entities/entities-plugins/src/composables/useSchemas.ts
packages/entities/entities-plugins/src/definitions/schemas/ResponseTransformer.ts
packages/entities/entities-plugins/src/definitions/schemas/ResponseTransformerAdvanced.ts
packages/entities/entities-plugins/src/types/plugin-form.ts
packages/entities/entities-plugins/src/types/plugins/response-transformer-advanced.ts
packages/entities/entities-plugins/src/types/plugins/response-transformer.ts
packages/entities/entities-plugins/src/types/plugins/shared.d.ts

Adjust `Response Transformer` and `Response Transformer Advanced` plugins to display a text area for certain fields instead of regular textbox.
Preview PR: https://github.com/Kong/konnect-ui-apps/pull/5659

fix(plugins): response transformer textareas

---

packages/entities/entities-consumers/src/components/ConsumerList.vue
packages/entities/entities-consumers/src/locales/en.json
packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue

Shared changes to `EntityBaseTable` for new empty states + usage in consumers.
Part of [KHCP-14823](https://konghq.atlassian.net/browse/KHCP-14823).
[KHCP-14823]: https://konghq.atlassian.net/browse/KHCP-14823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(consumers): new empty state [khcp-14823]

---

packages/analytics/dashboard-renderer/package.json
packages/analytics/dashboard-renderer/sandbox/pages/DynamicDashboardDemo.vue
packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
packages/analytics/dashboard-renderer/src/components/layout/DraggableGridLayout.vue
pnpm-lock.yaml

https://konghq.atlassian.net/browse/MA-3625

feat: draggable and resizable dashboard

---

packages/entities/entities-routes/docs/route-list.md
packages/entities/entities-routes/src/components/RouteList.vue
packages/entities/entities-routes/src/locales/en.json

JIRA ticket : https://konghq.atlassian.net/browse/KHCP-14822
New Empty state for Route List component
Konnect Adoption Preview : https://pr-5720--gateway-manager.cloud-preview.konghq.tech/us/gateway-manager
Konnect PR : https://github.com/Kong/konnect-ui-apps/pull/5720
FF : khcp-14756-empty-states-m2

feat: routes list new empty state [KHCP-14822]

---

package.json
pnpm-lock.yaml

[KM-937](https://konghq.atlassian.net/browse/KM-937)
[KM-937]: https://konghq.atlassian.net/browse/KM-937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(deps): update to vitest@3

---

packages/entities/entities-certificates/src/components/CACertificateList.vue
packages/entities/entities-certificates/src/components/CertificateList.vue
packages/entities/entities-consumers/src/components/ConsumerList.vue
packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-plugins/src/components/PluginList.vue

fix: ff guard v2 empty state changes

---

packages/analytics/analytics-utilities/src/types/explore/basic.ts

feat: add portal dimension

---

packages/core/app-layout/sandbox/pages/LayoutPage.vue
packages/core/app-layout/src/components/sidebar/SidebarItem.vue

Fix item truncation when subnav item has badge
Before
After

fix(app-layout): sidebar item badge count truncation

---

packages/entities/entities-certificates/sandbox/pages/CACertificateListPage.vue
packages/entities/entities-certificates/sandbox/pages/CertificateListPage.vue
packages/entities/entities-certificates/src/components/CACertificateList.vue
packages/entities/entities-certificates/src/components/CertificateList.vue
packages/entities/entities-consumers/src/components/ConsumerList.vue
packages/entities/entities-gateway-services/sandbox/pages/GatewayServiceListPage.vue
packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-plugins/sandbox/pages/PluginListPage.vue
packages/entities/entities-plugins/src/components/PluginList.vue
packages/entities/entities-routes/sandbox/pages/RouteListPage.vue
packages/entities/entities-routes/src/components/RouteList.vue

Konnect Preview : https://pr-5833.cloud-preview.konghq.tech/gateway-manager
Konnect Adoption PR : https://github.com/Kong/konnect-ui-apps/pull/5833
Refactored Entities
- RoutesList
- Plugins List
- Gateway Services List
- Certficates List
- CA Certficates List

refactor: remove ff guard and refactor LH button

---

packages/entities/entities-certificates/src/locales/en.json
packages/entities/entities-gateway-services/src/locales/en.json
packages/entities/entities-plugins/src/components/PluginList.vue
packages/entities/entities-plugins/src/locales/en.json
packages/entities/entities-routes/src/components/RouteList.vue
packages/entities/entities-routes/src/locales/en.json

Fixes - hide lh button for nested pages
- Route list
- Plugin list
String Casing fixes

fix: hide lear more, string casing

---

packages/entities/entities-key-sets/docs/key-set-list.md
packages/entities/entities-key-sets/sandbox/pages/KeySetListPage.vue
packages/entities/entities-key-sets/src/components/KeySetList.vue
packages/entities/entities-key-sets/src/locales/en.json
packages/entities/entities-keys/docs/key-list.md
packages/entities/entities-keys/sandbox/pages/KeyListPage.vue
packages/entities/entities-keys/src/components/KeyList.vue
packages/entities/entities-keys/src/locales/en.json

Keys and Key Set New Empty State
FF : khcp-14756-empty-states-m2
Konnect Preview : https://pr-5773--gateway-manager.cloud-preview.konghq.tech/gateway-manager
Konnect Adoption PR : https://github.com/Kong/konnect-ui-apps/pull/5773

feat: keys new empty state

---

packages/entities/entities-upstreams-targets/docs/upstreams-list.md
packages/entities/entities-upstreams-targets/sandbox/pages/UpstreamsListPage.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
packages/entities/entities-upstreams-targets/src/locales/en.json

Upstream new Empty state
FF : khcp-14756-empty-states-m2
Konnect Preview : https://pr-5773--gateway-manager.cloud-preview.konghq.tech/gateway-manager
Konnect Adoption PR : https://github.com/Kong/konnect-ui-apps/pull/5773

feat: added new upstream list empty state

---

packages/core/forms/src/components/fields/FieldArray.vue
packages/core/forms/src/components/fields/FieldTextArea.vue
packages/entities/entities-plugins/src/definitions/schemas/ResponseTransformer.ts
packages/entities/entities-plugins/src/definitions/schemas/ResponseTransformerAdvanced.ts
packages/entities/entities-plugins/src/types/plugins/response-transformer-advanced.ts
packages/entities/entities-plugins/src/types/plugins/response-transformer.ts

- Adding `config-rename-json` to `response-transformer` plugin schema because it needs to be a textarea as well
- Fixing `config-replace-body` schema of the `response-transformer-advanced` plugin
- Removing `rows` and enable `autosize` for `<KTextArea>`
KM-955

fix(plugins): rta plugin schema

---

packages/entities/entities-certificates/src/components/CACertificateList.vue
packages/entities/entities-certificates/src/components/CertificateList.vue
packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
packages/entities/entities-consumers/src/components/ConsumerList.vue
packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-key-sets/src/components/KeySetList.vue
packages/entities/entities-keys/src/components/KeyList.vue
packages/entities/entities-plugins/src/components/PluginList.vue
packages/entities/entities-routes/src/components/RouteList.vue
packages/entities/entities-snis/src/components/SniList.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
packages/entities/entities-vaults/src/components/VaultList.vue

Make the empty states have a unique id per entity type.
Address [KHCP-15185](https://konghq.atlassian.net/browse/KHCP-15185).
[KHCP-15185]: https://konghq.atlassian.net/browse/KHCP-15185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(entities): update empty state data-testids [khcp-15185]

---

packages/entities/entities-plugins/sandbox/index.ts
packages/entities/entities-plugins/sandbox/pages/HomePage.vue
packages/entities/entities-plugins/sandbox/pages/PluginFormPlayground.vue
packages/entities/entities-plugins/src/components/PluginForm.vue
packages/entities/entities-routes/docs/route-form.md

[KM-956](https://konghq.atlassian.net/browse/KM-956)
https://github.com/user-attachments/assets/5b305ffa-6648-4b0d-98dd-81d8ab10579a
[KM-956]: https://konghq.atlassian.net/browse/KM-956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(entities-plugins): add plugin form playground

---

packages/analytics/analytics-utilities/src/dashboardSchema.ts
packages/analytics/analytics-utilities/src/types/chart-types.ts
packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
packages/analytics/dashboard-renderer/src/components/BaseAnalyticsChartRenderer.vue
packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
packages/analytics/dashboard-renderer/src/components/DoughnutChartRenderer.vue

Addresses: https://konghq.atlassian.net/browse/MA-3650
Enabling doughnut charts in DashboardRenderer

fix(dashboard-renderer): enable doughnut charts [MA-3650]

---

packages/entities/entities-plugins/src/components/PluginEntityForm.vue

Array elements are mistakenly deleted.
FTI-6518

fix(forms): array elements are deleted

---

packages/analytics/analytics-chart/src/composables/useExploreResultToTimedDatasets.spec.ts
packages/analytics/analytics-metric-provider/src/mockExploreResponse.ts
packages/analytics/analytics-utilities/src/types/explore/result.ts
packages/analytics/analytics-utilities/src/utils/chartDataGenerator.ts

adding in extra keys to make things more consistent

feat(analytics-utilities): add start/end string as required result set

---

README.md

Small indentation and code block tweaks

docs(readme): fix code blocks

---

packages/analytics/dashboard-renderer/src/components/DashboardTile.vue

feat: remove explore link when portal dimension is present

---

packages/entities/entities-keys/fixtures/mockData.ts
packages/entities/entities-keys/src/components/KeyForm.cy.ts
packages/entities/entities-keys/src/components/KeyForm.vue
packages/entities/entities-keys/src/locales/en.json
packages/entities/entities-keys/src/types/key-form.ts

KM-906
FTI-6399
Adding `x5t` in key form upon customer request.
Related PR: https://github.com/Kong/kong/pull/14154

feat(key-form): add x5t field in key form

---

packages/core/forms/src/components/fields/FieldObjectAdvanced.vue
packages/entities/entities-plugins/src/components/PluginForm.vue

Fixing the following issues in the default `request-callout` plugin form:
1. The `+ Add` button doesn't work: 
https://github.com/user-attachments/assets/bce2b915-255b-40c9-9a9c-a53730d66b0d
2. When editing, the data for `request.body.custom` does not show in the input component: 
https://github.com/user-attachments/assets/15264470-f72c-4d13-aa7e-00e3df9f3672
KM-981

fix(*): nested fields issues

---

packages/entities/entities-plugins/src/composables/useSchemas.ts
packages/entities/entities-plugins/src/definitions/schemas/Confluent.ts
packages/entities/entities-plugins/src/definitions/schemas/KafkaUpstream.ts
packages/entities/entities-plugins/src/types/plugin-form.ts
packages/entities/entities-plugins/src/types/plugins/confluent.ts
packages/entities/entities-plugins/src/types/plugins/kafka-upstream.ts
packages/entities/entities-plugins/src/types/plugins/typedefs.d.ts

There'll be a new field `message_by_lua_functions` for the `kafka-upstream` and `confluent` plugins: https://github.com/Kong/kong-ee/pull/11431. We'll use a textarea for this field.
KM-984

feat(entities-plugins): use textarea for certain fields

---

packages/core/forms/src/components/fields/FieldArray.vue
packages/core/forms/src/components/fields/FieldInput.vue

Use `Number.isFinite` to exclude `NaN`.

fix(forms): use Number.isFinite

---

packages/entities/entities-redis-configurations/src/components/RedisConfigurationForm.vue

[KAG-6540](https://konghq.atlassian.net/browse/KAG-6540)
[KAG-6540]: https://konghq.atlassian.net/browse/KAG-6540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(redis): add password mask

---

packages/entities/entities-certificates/src/components/CACertificateList.vue
packages/entities/entities-certificates/src/components/CertificateList.vue
packages/entities/entities-certificates/src/locales/en.json
packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
packages/entities/entities-consumer-groups/src/locales/en.json
packages/entities/entities-consumers/src/components/ConsumerList.vue
packages/entities/entities-consumers/src/locales/en.json
packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-gateway-services/src/locales/en.json
packages/entities/entities-key-sets/src/components/KeySetList.vue
packages/entities/entities-key-sets/src/locales/en.json
packages/entities/entities-keys/src/components/KeyList.vue
packages/entities/entities-keys/src/locales/en.json
packages/entities/entities-plugins/src/components/PluginList.vue
packages/entities/entities-plugins/src/locales/en.json
packages/entities/entities-routes/src/components/RouteList.vue
packages/entities/entities-routes/src/locales/en.json
packages/entities/entities-shared/src/components/entity-empty-state/EntityEmptyState.vue
packages/entities/entities-shared/src/types/app-config.ts
packages/entities/entities-snis/src/components/SniList.vue
packages/entities/entities-snis/src/locales/en.json
packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
packages/entities/entities-upstreams-targets/src/locales/en.json
packages/entities/entities-vaults/src/components/VaultList.vue
packages/entities/entities-vaults/src/locales/en.json

- Updated empty state content
- Added controlGroup identification boolean in konnect config
- Added content for CPG
- updated EnttityEmptyState message slot css and style updates for secondary appearence
JIRA : https://konghq.atlassian.net/browse/KHCP-15337
Konnect Preview URL :  https://pr-6084.cloud-preview.konghq.tech/

chore: updated content

---

packages/analytics/analytics-chart/sandbox/pages/ChartDemoSimple.vue
packages/analytics/analytics-chart/sandbox/pages/DonutChartDemo.vue
packages/analytics/analytics-chart/src/components/AnalyticsChart.cy.ts
packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
packages/analytics/analytics-chart/src/components/SimpleChart.cy.ts
packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
packages/analytics/analytics-chart/src/components/chart-types/DonutChart.vue
packages/analytics/analytics-chart/src/components/chart-types/GaugeChart.vue
packages/analytics/analytics-chart/src/composables/index.ts
packages/analytics/analytics-chart/src/composables/useDonutChartOptions.ts
packages/analytics/analytics-chart/src/types/chart-data.ts
packages/analytics/analytics-chart/src/types/chart-types.ts
packages/analytics/analytics-chart/src/types/chartjs-options.ts
packages/analytics/analytics-chart/src/utils/commonOptions.ts
packages/analytics/analytics-utilities/src/dashboardSchema.ts
packages/analytics/analytics-utilities/src/types/chart-types.ts
packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
packages/analytics/dashboard-renderer/src/components/DonutChartRenderer.vue

Make the API match the UI / the terminology we decided on.
BREAKING CHANGE: rename doughnut to donut without a fallback.

fix(analytics): rename doughnut -> donut [MA-3729]

---

packages/entities/entities-redis-configurations/src/components/RedisConfigurationForm.cy.ts
packages/entities/entities-redis-configurations/src/components/RedisConfigurationForm.vue

[KAG-6519](https://konghq.atlassian.net/browse/KAG-6519)
[KAG-6519]: https://konghq.atlassian.net/browse/KAG-6519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(redis): make redis partial name immutable

---

.github/workflows/ci.yaml

missed permissions on publish job. needs force-merge to unblock...

fix: missing permissions on publish job

---

packages/analytics/analytics-utilities/src/types/explore/requests.ts

feat: add portal and api to request dimensions

---

packages/entities/entities-redis-configurations/fixtures/mockData.ts
packages/entities/entities-redis-configurations/src/components/RedisConfigurationConfigCard.vue
packages/entities/entities-redis-configurations/src/components/RedisConfigurationForm.vue
packages/entities/entities-redis-configurations/src/components/RedisConfigurationList.vue
packages/entities/entities-redis-configurations/src/composables/useRedisConfigurationForm.ts
packages/entities/entities-redis-configurations/src/helpers.ts
packages/entities/entities-redis-configurations/src/locales/en.json
packages/entities/entities-redis-configurations/src/types/redis-configuration-form.ts
packages/entities/entities-redis-configurations/src/types/redis-configuration.ts

Add `tags` to redis partial
[KM-1036](https://konghq.atlassian.net/browse/KM-1036)
[KM-1036]: https://konghq.atlassian.net/browse/KM-1036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(redis): add tags field

---

packages/analytics/dashboard-renderer/src/components/DashboardTile.vue

feat: disable jump to explore for api queries

---

packages/core/tracing/sandbox/pages/TraceViewPage.vue
packages/core/tracing/src/components/lifecycle/LifecycleView.vue
packages/core/tracing/src/utils/lifecycle.ts

Adds (relative) unique prefixes to nodes to ensure re-layout and re-render on tree change

fix(tracing): re-layout and re-render on tree change

---

.github/workflows/ci.yaml

Addresses security vulnerability; see INC-456.

fix(security): pin version

---

packages/entities/entities-certificates/src/components/CACertificateList.vue
packages/entities/entities-certificates/src/components/CertificateList.vue
packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
packages/entities/entities-consumers/src/components/ConsumerList.vue
packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-key-sets/src/components/KeySetList.vue
packages/entities/entities-keys/src/components/KeyList.vue
packages/entities/entities-plugins/src/components/PluginList.vue
packages/entities/entities-routes/src/components/RouteList.vue
packages/entities/entities-snis/src/components/SniList.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
packages/entities/entities-vaults/src/components/VaultList.vue

Fix search Empty state
JIRA : https://konghq.atlassian.net/browse/KHCP-15502
Adoption PR : https://github.com/Kong/konnect-ui-apps/pull/6179
Preview : https://pr-6179--gateway-manager.cloud-preview.konghq.tech/gateway-manager

fix: fixed wrong empty states for empty search results

---

packages/entities/entities-plugins-metadata/src/index.ts

Ref: https://github.com/Kong/kong-ee/commit/b474f602705635bce49ae09425f5b995ea48bcf9
JIRA: KM-1070, KAG-6667

fix(plugins-metadata): add consumer scope to request callout plugin

---

packages/entities/entities-redis-configurations/src/components/RedisConfigurationForm.vue
packages/entities/entities-redis-configurations/src/constants.ts

[KM-1071](https://konghq.atlassian.net/browse/KM-1071)
[KM-1071]: https://konghq.atlassian.net/browse/KM-1071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(redis): set default redis type to enterprise

---

.github/workflows/ci.yaml
.github/workflows/pr-on-close.yaml

ci: pin action versions

---

packages/entities/entities-gateway-services/src/locales/en.json

- updated placeholder content
Preview : https://pr-6265--gateway-manager.cloud-preview.konghq.tech/gateway-manager

fix: updated placeholder content

---

.github/workflows/ci.yaml

fix: publish release [KHCP-15589]

---

packages/core/tracing/src/components/lifecycle/LifecycleDefaultNodeView.vue
packages/core/tracing/src/components/lifecycle/LifecycleView.vue
packages/core/tracing/src/constants/lifecycle.ts
packages/core/tracing/src/types/lifecycle.ts
packages/core/tracing/src/utils/lifecycle.ts

This pull request adds a Kong frame to the lifecycle view to better annotate the relationship between the nodes:
https://github.com/user-attachments/assets/2ec7ba54-5ee7-41f9-ab63-8fd4c3b484dc
KM-1037

feat(tracing): show a Kong frame in lifecycle

---

CODEOWNERS
packages/core/cli/src/__template__/src/types/index.ts
packages/core/entities-config-editor/LICENSE
packages/core/entities-config-editor/README.md
packages/core/entities-config-editor/package.json
packages/core/entities-config-editor/sandbox/App.vue
packages/core/entities-config-editor/sandbox/index.html
packages/core/entities-config-editor/sandbox/index.ts
packages/core/entities-config-editor/sandbox/tsconfig.json
packages/core/entities-config-editor/src/components/EntitiesConfigEditor.cy.ts
packages/core/entities-config-editor/src/components/EntitiesConfigEditor.spec.ts
packages/core/entities-config-editor/src/components/EntitiesConfigEditor.vue
packages/core/entities-config-editor/src/global-components.d.ts
packages/core/entities-config-editor/src/index.ts
packages/core/entities-config-editor/src/locales/en.json
packages/core/entities-config-editor/src/types/index.ts
packages/core/entities-config-editor/tsconfig.build.json
packages/core/entities-config-editor/tsconfig.json
packages/core/entities-config-editor/vite.config.ts
pnpm-lock.yaml

This pull request contains the pure and untouched files populated by the pnpm run create-package command. The new package `@kong-ui-public/entities-config-editor` will be the codebase for the editor that provides an interactive declarative config editing experience for entities in Konnect and Kong Gateway.
KM-1107

feat(entities-config-editor): create package

---

packages/analytics/analytics-metric-provider/src/components/MetricsProvider.vue

https://konghq.atlassian.net/browse/MA-3679

fix: update additional filter to be ExploreFilterAll type

---

packages/entities/entities-gateway-services/src/components/GatewayServiceForm.vue

Added `data-testId` to the Try Sample API button for improved analytics and test targeting.

fix: added relevant data-testId

---

packages/analytics/analytics-chart/src/composables/useChartLegendValues.ts
packages/analytics/analytics-chart/src/utils/commonOptions.ts

https://konghq.atlassian.net/browse/MA-3796

fix(analytics-chart): remove dollar sign prefix

---

packages/analytics/analytics-utilities/src/types/explore/ai.ts

feat(ai): adding realm, status_code/grouped, ai_plugin_id

---

packages/analytics/analytics-metric-provider/src/components/MetricsProvider.cy.ts
packages/analytics/analytics-metric-provider/src/components/metricsProviderUtil.ts
packages/analytics/analytics-metric-provider/src/types/fetcher-types.ts

fix: metrics provider issue new style filters

---

packages/entities/entities-vaults/sandbox/pages/VaultFormPage.vue
packages/entities/entities-vaults/src/components/VaultForm.vue
packages/entities/entities-vaults/src/locales/en.json
packages/entities/entities-vaults/src/types/vault-form.ts

[KM-1191](https://konghq.atlassian.net/browse/KM-1191)
[KM-1191]: https://konghq.atlassian.net/browse/KM-1191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(vault): add conjur vault provider [KM-1191]

---

packages/entities/entities-redis-configurations/src/components/LinkedPluginList.vue

[KM-1170](https://konghq.atlassian.net/browse/KM-1170)
[KM-1170]: https://konghq.atlassian.net/browse/KM-1170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(redis): hide pagination when optional for redis links [KM-1170]

---

packages/entities/entities-certificates/src/components/CACertificateList.vue
packages/entities/entities-certificates/src/components/CertificateList.vue
packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue
packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
packages/entities/entities-consumers/src/components/ConsumerList.vue
packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
packages/entities/entities-key-sets/src/components/KeySetList.vue
packages/entities/entities-keys/src/components/KeyList.vue
packages/entities/entities-plugins/src/components/PluginList.vue
packages/entities/entities-redis-configurations/src/components/RedisConfigurationList.vue
packages/entities/entities-routes/src/components/RouteList.vue
packages/entities/entities-snis/src/components/SniList.vue
packages/entities/entities-upstreams-targets/src/components/TargetsList.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
packages/entities/entities-vaults/src/components/VaultList.vue

* Update all KClipboardProvider related function signatures.
Update all code infected by the change introduced in https://github.com/Kong/kongponents/pull/2685
This typing issue blocks the renovate job in https://github.com/Kong/public-ui-components/pull/2088
[KM-1202]
/cc @Justineo @2eha0 
[KM-1202]: https://konghq.atlassian.net/browse/KM-1202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(typing): update k-clipboard-provider related typing changes

---

packages/entities/entities-vaults/src/components/VaultForm.vue

Fixing [the interaction error](https://app.datadoghq.com/rum/replay/sessions/3656307c-2542-4059-aa83-4dca4c5c65d5?applicationId=6e430333-9e0f-4d6b-ac63-5f7d4ad9a641&highlightedEventId=AwAAAZZ1uWIaNVfklQAAABhBWloxdVc4b0FBQ2NaV1NId19TckhnQUEAAAAkMDE5Njc2NDItNzcyNS00ZWMyLTk5MjEtOTYyYzg4YmQyZmVkAAAQmw&seed=294b7463-5959-4285-a14b-43fda11cdd25&ts=1745731805722&from=1745731805666) due to Google Translate in the vault form.
[KM-1213](https://konghq.atlassian.net/browse/KM-1213)
[DD Error](https://app.datadoghq.com/rum/replay/sessions/3656307c-2542-4059-aa83-4dca4c5c65d5?applicationId=6e430333-9e0f-4d6b-ac63-5f7d4ad9a641&highlightedEventId=AwAAAZZ1uWIaNVfklQAAABhBWloxdVc4b0FBQ2NaV1NId19TckhnQUEAAAAkMDE5Njc2NDItNzcyNS00ZWMyLTk5MjEtOTYyYzg4YmQyZmVkAAAQmw&seed=294b7463-5959-4285-a14b-43fda11cdd25&ts= …

fix(vault): browser translate error [KM-1213]

---

packages/entities/entities-consumer-groups/docs/consumer-group-form.md
packages/entities/entities-consumer-groups/src/components/ConsumerGroupForm.vue

feat(consumer-groups): add `hide-consumers` to consumer groups form

---

packages/analytics/dashboard-renderer/src/components/DashboardTile.vue

fix: enable jump to explore for portal dimensions

---

packages/entities/entities-routes/src/components/RouteConfigCard.vue
packages/entities/entities-routes/src/locales/en.json

1. Unified the tooltip copy on the route form page and route detail page.
2. Updated the tooltip copy according to the feedback from the docs team.

fix(entities-routes): update tooltip copy

---

packages/entities/entities-routes/src/utilities/helpers.ts

This PR fixes a bug where if a route is created using headers, the initial config type is incorrectly set to Basic when editing it.

fix(entities-routes): wrong config type when editing

---

packages/analytics/analytics-metric-provider/src/components/MetricsProvider.cy.ts
packages/analytics/analytics-metric-provider/src/components/MetricsTestHarness.vue
packages/analytics/analytics-utilities/src/types/explore/advanced.ts
packages/analytics/analytics-utilities/src/types/explore/ai.ts
packages/analytics/analytics-utilities/src/types/explore/all.ts
packages/analytics/analytics-utilities/src/types/explore/basic.ts
packages/analytics/analytics-utilities/src/types/explore/requests.ts
packages/analytics/dashboard-renderer/sandbox/mock-data.ts
packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue
packages/analytics/dashboard-renderer/src/components/QueryDataProvider.vue

feat(analytics-utilities): remove old style filters

---

packages/entities/entities-vaults/sandbox/pages/VaultFormPage.vue
packages/entities/entities-vaults/src/components/VaultForm.vue
packages/entities/entities-vaults/src/locales/en.json
packages/entities/entities-vaults/src/types/vault-form.ts

[KM-1283](https://konghq.atlassian.net/browse/KM-1283)
[Schema changes](https://github.com/Kong/kong-ee/pull/12244)
[KM-1283]: https://konghq.atlassian.net/browse/KM-1283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(vault): add base64_decode field [KM-1283]

---

packages/analytics/analytics-metric-provider/sandbox/App.vue
packages/analytics/analytics-metric-provider/src/components/MetricsConsumer.vue
packages/analytics/analytics-metric-provider/src/components/display/MetricsCard.vue
packages/analytics/analytics-metric-provider/src/locales/en.json

- Update text styles for card titles
- Update "Average" to "Avg."
- Add divider lines between cards.

feat(analytics): update small metric card styling [MA-3932]

---

packages/analytics/analytics-utilities/src/dashboardSchema.ts
packages/analytics/dashboard-renderer/src/components/DashboardTile.vue

feat: add global filters

---

packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue

Addresses: https://konghq.atlassian.net/browse/MA-3841
Set `margin: 0;` in horizontal chart legend

fix(analytics-chart): horizontal chart legend margin [MA-3841]

---

packages/entities/entities-plugins/src/components/free-form/shared/ArrayField.vue
packages/entities/entities-plugins/src/locales/en.json

Add `data-testid` for free form fields in order to get tests done.

test(free-form): add `data-testid` for required fileds

---

packages/entities/entities-vaults/src/components/VaultForm.vue
packages/entities/entities-vaults/src/types/vault-form.ts

feat(vault): add base64 field to conjur [KM-1306]

---

packages/analytics/analytics-utilities/src/dashboardSchema.ts
packages/analytics/dashboard-renderer/sandbox/mock-data.ts
packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue

feat: combine context and global filters

---

packages/entities/entities-vaults/src/components/VaultForm.vue
packages/entities/entities-vaults/src/types/vault-form.ts

[Schema definition](https://github.com/Kong/kong-ee/blob/11c8ff4c18a1e8181cbc4b1eda233ac1a3d87887/kong/vaults/conjur/schema.lua#L20)

fix(vault): set conjur auth_method vault to be api_key

---

packages/entities/entities-gateway-services/src/components/GatewayServiceForm.vue

In the revamped service form, we don't need to call `validateUrl` after the form submit button is clicked because URL is validated in real time. 
KM-1235

fix(entities-gateway-services): error message flicker

---

packages/entities/entities-plugins/src/components/free-form/shared/ArrayField.vue
packages/entities/entities-plugins/src/components/free-form/shared/BooleanField.vue
packages/entities/entities-plugins/src/components/free-form/shared/EnumField.vue
packages/entities/entities-plugins/src/components/free-form/shared/KeyValueField.vue
packages/entities/entities-plugins/src/components/free-form/shared/NumberField.vue
packages/entities/entities-plugins/src/components/free-form/shared/ObjectField.vue
packages/entities/entities-plugins/src/components/free-form/shared/StringField.vue
packages/entities/entities-plugins/src/components/free-form/shared/TagField.vue

[KM-1313](https://konghq.atlassian.net/browse/KM-1313)
[KM-1313]: https://konghq.atlassian.net/browse/KM-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

test(free-form): add test-id [KM-1313]

---

packages/entities/entities-vaults/sandbox/pages/VaultFormPage.vue
packages/entities/entities-vaults/src/components/VaultForm.vue
packages/entities/entities-vaults/src/locales/en.json
packages/entities/entities-vaults/src/types/vault-form.ts

[KM-1303](https://konghq.atlassian.net/browse/KM-1303)
[Schema changing](https://github.com/Kong/kong-ee/pull/12418)
[KM-1303]: https://konghq.atlassian.net/browse/KM-1303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(entities-vaults): add cert based authentication to hcv [KM-1303]

---

packages/entities/entities-plugins/src/components/free-form/shared/ObjectField.vue

fix(free-form): record cannot be removed [KAG-7153]

---

packages/entities/entities-vaults/src/components/VaultForm.vue
packages/entities/entities-vaults/src/locales/en.json
packages/entities/entities-vaults/src/types/vault-form.ts

Schema change: https://github.com/Kong/kong-ee/pull/12685
[KM-1354](https://konghq.atlassian.net/browse/KM-1354)
[KM-1354]: https://konghq.atlassian.net/browse/KM-1354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(vault): remove hcv cert auth verify flag [KM-1354]

---

packages/entities/entities-plugins-icon/LICENSE
packages/entities/entities-plugins-icon/README.md
packages/entities/entities-plugins-icon/package.json
packages/entities/entities-plugins-icon/sandbox/App.vue
packages/entities/entities-plugins-icon/sandbox/index.html
packages/entities/entities-plugins-icon/sandbox/index.ts
packages/entities/entities-plugins-icon/sandbox/tsconfig.json
packages/entities/entities-plugins-icon/src/components/EntitiesPluginsIcon.cy.ts
packages/entities/entities-plugins-icon/src/components/EntitiesPluginsIcon.spec.ts
packages/entities/entities-plugins-icon/src/components/EntitiesPluginsIcon.vue
packages/entities/entities-plugins-icon/src/global-components.d.ts
packages/entities/entities-plugins-icon/src/index.ts
packages/entities/entities-plugins-icon/src/locales/en.json
packages/entities/entities-plugins-icon/src/types/index.ts
packages/entities/entities-plugins-icon/tsconfig.build.json
packages/entities/entities-plugins-icon/tsconfig.json
packages/entities/entities-plugins-icon/vite.config.ts
pnpm-lock.yaml

This new package for the plugin icon, which will be extracted from `entities-plugins`.

chore: create a new package for plugin icon [KM-1318]

---

packages/entities/entities-upstreams-targets/docs/upstreams-form.md
packages/entities/entities-upstreams-targets/sandbox/pages/UpstreamFormPage.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsForm.vue
packages/entities/entities-upstreams-targets/src/components/UpstreamsFormLoadBalancing.cy.ts
packages/entities/entities-upstreams-targets/src/components/UpstreamsFormLoadBalancing.vue
packages/entities/entities-upstreams-targets/src/composables/useHelpers.ts
packages/entities/entities-upstreams-targets/src/locales/en.json
packages/entities/entities-upstreams-targets/src/types/upstreams-form.ts

Adding support for two new fields. Reference: https://github.com/Kong/kong-ee/pull/12524.
KM-1358

feat(entities-upstreams-targets): support sticky sessions

---

packages/entities/entities-plugins/package.json
packages/entities/entities-plugins/src/components/free-form/Datakit/DatakitForm.vue
packages/entities/entities-plugins/src/components/free-form/shared/FormSection.vue
packages/entities/entities-plugins/src/components/free-form/shared/layout/StandardLayout.vue
packages/entities/entities-plugins/src/locales/en.json

[KM-1360](https://konghq.atlassian.net/browse/KM-1360)
[KM-1360]: https://konghq.atlassian.net/browse/KM-1360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(entities-plugins): improve datakit yaml description

---

packages/analytics/dashboard-renderer/src/components/DashboardTile.vue

feat: remove ma-3630-portal-v3 flag

---

packages/entities/entities-vaults/src/components/VaultForm.vue
packages/entities/entities-vaults/src/locales/en.json

feat(vault): rename labels and tooltips [KM-1379]

---

packages/entities/entities-shared/src/components/entity-filter/EntityFilter.vue
packages/entities/entities-shared/src/types/entity-filter.ts

feat(entity-shared): enhance the filter of the select input

---

packages/entities/entities-plugins/src/components/free-form/Datakit/DatakitForm.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/examples/authenticate.yml
packages/entities/entities-plugins/src/components/free-form/Datakit/examples/combine.yml
packages/entities/entities-plugins/src/components/free-form/Datakit/examples/index.ts
packages/entities/entities-plugins/src/locales/en.json
packages/entities/entities-plugins/tsconfig.build.json

[KM-1414](https://konghq.atlassian.net/browse/KM-1414)
[KM-1414]: https://konghq.atlassian.net/browse/KM-1414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(entities-plugins): improve datakit examples

---

packages/entities/entities-plugins/src/components/free-form/Datakit/DatakitForm.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/examples/authenticate.yml
packages/entities/entities-plugins/src/locales/en.json

[KM-1414](https://konghq.atlassian.net/browse/KM-1414)
[KM-1414]: https://konghq.atlassian.net/browse/KM-1414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(entities-plugins): use correct datakit authenticate example

---

packages/analytics/analytics-utilities/package.json
packages/analytics/analytics-utilities/src/dashboardSchema.v2.ts
packages/analytics/analytics-utilities/src/index.ts

- Copy the v1 schema to ensure no changes.  Don't change the default export.
- Apply changes as described in MA-3920.

feat(analytics): dashboard schema v2 [MA-4017]

---

packages/entities/entities-plugins/src/components/free-form/RequestCallout/RequestCalloutForm.vue
packages/entities/entities-plugins/src/components/free-form/shared/PluginFormWrapper.vue

KM-1470
|Before| After |
|---|---|
| <img width="369" alt="image" src="https://github.com/user-attachments/assets/aff09574-2b69-4d46-b019-bb1f5a80c1ba" /> |<img width="484" alt="image" src="https://github.com/user-attachments/assets/d9ffca5f-b99d-49dd-ba1c-952927cfac38" />|
Caused by https://github.com/Kong/public-ui-components/pull/2112

fix(plugin-request-callout): vault picker missing [KM-1470]

---

packages/entities/entities-plugins/src/components/free-form/Datakit/examples/manipulate.yml

[KM-1472](https://konghq.atlassian.net/browse/KM-1472)
[KM-1472]: https://konghq.atlassian.net/browse/KM-1472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(entities-plugins): fix datakit example code

---

packages/analytics/analytics-utilities/src/types/explore/common.ts

Used for new fine-granularity feature.
https://konghq.atlassian.net/browse/MA-4089

feat(fine-granularity): add response type for getting back information about available granularity

---

packages/analytics/analytics-chart/src/components/chart-plugins/HighlightPlugin.ts
packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue

https://konghq.atlassian.net/browse/MA-4101

fix: pause highlight plugin while zooming/selecting chart area

---

packages/core/app-layout/src/components/sidebar/AppSidebar.vue

fix(app-layout): group name styles

---

packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
packages/analytics/dashboard-renderer/src/components/DashboardTile.cy.ts
packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
packages/analytics/dashboard-renderer/src/locales/en.json

https://konghq.atlassian.net/browse/MA-3901

fix: aged out data warning on dashboard tiles

---

packages/analytics/analytics-config-store/package.json

The analytics config store should be considered stable and properly reflect breaking changes.

chore(analytics): set config store version to 1.x

---

packages/core/expressions/package.json
packages/entities/entities-redis-configurations/package.json

Release version 1.0.0 of `@kong-ui-public/expressions` and `@kong-ui-public/entities-redis-configurations`.

feat(*): release version 1.0.0 for expressions and redis config

---

packages/entities/entities-plugins/src/components/free-form/Datakit/visual-editor/constants.ts
packages/entities/entities-plugins/src/components/free-form/Datakit/visual-editor/modal/EditorContent.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/visual-editor/modal/EditorMain.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/visual-editor/modal/EditorModal.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/visual-editor/node/nodePropertiesPanel.vue

https://github.com/user-attachments/assets/f4f88630-6469-4f00-bba8-bf51ecfbdf00

feat(datakit): node properties panel [KM-1460]

---

packages/analytics/dashboard-renderer/src/components/DashboardTile.vue

https://konghq.atlassian.net/browse/MA-4108

fix(dashboard-renderer): max-width 320px for aged data warning tooltip

---

packages/analytics/analytics-chart/src/components/chart-plugins/DragSelectPlugin.ts

https://konghq.atlassian.net/browse/MA-4109

fix: handle zooming right to left ensure end > start

---

packages/analytics/analytics-utilities/src/dashboardSchema.v2.ts

Preparation for removing this field from dashboard schemas in favor of strictly using endpoints for versioning.

feat(dashboard-schema): make 'version' optional [MA-3935]

---

packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue

fix: wrong ff evaluated for zoom actions

---

packages/entities/entities-plugins/src/components/free-form/shared/EnhancedInput.vue
packages/entities/entities-plugins/src/components/free-form/shared/KeyValueField.vue
packages/entities/entities-plugins/src/components/free-form/shared/NumberField.vue
packages/entities/entities-plugins/src/components/free-form/shared/StringField.vue
packages/entities/entities-plugins/src/components/free-form/shared/TagField.vue
packages/entities/entities-plugins/src/components/free-form/shared/types.ts

feat(entities-plugins): freeform - suport lazy update input

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/node.ts
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/helpers.ts
packages/entities/entities-plugins/src/components/free-form/Datakit/types.ts

[KM-1494](https://konghq.atlassian.net/browse/KM-1494)
[KM-1494]: https://konghq.atlassian.net/browse/KM-1494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(entities-plugins): datakit - improve I/O meta

---

packages/entities/entities-shared/src/types/entity-base-config-card.ts

Add supported entity type for event gateway

chore(entities-shared): add supported entity type for event gateway

---

packages/core/forms/src/components/RedisConfigSelect.vue
packages/entities/entities-plugins/src/components/free-form/shared/RedisSelector.vue
packages/entities/entities-redis-configurations/src/components/RedisConfigurationList.vue

feat(*): filter out non-redis partials in redis partials [KM-1546]

---

packages/core/app-layout/src/components/pageInfoSection/AppPageInfoSection.vue

fix(app-layout): app page info section slotted table sticky columns

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/InputsField.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/NodeFormCall.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/NodeFormProperty.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/PropertiesField.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/composables.ts
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/property.ts
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/NodePanel.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/NodePropertiesPanel.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/mock.ts
packages/entities/entities-plugins/src/locales/en.json

KM-1460
https://github.com/user-attachments/assets/9cdfc65f-16de-4a8d-af5e-760fd111c89e

feat(entities-plugins): datakit - property node form [KM-1460]

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/NodeFormExit.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/NodePropertiesPanel.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/mock.ts

feat(entities-plugins): datakit - exit node form [KM-1460]

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/InputsField.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/InputsMapField.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/NodeFormJq.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/composables.ts
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/init.ts
packages/entities/entities-plugins/src/components/free-form/shared/composables.ts
packages/entities/entities-plugins/src/components/free-form/shared/headless/useKeyValueField.ts

KM-1460
* Complete user-defined field UI operations.
* Fix node fields init logic.
* Optimize types definition.
https://github.com/user-attachments/assets/18d7a2ae-06f1-4af1-8861-32d5e4028f1f

feat(entities-plugins): datakit - jq form data binding [KM-1460]

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/NodeFormResponse.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/NodeFormServiceRequest.vue

Form data binding for the `Response` and `ServiceRequest` forms

feat(entities-plugins): datakit - data binding for 2 forms [KM-1460]

---

packages/analytics/dashboard-renderer/src/components/BaseAnalyticsChartRenderer.vue
packages/analytics/dashboard-renderer/src/components/DashboardTile.cy.ts
packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
packages/analytics/dashboard-renderer/src/locales/en.json

https://konghq.atlassian.net/browse/MA-4179
Behind [Feature Flag](https://app.launchdarkly.com/projects/default/flags/analytics-chart-zoom-actions/targeting?env=local&env=dev&selected-env=dev)
Wired up "View Requests" functionality in dashboards.
- Handle analytics chart view request event from zoom actions
- Add View requests option to dashboard tile kebab menu
- Build api requests query and navigate to requests on view requests event or clicking view requests option in kebab menu

feat: wire up view requests in dashboards

---

packages/analytics/analytics-utilities/src/dashboardSchema.v2.ts

Add template_id to dashboard jsonschema

fix(analytics): add template_id optional field on dashboard schema

---

packages/core/forms/package.json
packages/core/forms/src/components/FormGroup.vue
pnpm-lock.yaml
pnpm-workspace.yaml

1. For field tooltip, sanitize the help string before passing it to `v-html`.
2. For field label/hint/error, use text Interpolation.
KM-1563

fix(forms): xss vulnerability in plugin schema

---

packages/analytics/analytics-chart/src/components/ZoomActions.vue
packages/analytics/analytics-chart/src/components/ZoomTimerange.vue
packages/analytics/analytics-chart/src/components/chart-plugins/ChartTooltip.vue
packages/analytics/analytics-chart/src/components/chart-plugins/DragSelectPlugin.ts
packages/analytics/analytics-chart/src/locales/en.json
packages/analytics/analytics-chart/src/styles/mixins.scss

https://konghq.atlassian.net/browse/MA-4146
https://github.com/user-attachments/assets/0d45645f-0fbf-48c9-af38-eacf844d3eda

fix: align analytics chart zoom ux with design

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/FlowEditor.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorMain.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorModal.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/store.ts
packages/entities/entities-plugins/src/locales/en.json

[KM-1581](https://konghq.atlassian.net/browse/KM-1581)
[KM-1581]: https://konghq.atlassian.net/browse/KM-1581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(entities-plugins): done button for datakit modal

---

package.json
packages/entities/entities-certificates/package.json
packages/portal/document-viewer/package.json
pnpm-lock.yaml

**Note: This is a human made PR!!!**
| Package | Change | Age | Confidence |
|---|---|---|---|
| [@babel/types](https://babel.dev/docs/en/next/babel-types) ([source](https://redirect.github.com/babel/babel/tree/HEAD/packages/babel-types)) | [`^7.26.0` -> `^7.28.2`](https://renovatebot.com/diffs/npm/@babel%2ftypes/7.26.9/7.28.2) | [![age](https://developer.mend.io/api/mc/badges/age/npm/@babel%2ftypes/7.28.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@babel%2ftypes/7.26.9/7.28.2?slim=true)](https://docs.renovatebot.com/merge-confidence/) |
| [@commitlint/cli](https://commitlint.js.org/) ([source](https://redirect.github.com/conventional-changelog/commitlint/tree/HEAD/@commitlint/cli)) | [`^19.5.0` -> …

fix(@babel/types): v7.28.2

---

packages/entities/entities-plugins/src/components/free-form/RequestCallout/CalloutsForm.vue
packages/entities/entities-plugins/src/components/free-form/shared/headless/useKeyValueField.ts

fix(entities-plugins): request callout - KV default null [KM-1580]

---

packages/entities/entities-plugins/src/components/free-form/ServiceProtection/ConfigForm.vue

fix(entities-plugins): service protection - delete namespace when it is null

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/composables/useFlow.ts

[KM-1610](https://konghq.atlassian.net/browse/KM-1610)
[KM-1610]: https://konghq.atlassian.net/browse/KM-1610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(entities-plugins): datakit allow delete nodes with delete key

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorCanvasFlow.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorContent.vue

[KM-1611](https://konghq.atlassian.net/browse/KM-1611)
[KM-1611]: https://konghq.atlassian.net/browse/KM-1611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(entities-plugins): datakit improve modal background color

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/composables/validation/business.ts
packages/entities/entities-plugins/src/locales/en.json

feat(entities-plugins): datakit - reserved node name check [KM-1617]

---

packages/entities/entities-plugins/src/utils/helper.ts

fix(entities-plugins): kafka-* set confluent to null if is default value [KM-1616]

---

packages/analytics/analytics-chart/README.md
packages/analytics/analytics-chart/sandbox/pages/BarChartDemo.vue
packages/analytics/analytics-chart/sandbox/pages/DonutChartDemo.vue
packages/analytics/analytics-chart/sandbox/pages/TimeSeriesChartDemo.vue
packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
packages/analytics/dashboard-renderer/README.md
packages/analytics/dashboard-renderer/sandbox/pages/EditableDashboardDemo.vue
packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
packages/analytics/dashboard-renderer/src/components/BaseAnalyticsChartRenderer.vue
packages/analytics/dashboard-renderer/src/components/DashboardTile.cy.ts
packages/analytics/dashboard-renderer/src/components/DashboardTile.vue

- Remove unused prop from `AnalyticsChart`.
- Update dashboard renderer sandbox to v2 schema.
- Fix use of the `allow_csv_export` property in `DashboardTile`.

fix(analytics): fix uses of `allow_csv_export`

---

packages/analytics/analytics-geo-map/README.md
packages/analytics/analytics-geo-map/package.json

Analytics geo map version to 1.0.0
Update readme

fix: forgot to bump the version to 1.0.0

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/composables/useFlow.ts
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorCanvas.vue

[KM-1652](https://konghq.atlassian.net/browse/KM-1652)
https://github.com/user-attachments/assets/05306ce7-8553-4d1a-98cb-82495a45caa9
[KM-1652]: https://konghq.atlassian.net/browse/KM-1652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(entities-plugins): datakit edge style, sync selection state

---

packages/entities/entities-plugins/src/components/free-form/Common/CommonForm.vue
packages/entities/entities-plugins/src/components/free-form/Common/ConfigForm.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/DatakitForm.vue
packages/entities/entities-plugins/src/components/free-form/shared/layout/StandardLayout.vue

feat(entities-plugins): jwt-signer - using standard layout

---

packages/entities/entities-plugins/src/components/free-form/shared/layout/StandardLayout.vue
packages/entities/entities-plugins/src/locales/en.json

fix(entities-plugins): standard layout plugin config description

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/FlowPanels.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/composables/useHotkeys.ts
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorContent.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorMain.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorNav.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/flow.ts
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/history.ts
packages/entities/entities-plugins/src/locales/en.json

[KM-1661](https://konghq.atlassian.net/browse/KM-1661)
https://github.com/user-attachments/assets/2934d9f9-4f27-4a9e-9487-979d47c18bcb
[KM-1661]: https://konghq.atlassian.net/browse/KM-1661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(entities-plugins): datakit ui undo redo buttons and hotkeys

---

packages/entities/entities-plugins/src/components/free-form/shared/composables.ts

fix(entities-plugins): useItemKeys [KM-1673]

---

packages/entities/entities-plugins/src/components/free-form/Datakit/DatakitForm.vue

[KM-1676](https://konghq.atlassian.net/browse/KM-1676)
[KM-1676]: https://konghq.atlassian.net/browse/KM-1676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(entities-plugins): datakit editor mode

---

packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
packages/analytics/analytics-chart/src/locales/en.json
packages/analytics/dashboard-renderer/src/components/BaseAnalyticsChartRenderer.vue
packages/analytics/dashboard-renderer/src/components/DashboardTile.cy.ts
packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
packages/analytics/dashboard-renderer/src/components/TimeseriesChartRenderer.vue
packages/analytics/dashboard-renderer/src/composables/index.ts
packages/analytics/dashboard-renderer/src/composables/useContextLinks.spec.ts
packages/analytics/dashboard-renderer/src/composables/useContextLinks.ts
packages/analytics/dashboard-renderer/src/types/renderer-types.ts

https://konghq.atlassian.net/browse/MA-4272
ui-apps pr: https://github.com/Kong/konnect-ui-apps/pull/8128
- Add exploreLink prop to analytics chart and add explore zoom action item
- DashboardTile 
- moved link generating logic to composable.
- generate explore link on sele
- add unit test for new composable
https://github.com/user-attachments/assets/27fc6c41-beb4-4304-94c3-a326bb761c77
ct chart range event

feat: add explore link to zoom actions

---

packages/entities/entities-plugins/src/components/PluginForm.cy.ts
packages/entities/entities-plugins/src/components/free-form/shared/composables.ts
packages/entities/entities-plugins/src/locales/en.json
packages/entities/entities-vaults/src/locales/en.json

[KM-1685](https://konghq.atlassian.net/browse/KM-1685)
[KM-1685]: https://konghq.atlassian.net/browse/KM-1685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(*): freeform - use sentence case [KM-1685]

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/InputsMapField.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/InputsRecordField.vue
packages/entities/entities-plugins/src/components/free-form/shared/EnumField.vue

feat(entities-plugins): datakit - make input field searchable

---

packages/analytics/dashboard-renderer/src/components/DashboardTile.cy.ts
packages/analytics/dashboard-renderer/src/composables/useContextLinks.ts

Fix [MA-4279](https://konghq.atlassian.net/browse/MA-4279)
This will ensure that the filters used when generating a request URL link are scoped to the datasource of the dashboard tile.
[MA-4279]: https://konghq.atlassian.net/browse/MA-4279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(analytics): exclude irrelevant filters for view requests [MA-4279]

---

packages/core/forms/src/components/forms/RLAForm.vue
packages/core/forms/src/locales/en.json
packages/entities/entities-plugins/src/components/free-form/shared/AdvancedFields.vue

[KM-1694](https://konghq.atlassian.net/browse/KM-1694)
[KM-1694]: https://konghq.atlassian.net/browse/KM-1694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(forms,entities-plugins): fix rla view_advanced label, add testid

---

packages/entities/entities-plugins-metadata/src/index.ts

Change the category of Kafka Consume plugin from Transformations to Traffic Control.

fix(entities-plugins-metadata): adjust the category of kafka consume

---

packages/entities/entities-plugins/src/components/PluginSelect.vue

[KM-1697](https://konghq.atlassian.net/browse/KM-1697)
[KM-1697]: https://konghq.atlassian.net/browse/KM-1697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(plugins): autofocus plugin filter on creation page

---

packages/analytics/analytics-chart/src/locales/en.json

Fix [MA-4255](https://konghq.atlassian.net/browse/MA-4255)
This will add the `vulnerability_count` locale string to analytics-chart.
[MA-4255]: https://konghq.atlassian.net/browse/MA-4255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(analytics): add vulnerability_count to locale entries [MA-4255]

---

packages/entities/entities-plugins/src/utils/helper.ts

KM-1698
In this PR:
* enhanced `SchemaRegistry` interface definition
* remove unnecessary fields depends on the value of `mode`

fix(entities-plugins): schema registry data transform [KM-1698]

---

packages/entities/entities-plugins/src/components/PluginEntityForm.vue
packages/entities/entities-plugins/src/components/PluginForm.vue
packages/entities/entities-plugins/src/composables/useSchemas.ts

feat(entities-plugins): add engine prop to plugin form

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/InputsMapField.vue

Before
https://github.com/user-attachments/assets/1c8fb11b-ce01-440e-8835-f8caf96f5414
After
https://github.com/user-attachments/assets/83051454-6fe6-4c57-9621-9d204fa062df

fix(entities-plugins): datakit - unexpected disabled state

---

packages/analytics/dashboard-renderer/src/composables/useContextLinks.ts

View requests in the kebab menu should be behind FF

fix: view requests kebab menu link behind FF

---

packages/entities/entities-plugins/src/utils/helper.ts

Fixing https://github.com/Kong/konnect-ui-apps/actions/runs/17572584503/job/49926754710?pr=8278

fix(entities-plugins): add empty confluent case

---

package.json
packages/analytics/analytics-chart/package.json
packages/analytics/analytics-geo-map/package.json
packages/analytics/analytics-metric-provider/package.json
packages/analytics/dashboard-renderer/package.json
packages/core/app-layout/package.json
packages/core/documentation/package.json
packages/core/entities-config-editor/package.json
packages/core/expressions/package.json
packages/core/forms/package.json
packages/core/misc-widgets/package.json
packages/core/sandbox-layout/package.json
packages/entities/entities-certificates/package.json
packages/entities/entities-consumer-credentials/package.json
packages/entities/entities-consumer-groups/package.json
packages/entities/entities-consumers/package.json
packages/entities/entities-data-plane-nodes/package.json
packages/entities/entities-gateway-services/package.json
packages/entities/entities-key-sets/package.json
packages/entities/entities-keys/package.json
packages/entities/entities-plugins/package.json
packages/entities/entities-redis-configurations/package.json
packages/entities/entities-routes/package.json
packages/entities/entities-shared/package.json
packages/entities/entities-snis/package.json
packages/entities/entities-upstreams-targets/package.json
packages/entities/entities-vaults/package.json
packages/portal/document-viewer/package.json
packages/portal/spec-renderer/package.json
pnpm-lock.yaml

chore(*): bump kongponents version

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/NodeFormJq.vue
packages/entities/entities-plugins/src/components/free-form/shared/StringField.vue

fix(entities-plugins): datakit - jq textarea error message

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/composables/useNodeForm.ts

fix(entities-plugins): datakit - remove unecessary connection confirm

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/composables/useNodeForm.ts

fix(entities-plugins): datakit - confirmation history ops

---

packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/init.ts

[KM-1766](https://konghq.atlassian.net/browse/KM-1766)
[KM-1766]: https://konghq.atlassian.net/browse/KM-1766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(entities-plugins): datakit field order should cover pure config

---

packages/analytics/analytics-chart/src/locales/en.json
packages/analytics/analytics-geo-map/src/utils/explore-to-country-metrics.spec.ts
packages/analytics/analytics-geo-map/src/utils/explore-to-country-metrics.ts
packages/analytics/analytics-utilities/src/dashboardSchema.v2.ts
packages/analytics/analytics-utilities/src/types/country-codes.ts
packages/analytics/analytics-utilities/src/types/explore/advanced.ts
packages/analytics/analytics-utilities/src/types/explore/requests.ts
packages/analytics/dashboard-renderer/sandbox/pages/EditableDashboardDemo.vue
packages/analytics/dashboard-renderer/sandbox/sandbox-query-provider.ts

Fix [MA-3448](https://konghq.atlassian.net/browse/MA-3448)
This will remove all mentions of `iso_code` in favor of `country_code`
[MA-3448]: https://konghq.atlassian.net/browse/MA-3448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(analytics): remove mentions of iso_code [MA-3448]

---

packages/core/app-layout/sandbox/pages/SidebarPage.vue
packages/core/app-layout/src/components/AppLayout.vue
packages/core/app-layout/src/components/sidebar/AppSidebar.cy.ts
packages/core/app-layout/src/components/sidebar/AppSidebar.vue
packages/core/app-layout/src/components/sidebar/SidebarItem.vue

Add slot for `New` badge in sidebar items for AI Gateway FTUX.
Part of [KHCP-17791](https://konghq.atlassian.net/browse/KHCP-17791).
Figma: https://www.figma.com/design/wckYijTTGiSb2N0KQrZxcm/AI-Gateway?node-id=7089-23373&t=ozSaSThi8I47idNK-1
[KHCP-17791]: https://konghq.atlassian.net/browse/KHCP-17791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(sidebar): add badge slot [khcp-17791]

---

packages/entities/entities-plugins/src/components/PluginConfigCard.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/DatakitConfigCardCanvas.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/FlowCanvas.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/FlowEditor.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/FlowPanels.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorMain.vue
packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/FlowNode.vue
packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardDisplay.vue
packages/entities/entities-shared/src/components/entity-base-config-card/EntityBaseConfigCard.vue

feat(entities-*): datakit - plugin detail page [KM-1464]

---

packages/core/app-layout/src/components/sidebar/AppSidebar.vue

Fix the mobile check for autoexpand of groups.
Part of [KHCP-17790](https://konghq.atlassian.net/browse/KHCP-17790).
[KHCP-17790]: https://konghq.atlassian.net/browse/KHCP-17790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(app-sidebar): mobile check [khcp-17790]

---

packages/analytics/analytics-geo-map/src/components/AnalyticsGeoMap.vue

Fix [MA-4081](https://konghq.atlassian.net/browse/MA-4081)
This will change the font-family in the analytics geo map to match our standard.
[MA-4081]: https://konghq.atlassian.net/browse/MA-4081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(analytics): update the font-family in geo map [MA-4081]

---

packages/analytics/analytics-geo-map/src/components/AnalyticsGeoMap.vue
packages/analytics/analytics-geo-map/src/components/MapLegend.vue
packages/analytics/analytics-geo-map/src/composables/index.ts
packages/analytics/analytics-geo-map/src/composables/useMetricUtils.spec.ts
packages/analytics/analytics-geo-map/src/composables/useMetricUtils.ts

Just the legend portion of https://konghq.atlassian.net/browse/MA-4194 
- Move legend to the top right
- Update legend style to match figma
- Move legend to its own component
- Move legend/metric range related utilities to composable + add unit test

fix: update legend styles
