Kong/public-ui-components

- packages/portal/spec-renderer/README.md
- packages/portal/spec-renderer/package.json
- packages/portal/spec-renderer/sandbox/App.vue
- packages/portal/spec-renderer/src/components/SpecRenderer.vue
Remove `slimMode` since we have `spec-renderer-mini` instead.
> fix(spec-renderer): remove slimMode

- packages/portal/spec-renderer-mini/README.md
- packages/portal/spec-renderer-mini/sandbox/App.vue
- packages/portal/spec-renderer-mini/src/components/SpecItem.vue
- packages/portal/spec-renderer-mini/src/components/SpecRendererMini.vue
- packages/portal/spec-renderer-mini/src/types/specs.ts
Fit & finish for `spec-renderer-mini`.
Addresses [KHCP-5769](https://konghq.atlassian.net/browse/KHCP-5769).
Includes:
- style updates
- new prop `tags`
- documentation updates
[KHCP-5769]: https://konghq.atlassian.net/browse/KHCP-5769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(spec-renderer-mini): fit & finish [khcp-5769]

- packages/portal/spec-details/README.md
- packages/portal/spec-details/package.json
- packages/portal/spec-details/sandbox/App.vue
- packages/portal/spec-details/src/components/SpecDetails.vue
- packages/portal/spec-details/src/swagger-ui-web-component.d.ts
- packages/portal/spec-details/src/types/index.ts
- packages/portal/swagger-ui-web-component/package.json
- packages/portal/swagger-ui-web-component/src/element.js
- packages/portal/swagger-ui-web-component/src/register.js
- packages/portal/swagger-ui-web-component/src/styles/essentialsOnly.css
- packages/portal/swagger-ui-web-component/src/styles/overrides.css
- packages/portal/swagger-ui-web-component/src/utils.js
- packages/portal/swagger-ui-web-component/webpack.config.js
- pnpm-lock.yaml
* Add `activeOperation` prop to spec-details
* Add `showOperation`, `hideOperation`, and `scrollToOperation` public methods to swagger-ui-web-component
* Fix spec-details types
> feat(spec-details): add activeOperation property

- packages/portal/spec-details/src/components/SpecDetails.vue
- packages/portal/swagger-ui-web-component/src/element.js
Enables View Raw, and Register button
This is done by firing a custom event which is listened to in the portal client application. 
works with with https://github.com/Kong/khcp/pull/5632
> feat(swagger-ui): add fire event on button presses TDX-2778

- packages/portal/spec-renderer/package.json
- packages/portal/spec-renderer/src/components/SpecOperationsList.vue
Fixes:
- issue where previous items weren't cleared when regenerating the list of operations
- bump package version to `0.4.0` since we already had version up to `0.3.2` of a different component (renamed) using this package name
> fix(spec-operations-list): misc fixes

- .github/workflows/ci.yaml
And when there are no UT found - exclude package from  `test:unit` even when package is changed.
> fix: [KHCP-5864] running unit tests only in packages where unit tests are present.

- packages/portal/swagger-ui-web-component/src/element.js
This removes the CSS `contains: content` on the web-component root div. Having this prevented the modal for "authorize from displaying fixed backdrop over the whole page. 
It's possible that this has some wider ramifications, and breaks some other styles/functionality. I did not see any as far I could tell.
> feat(swagger-ui-web-comp): remove css contains [TDX-2278]

- packages/portal/document-viewer/src/components/nodes/Blockquote.vue
- packages/portal/document-viewer/src/components/nodes/Text.vue
- packages/portal/document-viewer/src/components/renderChildren.tsx
- packages/portal/document-viewer/src/types/index.ts
Adds spaces between nested text in paragraphs for the document viewer, along with some styling fixes.
> fix(document-viewer): add spaces between nested text in paragraphs

- .github/workflows/pr-closed.yml
We do not want PR comments referencing preview packages in closed PRs. Those previews are unpublished or deprecated, so no reason to keep those reference comments around
> fix: [KHCP-6076] remove PR preview comment when closing PR

- packages/portal/document-viewer/src/types/index.ts
- packages/portal/document-viewer/src/utils/addUniqueHeadingSlugs.ts
If a heading node was in the markdown JSON without any text in the children, the `toSlug` could fail trying to call methods on undefined
> fix(document-viewer): use default text for slug if there is no text

- packages/portal/spec-renderer/src/components/SpecOperationsList.cy.ts
- packages/portal/spec-renderer/src/components/SpecOperationsList.vue
- packages/portal/spec-renderer/src/components/SpecRenderer.vue
Essentially, we need a way to deselect an item from a parent component. This does it by passing it as a prop and listening for changes.
I will note that I tried to add a test for this, but ran into problems with changing properties _after_ mount. If anyone has some hot tips, I'm happy to add a test!
> feat(portal): update spec renderer to listen for "deselect"

- packages/core/cli/src/__template__/README.md
- packages/core/cli/src/__template__/src/components/Template.cy.ts
- packages/core/misc-widgets/LICENSE
- packages/core/misc-widgets/README.md
- packages/core/misc-widgets/package.json
- packages/core/misc-widgets/sandbox/App.vue
- packages/core/misc-widgets/sandbox/index.html
- packages/core/misc-widgets/sandbox/index.ts
- packages/core/misc-widgets/sandbox/tsconfig.json
- packages/core/misc-widgets/src/components/github-star/GithubStar.cy.ts
- packages/core/misc-widgets/src/components/github-star/GithubStar.vue
- packages/core/misc-widgets/src/components/github-star/README.md
- packages/core/misc-widgets/src/components/index.ts
- packages/core/misc-widgets/src/composables/index.ts
- packages/core/misc-widgets/src/composables/useI18n.ts
- packages/core/misc-widgets/src/global-components.d.ts
- packages/core/misc-widgets/src/index.ts
- packages/core/misc-widgets/src/locales/en.json
- packages/core/misc-widgets/src/types/index.ts
- packages/core/misc-widgets/tsconfig.build.json
- packages/core/misc-widgets/tsconfig.json
- packages/core/misc-widgets/vite.config.ts
- pnpm-lock.yaml
Create a new `@kong-ui-public/misc-widgets` package that can house one-off components that aren't complex and a standalone package is not necessary.
This PR also adds the Github Star component to the `misc-widgets` package. 
https://konghq.atlassian.net/browse/KHCP-6075
> feat(misc-widgets): create new package

- packages/portal/document-viewer/src/components/DocumentViewer.vue
Previously, `!!{}` would default to true so it would attempt to render the children (which would be empty) if an empty object is passed. This change would update the check on the document being passed, and then display an error message.
> fix(document-viewer): properly check if empty object is passed

- packages/core/i18n/README.md
- packages/core/i18n/sandbox/App.vue
- packages/core/i18n/sandbox/index.ts
- packages/core/i18n/sandbox/locales/en.json
- packages/core/i18n/src/Translation.spec.ts
- packages/core/i18n/src/Translation.ts
- packages/core/i18n/src/index.ts
Now `i18n-t` can be used can be used from component libraries without it being registered via plugin on application level.
> feat: [KHCP_6176] Expose i18n Translation component for import without Vue plugin

- packages/core/misc-widgets/sandbox/App.vue
- packages/core/misc-widgets/sandbox/index.ts
- packages/core/misc-widgets/src/components/github-star/GithubStar.cy.ts
- packages/core/misc-widgets/src/components/github-star/GithubStar.vue
- packages/core/misc-widgets/src/components/github-star/README.md
- packages/core/misc-widgets/src/locales/en.json
https://konghq.atlassian.net/browse/KHCP-6183
Adds a new tooltip text prop for the GitHub Star component that accepts a string to display a KTooltip when hovered. 
The default text reads, "Star this repository on Github".
> feat(githubStar): add tooltipText prop to GitHub Star component [KHCP-6183]

- packages/portal/swagger-ui-web-component/README.md
- packages/portal/swagger-ui-web-component/package.json
- packages/portal/swagger-ui-web-component/public/index.html
- packages/portal/swagger-ui-web-component/public/petstore_v3.json
- packages/portal/swagger-ui-web-component/webpack.config.js
- pnpm-lock.yaml
Bumping to fix some styling, and changing the port this runs on to `5173`, to be consistent with the other packages and not to conflict with some ports if you have `khcp` running.
> chore: bump swagger ui kong theme + refactor

- packages/portal/document-viewer/fixtures/markdown-data.ts
- packages/portal/document-viewer/src/utils/addUniqueHeadingSlugs.ts
The logic wasn't considering elements that had nested headings - this updates the logic to do so. It also keeps proper count of the unique slugs now, as it was not previously. Additionally updated the example spec file.
> fix(document-viewer): add unique ids to nested headings

- packages/portal/document-viewer/src/components/DocumentViewer.cy.ts
- packages/portal/document-viewer/src/components/nodes/Code.vue
- packages/portal/document-viewer/src/components/nodes/CodeBlock.vue
- packages/portal/document-viewer/src/components/nodes/Heading.vue
- packages/portal/document-viewer/src/components/nodes/Image.vue
- packages/portal/document-viewer/src/components/nodes/ListItem.vue
`CodeBlock` was only escaping characters that would be tags for html language, but changed that logic to apply to all code. Also refactored the `Image` component to not render as a figure, and remove the `<figcaption>`. 
Includes various styling fixes
> fix(document-viewer): allow codeblocks to render xml and fix image tags (TDX-2917) (TDX-2920)

- packages/portal/spec-renderer/docs/spec-operations-list.md
- packages/portal/spec-renderer/src/components/operations-list/OperationsListItem.vue
Adds a few more variables to the `spec-operations-list` so that we are able to support a dark mode in portal.
> feat(operations-list): add more css variables to support dark mode (TDX-2928)

- packages/portal/swagger-ui-web-component/package.json
- pnpm-lock.yaml
> fix: bump package of swagger-ui-kong-theme for dark theme (TDX-2928)

- packages/portal/swagger-ui-web-component/package.json
- pnpm-lock.yaml
Bumps version of swagger ui kong theme for the web component.
> fix(swagger-ui-web-component): bump package version

- packages/core/app-layout/docs/sidebar.md
- packages/core/app-layout/sandbox/pages/LayoutPage.vue
- packages/core/app-layout/sandbox/pages/SidebarPage.vue
- packages/core/app-layout/src/components/AppLayout.cy.ts
- packages/core/app-layout/src/components/AppLayout.vue
- packages/core/app-layout/src/components/sidebar/AppSidebar.cy.ts
- packages/core/app-layout/src/components/sidebar/AppSidebar.vue
- packages/core/app-layout/src/components/sidebar/SidebarFooter.vue
Adds a new `footer` slot in the `AppSidebar.vue` component (exposed as the `sidebar-footer` slot in the `AppLayout.vue` component) in preparation for removing the sidebar profile menu and replacing it with the Geo Switcher.
If `footer` slot content is provided, it will override the `profile-items` and `profile-name` props, preventing the default sidebar footer with the profile menu from being rendered.
> feat(app-layout): add sidebar footer slot [KHCP-6623]

- packages/core/copy-uuid/README.md
- packages/core/copy-uuid/package.json
- packages/core/misc-widgets/README.md
- packages/core/misc-widgets/package.json
- pnpm-lock.yaml
Move i18n to peerDependencies in a few of the smaller packages
> fix(i18n): move to peer dependencies

- packages/analytics/metric-cards/src/components/MetricCardContainer.cy.ts
- packages/analytics/metric-cards/src/components/MetricCardContainer.vue
- packages/analytics/metric-cards/src/utilities/trend-display.ts
Detect divide-by-zero situations and show 0 instead of Infinity.
> fix(metric-cards): avoid showing Infinity in metrics cards

- packages/core/cli/src/__template__/src/index.ts
Comment out the Vue plugin export since we typically do not want to include it.
> chore(cli): remove vue plugin export

- package.json
- packages/core/app-layout/src/index.ts
- pnpm-lock.yaml
- renovate.json
Downgrade `vue-tsc` to version `1.2.0` to resolve built type errors stemming from version `1.2.1`
Link to opened issue: https://github.com/vuejs/language-tools/issues/2714
> fix(*): downgrade vue-tsc for type errors

- .github/workflows/ci.yaml
To resolve 
```
lerna ERR! Error: Command failed with exit code 128: git tag @kong-ui/entities-certificates@0.6.47 -m @kong-ui/entities-certificates@0.6.47
lerna ERR! fatal: tag '@kong-ui/entities-certificates@0.6.47' already exists
```
do not push anything from CI to remote till `publish` step is completed.
we use https://github.com/lerna/lerna/tree/main/libs/commands/version#--force-git-tag
> chore: do not create git tags until CI publishes packages [KHCP-7169]

- .github/actions/up-to-date/action.yml
- .github/workflows/ci.yaml
- Using `up-to-date` shared action to figure out if tests are needed on push
- each job in workflow takes a time to start and waits for free runner. so we can combine two jobs into one and shave all this time from the workflow run
> chore: using up-to-date from shared-actions. decreasing number of jobs [KHCP-7173]

- .github/workflows/ci.yaml
- cancel currently running workflow when PR branch receives a new commit and new workflow run is initiated
- when merging to main , wait for a new workflow to kick-off till previous workflow finishes
> chore: cancel concurrent CI on PR. Wait for job to finish in main [KHCP-7168]

- packages/portal/swagger-ui-web-component/package.json
- pnpm-lock.yaml
Bumps to latest version of `swagger-ui-kong-theme-universal`
> fix: bump swagger-ui-kong-theme-universal to 4.2.0

- renovate.json
- This way the only source of thought for npm settings for renovate is .npmrc file. 
- also locking renovate to pnpm 8.5.1. we do not want anymore surprises when new version of pnpm is released.
> fix: make renovate respect .npmrc settings. lock renovate to pnpm 8.5.1 [KHCP-7488]

- packages/core/app-layout/sandbox/pages/LayoutPage.vue
- packages/core/app-layout/src/components/AppLayout.vue
Update the `AppLayout` component layout:
- `.kong-ui-app-layout-content` changes to `align-content: stretch` instead of `flex-start`
- Adds a new child container `.kong-ui-app-layout-content > .kong-ui-app-layout-content-inner` to provide proper padding on the host app content.
> fix(app-layout): update layout content height

- packages/core/copy-uuid/README.md
- packages/core/copy-uuid/sandbox/App.vue
- packages/core/copy-uuid/sandbox/index.ts
- packages/core/copy-uuid/src/components/CopyUuid.cy.ts
- packages/core/copy-uuid/src/components/CopyUuid.vue
Add the ability to use tooltip text in place of events via the `tooltip` and `successTooltip` props.
> feat(copy-uuid): support tooltips instead of events

- vite.config.shared.ts
Enable sourcemaps when `BUILD_VISUALIZER` is set
> fix(sourcemaps): enable sourcemaps for visualizer [KHCP-7683]

- .github/workflows/cleanup-preview-packages.yaml
20 minutes was a little overkill 429 errors are not getting cleared. not enough time.
> fix: change schedule to run every 4 hours [KHCP-7461]

- .github/workflows/cleanup-preview-packages.yaml
cut & paste error.  was using wrong token for cleanup NPM packages.
> fix: use correct token for npm cleanup job [KHCP-7461]

- packages/analytics/analytics-chart/src/components/AnalyticsChart.cy.ts
- packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
Only time based charts were properly displaying the KEmptyState, because the hasMillisecondTimestamps check was failing (as expected).
However, Doughnut were displaying an empty div. Need to check for the presence of **1 or more records** in the array, since the blank `records` array is present regardless.
Bug:
> feat: fix(charts): empty state check [MA-1726]

- renovate.json
Enable dependency dashboard and grouping dev non-major dependencies into combined renovate PRs
https://konghq.atlassian.net/browse/KHCP-7899
> feat(renovate): enable dependency dashboard and dev package grouping [KHCP-7899]

- packages/portal/document-viewer/src/components/nodes/CodeBlock.vue
Resolves this [Datadog error](https://app.datadoghq.com/rum/error-tracking?query=%40application.id%3A6e430333-9e0f-4d6b-ac63-5f7d4ad9a641%20env%3Aprod%20-%40browser.name%3AHeadlessChrome%20%40issue.age%3A%3C%3D300000&issueId=4608d102-227b-11ee-9087-da7ad0900002&from_ts=1689362069000&to_ts=1689362369000&live=false)
> fix(document-viewer): handle empty props.lines [KHCP-8126]

- .github/workflows/ci.yaml
Fail CI if packages contain the wrong npm scope or `publishConfig.access` value.
> ci: guard against private scoped packages

- README.md
- docs/moving-packages.md
Add docs for moving packages between [`Kong/shared-ui-components`](https://github.com/Kong/shared-ui-components) and [`Kong/public-ui-components`](https://github.com/Kong/public-ui-components)
> docs: moving packages [KHCP-7979]

- packages/core/i18n/README.md
- packages/core/i18n/src/i18n.spec.ts
- packages/core/i18n/src/i18n.ts
- packages/core/i18n/src/types/index.ts
feat(i18n): add formatUnixTimeStamp and formatIsoDate to i18n [KHCP-7929] 
https://konghq.atlassian.net/browse/KHCP-7929
[KHCP-7929]: https://konghq.atlassian.net/browse/KHCP-7929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(i18n): add formatUnixTimeStamp and formatIsoDate to i18n [KHCP-7929]

- packages/core/copy-uuid/README.md
- packages/core/copy-uuid/package.json
- packages/core/copy-uuid/sandbox/App.vue
- packages/core/copy-uuid/src/components/CopyUuid.cy.ts
- packages/core/copy-uuid/src/components/CopyUuid.vue
BREAKING CHANGE: `isHidden` prop no longer available, now supports `format` prop to determine the uuid string display
Addresses:
[https://konghq.atlassian.net/browse/KHCP-8505](https://konghq.atlassian.net/browse/KHCP-8505)
> feat(copy-uuid): supports new prop - format [KHCP-8505]

- packages/entities/entities-consumer-credentials/LICENSE
- packages/entities/entities-consumer-credentials/README.md
- packages/entities/entities-consumer-credentials/docs/consumer-credential-list.md
- packages/entities/entities-consumer-credentials/fixtures/mockData.ts
- packages/entities/entities-consumer-credentials/package.json
- packages/entities/entities-consumer-credentials/sandbox/App.vue
- packages/entities/entities-consumer-credentials/sandbox/index.html
- packages/entities/entities-consumer-credentials/sandbox/index.ts
- packages/entities/entities-consumer-credentials/sandbox/pages/ConsumerCredentialListPage.vue
- packages/entities/entities-consumer-credentials/sandbox/pages/FallbackPage.vue
- packages/entities/entities-consumer-credentials/sandbox/pages/HomePage.vue
- packages/entities/entities-consumer-credentials/sandbox/tsconfig.json
- packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.cy.ts
- packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue
- packages/entities/entities-consumer-credentials/src/composables/index.ts
- packages/entities/entities-consumer-credentials/src/composables/useI18n.ts
- packages/entities/entities-consumer-credentials/src/consumer-credentials-endpoints.ts
- packages/entities/entities-consumer-credentials/src/global-components.d.ts
- packages/entities/entities-consumer-credentials/src/index.ts
- packages/entities/entities-consumer-credentials/src/locales/en.json
- packages/entities/entities-consumer-credentials/src/types/consumer-credential-list.ts
- packages/entities/entities-consumer-credentials/src/types/index.ts
- packages/entities/entities-consumer-credentials/tsconfig.build.json
- packages/entities/entities-consumer-credentials/tsconfig.json
- packages/entities/entities-consumer-credentials/vite.config.ts
- pnpm-lock.yaml
Adds `entities-consumer-credentials`. Verified [here](https://github.com/Kong/kong-admin/actions/runs/5817691170?pr=2842).
> feat(entitites): add `consumer-credentials` package

- packages/analytics/analytics-utilities/src/queryTime.spec.tz.ts
- packages/analytics/analytics-utilities/src/timeframes.ts
In the last few days of March, subtracting 1 from `Date.getMonth` will result in a March date rather than a February date.
> fix(timeframes): fix bug in previous month calculation [MA-1583]

- packages/analytics/analytics-metric-provider/package.json
- pnpm-lock.yaml
Make the link between `analytics-utilities` and `analytics-metric-provider` a workspace dep to help avoid type issues when the packages are used together.
> fix(deps): bump version of `analytics-utilities`

- .github/workflows/ci.yaml
- packages/entities/entities-upstreams-targets/src/components/UpstreamsForm.cy.ts
The `cy.wait()` will wait intercepted network events for 5 seconds by default. But in the CI environment, the
`['@getUpstream', '@fetchServices', '@fetchCertificates']` combination will took more than 4 seconds so the test will be flaky if it occasionally execeeds the 5 seconds limitation.
The slow part seems caused by the Cypress's vm hooks. It does not affect the component in development/production mode. So it's safe to loose the timeout to 10 seconds
This commit also fix the test results upload failure. The artifact name could not contains some special characters like `/`, which will occur in `matrix.container`. A new step is added to normalize the artifact name to make sure it can be uploaded successfully. (Verified [here](https://github.com/Kong/public-ui-components/actions/runs/58937 …
> test(entities-upstreams-targets): fix flaky tests and test results upload workflow

- packages/analytics/analytics-utilities/package.json
- packages/analytics/analytics-utilities/src/granularity.ts
- packages/analytics/analytics-utilities/src/queryTime.spec.tz.ts
- packages/analytics/analytics-utilities/src/queryTime.ts
- packages/analytics/analytics-utilities/src/timeframes.ts
- pnpm-lock.yaml
- Avoid breaking the API; `tz` is an optional param.
- Add many test cases.
> feat(queryTime): support doing calculations in a specific TZ [MA-1916]

- packages/portal/swagger-ui-web-component/src/element.js
The bug was because the div is not visible if the parent container is not open. This bug fix opens the parent container, which then allows us to select the operation that we want to find, and then scrolls to it.
> fix(swagger-ui-web-component): open section if collapsed for side nav (TDX-3313)

- packages/entities/entities-shared/src/components/permissions-wrapper/PermissionsWrapper.vue
Fixes an issue where `isAllowed` in `PermissionsWrapper` was not updated while the `auth-function` property was updated.
> fix(entities-shared): add missing watcher to permissions-wrapper

- packages/core/forms/src/generator/fields/advanced/FieldAutoSuggest.vue
- packages/entities/entities-plugins/docs/plugin-config-card.md
- packages/entities/entities-plugins/docs/plugin-list.md
- packages/entities/entities-plugins/fixtures/mockData.ts
- packages/entities/entities-plugins/package.json
- packages/entities/entities-plugins/sandbox/index.ts
- packages/entities/entities-plugins/src/components/PluginConfigCard.vue
- packages/entities/entities-plugins/src/components/PluginList.cy.ts
- packages/entities/entities-plugins/src/components/PluginList.vue
- packages/entities/entities-plugins/src/composables/usePluginMeta.ts
- packages/entities/entities-plugins/src/locales/en.json
- packages/entities/entities-plugins/src/types/plugin-list.ts
- packages/entities/entities-plugins/src/types/plugin.ts
- pnpm-lock.yaml
This PR enables `entities-plugins` to:
- display `Consumer Group` in the plugin list if a plugin is scoped to a consumer group
<p align=center><img width="700" alt="image" src="https://github.com/Kong/public-ui-components/assets/10095631/8baff5c3-2812-4337-bcbf-522c5b2c1689"></p>
- show `Consumer Group ID` in the plugin config card if the plugin is scoped to a consumer group
<p align=center><img width="700" alt="image" src="https://github.com/Kong/public-ui-components/assets/10095631/5db0bb9d-3f25-46ae-85ce-71f7fdb4db08"></p>
Also updates `FieldAutoSuggest` so that the plugin form can handle consumer group selection correctly. Note that consumer group selection needs to be handled in the host app.
> feat(plugins): support scoping for consumer groups

- packages/analytics/analytics-utilities/src/format.spec.tz.ts
- packages/analytics/analytics-utilities/src/format.ts
- packages/analytics/analytics-utilities/src/index.ts
- packages/analytics/analytics-utilities/src/queryTime.spec.tz.ts
- packages/analytics/analytics-utilities/src/specUtils.ts
- Refactor tests to allow using `runUtcTest` in more files.
- Add analytics-specific date format to analytics-utilities.
> feat(analytics-utilities): Add date formatting support [MA-1969]

- packages/analytics/analytics-chart/sandbox/App.vue
- packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
https://konghq.atlassian.net/browse/MA-2048
Only truncate the label when the legend grows such that it begins to wrap to multiple rows.
calculate the number of row in the grid layout, representing
the legend by comparing the "top" position of each item
incrementing the numberOfRows each time there is a difference.
Use the number of rows to determine if a label should be
truncated or not.
https://www.loom.com/share/c338d6643f9d4f46baf49de6245e468a
https://www.loom.com/share/bf2b6c0d7a03428ea290f3059fe6d01d
> fix(analytics-chart): better legend label truncation [MA-2048]

- packages/analytics/analytics-chart/README.md
- packages/analytics/analytics-chart/sandbox/App.vue
- packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
- packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
- packages/analytics/analytics-chart/src/components/chart-types/DoughnutChart.vue
- packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
- packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
- packages/analytics/analytics-chart/src/styles/chart.scss
https://konghq.atlassian.net/browse/MA-2055
- set the grid-column-template width based on the widest item
- implement a grid formatting function in order to better handle
dynamic sized legend items. Pure CSS was not enough to handle
both short as well as long legend labels.
- To avoid unecesarry calls to a potentially DOM-modifying function
only execute formatGrid() if the legend items have changed.
- Fixes and tweaks to styles for better readability and consistency
- Fix how chart width/height and legend/width height are set and maintained across all sub-components
> fix: adjust column width to prevent legend items from overlapping

- packages/analytics/analytics-chart/README.md
- packages/analytics/analytics-chart/sandbox/App.vue
- packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
- packages/analytics/analytics-chart/src/composables/useBarChartOptions.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToDatasets.spec.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToDatasets.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToTimeDatasets.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToTimedDatasets.spec.ts
- packages/analytics/analytics-chart/src/types/chart-data.ts
https://konghq.atlassian.net/browse/MA-2066
https://konghq.atlassian.net/browse/MA-2034
* Allow bar charts to be stacked/unstacked
* Update explore result --> chartJS dataset composable to detect and handle data with multiple metrics and one group-by dimension (group by dimension is inherently "time" for timeseries charts).
* Some unit tests for `useExploreResultToTimeDatasets` were not setting up the `meta` object properly. The `dataset` property in the meta object should have the dimensionName as a key, the value should be an array including all of the values present in the records for that dimensionName
Note - Metric axis title, chart title, tooltip title, as well as annotations enabled/disabled are provided by the consuming app. Any discrepancies seen in the sandbox for those aspects …
> feat: add support for multiple metrics

- packages/core/copy-uuid/sandbox/App.vue
- packages/core/copy-uuid/src/components/CopyUuid.cy.ts
- packages/core/copy-uuid/src/components/CopyUuid.vue
Add prop to support displaying custom text on hover of the `id` (does not affect existing tooltip support for the copy button).
> feat(copy-uuid): display tooltip on id hover

- packages/entities/entities-gateway-services/src/components/GatewayServiceConfigCard.vue
- packages/entities/entities-shared/src/composables/useHelpers.ts
When `tls_vefiry` is `null`, the displayed text should be `Use default system setting`.
> fix(service): `tls_verify` value in config card

- packages/entities/entities-gateway-services/src/components/GatewayServiceForm.cy.ts
- packages/entities/entities-gateway-services/src/components/GatewayServiceForm.vue
- packages/entities/entities-gateway-services/src/composables/getPortFromProtocol.ts
This PR fixes a bug where zero values are interpreted as `true`.
Before:
```ts
// when data.read_timeout is 0, the following evaluates to true
(data?.read_timeout || data?.read_timeout === 0) ?? 60000
```
After:
```ts
// when data.read_timeout is 0, the following evaluates to 0
(data?.read_timeout || data?.read_timeout === 0) ? data?.read_timeout : 60000
```
Fixes FTI-5437
> fix(service): interpreting 0 as a boolean true

- packages/entities/entities-plugins/src/components/PluginList.vue
- packages/entities/entities-plugins/src/locales/en.json
- packages/entities/entities-shared/docs/entity-base-table.md
- packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue
- packages/entities/entities-snis/src/components/SniList.vue
- packages/entities/entities-snis/src/locales/en.json
- packages/entities/entities-vaults/src/locales/en.json
Changes:
* Align vault and plugin delete modal titles by changing "Delete Plugin/Vault" to "Delete a Plugin/Vault", matching other entity modal titles.
* Correct typo in the SNI name placeholder.
* Introduce `disable-row-click` prop to `EntityBaseTable` for improved control over clickable row UI in the `KTable` component. The current implementation of `KTable` doesn't allow us to wrap it in other component while still keeping row clickable UI switchable
* Deactivate clickable UI for SNI list (no detail page for SNI entity).
* Prioritize displaying the plugin instance name over the plugin name in the delete modal.
> fix: enhance text consistency and SNI table UI

- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardDisplay.vue
This PR removes line links when format is `'yaml'`.
> fix(config-card-display): remove line links

- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.cy.ts
- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.vue
Update the tag prop on the `componentAttrsData` to match the tag which is now a `KTooltip`
> fix: lost data-testid on plaintext config card items

- .eslintrc.cjs
Enforce using `data-testid` and error if `data-test-id` is used.
> chore(eslint): enforce data-testid instead of data-test-id

- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.vue
> fix(*): tooltip label in config card item

- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.vue
This PR fixes a bug where a config car item value is wrapped inside two layers of KTooltip.
> fix(entities-shared): config card item tag

- packages/entities/entities-certificates/src/components/CertificateList.cy.ts
- packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTableCell.vue
This PR fixes a warning:
Because [`<KTooltip>`](https://kongponents.konghq.com/components/tooltip.html) does not have a `disabled` prop.
> fix(entities-shared): tooltip for the first column

- packages/analytics/analytics-chart/src/components/TopNTable.cy.ts
- packages/analytics/analytics-chart/src/components/TopNTable.vue
- packages/analytics/analytics-utilities/src/types/analytics-data.ts
- Remove union type for explore v3 display blob
- Remove shims for old display blob support
BREAKING CHANGE: removed support for old display blob style.
> refactor(TopN): remove support for old explore v3 format [MA-2094]

- packages/portal/spec-renderer/src/components/SpecRenderer.vue
Improves the error handling for when there is no spec. Uses `KEmptyState` instead
> feat(spec-renderer): utilize kemptystate for empty state

- packages/entities/entities-plugins/src/locales/en.json
- packages/entities/entities-vaults/src/components/VaultList.vue
- packages/entities/entities-vaults/src/locales/en.json
https://konghq.atlassian.net/browse/KHCP-9683
The good news is it affects only vaults and plugins
Tested Deploy Preview in khcp-ui: https://github.com/Kong/khcp-ui/pull/7120
> fix(vaults): fix delete modal for vault and plugin entities [khcp-9683]

- packages/core/forms/src/generator/FormGroup.vue
If `field.labelClasses` is undefined, before this PR:
After this PR:
> fix(forms): remove undefined class name

- packages/entities/entities-keys/docs/key-config-card.md
- packages/entities/entities-keys/docs/key-form.md
- packages/entities/entities-keys/sandbox/pages/KeyConfigCardPage.vue
- packages/entities/entities-keys/sandbox/pages/KeyFormPage.vue
- packages/entities/entities-keys/src/components/KeyConfigCard.vue
- packages/entities/entities-keys/src/components/KeyForm.cy.ts
- packages/entities/entities-keys/src/components/KeyForm.vue
- packages/entities/entities-keys/src/keys-endpoints.ts
Previously, `<KeyForm />` and `<KeyConfigCard />` interacted with the key entity by using a global scope endpoint for all operations.
This patch introduces the `keySetId` property, allowing these components to utilize keyset-scoped entity endpoints, aligning with the functionality already present in `<KeyList />`.
> fix(entities-keys): introduce `keySetId` prop to `<KeyForm />` and `<KeyConfigCard />`

- vite.config.shared.ts
Vite now respects the `pnpm-workspace.yaml` file so the `server.fs.allow` setting shouldn't be needed.
> chore: vite server setting

- packages/entities/entities-plugins/src/composables/usePluginMeta.ts
The Application Registration plugin can only be scoped to a service.
> fix(entities-plugins): app-registration plugin scope

- packages/entities/entities-plugins/src/locales/en.json
The empty state description for the `PluginList` is wrong. The PR updates it with the text from the original Figma mocks.
> fix(entities-plugins): empty state description

- packages/core/app-layout/src/components/AppLayout.vue
- packages/core/app-layout/src/components/sidebar/AppSidebar.vue
- packages/core/app-layout/src/constants.ts
- packages/core/app-layout/src/styles/_variables.scss
- packages/core/app-layout/src/styles/variables/_app-layout.scss
Adds a new `theme` prop that accepts `light` (default) or `dark` to modify the app layout background color.
> feat(app-layout): dark theme

- packages/entities/entities-plugins/src/components/PluginForm.vue
Fix `hint` text in custom schemas not being respected.
> fix(plugin/form): schema hint propagation

- packages/core/forms/package.json
- packages/core/forms/src/generator/FormGenerator.vue
- packages/core/forms/src/generator/fields/advanced/FieldArrayCardContainer.vue
- packages/core/forms/src/generator/fields/advanced/FieldArrayItem.vue
- packages/core/forms/src/generator/fields/advanced/FieldMetric.vue
- packages/core/forms/src/generator/fields/advanced/FieldObjectAdvanced.vue
- packages/entities/entities-shared/src/components/entity-filter/EntityFilter.vue
- pnpm-lock.yaml
Fix some style issues introduced by Kongponents alpha.
> fix(forms): misc style fix

- packages/entities/entities-shared/src/components/entity-filter/EntityFilter.vue
This PR fixes a style issue that the input width exceeds its container in the shared `EntityFilter`.
Before:
After:
> fix(entities-shared): filter input style

- packages/core/forms/src/generator/FormGenerator.vue
- packages/core/forms/src/generator/FormGroup.vue
- packages/core/forms/src/generator/fields/advanced/FieldKeyValuePairs.vue
- packages/core/forms/src/generator/utils/fieldsLoader.ts
- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-plugins/src/composables/plugin-schemas/RouteByHeader.ts
- packages/entities/entities-plugins/src/composables/useSchemas.ts
- packages/entities/entities-plugins/src/locales/en.json
- packages/entities/entities-plugins/src/types/plugin-form.ts
- packages/entities/entities-plugins/src/types/plugins/route-by-header.d.ts
- packages/entities/entities-plugins/src/types/plugins/shared.d.ts
This PR adds support for creating/editing the `route-by-header` plugin.
> feat(entities-plugins): support `route-by-header`

- packages/core/documentation/package.json
- packages/core/documentation/src/components/ProductDocumentModal.vue
- pnpm-lock.yaml
**Changes:**
- Updating the publish status toggle switch to be enabled by default, which matches current functionality in production.
- Bumps kongponents and fixes button styling
> fix(documentation): publish toggle should be enabled by default

- packages/entities/entities-plugins/src/components/select/PluginSelectCard.vue
- packages/entities/entities-plugins/src/components/select/PluginSelectGrid.vue
- packages/entities/entities-plugins/src/types/plugin.ts
This PR fixes the collapse states of plugin groups in the plugin select page.
Before:
<hr>
After:
> fix(entities-plugins): collapse status of plugin groups

- packages/entities/entities-certificates/src/components/CACertificateList.vue
- packages/entities/entities-certificates/src/components/CertificateList.vue
- packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue
- packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
- packages/entities/entities-consumers/src/components/ConsumerList.vue
- packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
- packages/entities/entities-key-sets/src/components/KeySetList.vue
- packages/entities/entities-keys/src/components/KeyList.vue
- packages/entities/entities-plugins/src/components/PluginList.vue
- packages/entities/entities-routes/src/components/RouteList.vue
- packages/entities/entities-snis/src/components/SniList.vue
- packages/entities/entities-upstreams-targets/src/components/TargetsList.vue
- packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
- packages/entities/entities-vaults/src/components/VaultList.vue
Fixes a bug where `hasData` will never be true after new entities are created: https://github.com/Kong/kong-admin/actions/runs/7053078914/job/19199527913?pr=3081.
> fix(*): create button visibility

- packages/analytics/analytics-chart/sandbox/pages/BarChartDemo.vue
- packages/analytics/analytics-chart/src/composables/useBarChartOptions.ts
- packages/analytics/analytics-chart/src/composables/useChartLegendValues.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToDatasets.spec.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToDatasets.ts
- packages/analytics/analytics-chart/src/types/dataset-generation-types.ts
- packages/analytics/analytics-chart/src/types/index.ts
Adding `0` to datasets as empty data rather than `null` was causing https://konghq.atlassian.net/browse/MA-2342 
When unstacking, ChartJS was allocating space in the canvas for the segments the `0`s represented. 
Setting empty values to null in the dataset, and setting `skipNull: true` in the chart options, solves the problem.
also, some housekeeping fixes
- move dataset generation to a function for code readability
- some sandbox tweaks
> fix(analytics-chart): do not add zero values to datasets [MA-2342]

- packages/portal/document-viewer/src/components/nodes/TableCell.vue
Adds line-height to code blocks that are inside table cells just so they do not overlap with each other.
> style(doc-viewer): add lineheight for code blocks in table cells (TDX-3667)

- cypress/support/commands.ts
The `findTestId` command wasn't supported chaining.
> test: fix findTestId command

- packages/entities/entities-consumers/src/components/ConsumerList.vue
- packages/entities/entities-consumers/src/locales/en.json
- packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
- packages/entities/entities-gateway-services/src/locales/en.json
- packages/entities/entities-plugins/src/components/PluginList.vue
- packages/entities/entities-plugins/src/locales/en.json
- packages/entities/entities-routes/src/components/RouteList.vue
- packages/entities/entities-routes/src/locales/en.json
- packages/entities/entities-shared/src/composables/tests/useFetchUrlBuilder.spec.ts
- packages/entities/entities-shared/src/composables/useFetchUrlBuilder.ts
Changes include:
* Add `/{query}/` back since kong manager and konnect have different query URL schema
* Display different placeholder for KM and konnect
> fix(useFetchUrlBuilder): fix exact match filter for kong manager

- packages/portal/swagger-ui-web-component/src/utils.js
Fixes an issue where the escaping pattern is not matched with how swagger-ui creates the id
> fix(swagger-ui-web-component): operationId

- packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
- packages/analytics/analytics-chart/src/composables/useBarChartOptions.ts
- packages/analytics/analytics-chart/src/types/chartjs-options.ts
- packages/analytics/analytics-chart/src/utils/constants.ts
https://konghq.atlassian.net/browse/MA-2409
Setting a specific Y-axis label font size so that chartjs avoids dropping every other label due to lack of space.
> feat: dynamic label font for axes [MA-2409]

- packages/core/app-layout/src/components/AppLayout.vue
Add bottom padding of `64px` to allow room for the infamous Intercom floating chat bubble.
> fix(app-layout): bottom padding for intercom

- packages/portal/swagger-ui-web-component/package.json
- packages/portal/swagger-ui-web-component/src/utils.js
- pnpm-lock.yaml
Fixes an issue where the escaping pattern is not matched with how swagger-ui creates the id
> fix(swagger-ui-web-component): operationId (#987)

- packages/core/forms/src/forms/ACMEForm.vue
- packages/core/forms/src/forms/OIDCForm.vue
- packages/core/forms/src/forms/schemas/ACMECommon.ts
- packages/core/forms/src/forms/schemas/OIDCAuth.js
- packages/core/forms/src/forms/schemas/OIDCCommon.js
- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-plugins/src/composables/plugin-schemas/JWT.ts
- packages/entities/entities-plugins/src/composables/plugin-schemas/Kafka.ts
- packages/entities/entities-plugins/src/composables/usePluginMeta.ts
- packages/entities/entities-plugins/src/composables/useSchemas.ts
- packages/entities/entities-plugins/src/types/plugin-form.ts
- packages/entities/entities-plugins/src/types/plugins/jwt.d.ts
This PR makes the plugin form use descriptions from backend schemas when descriptions are not defined in frontend schemas. It also fixes some current issues with tooltips.
Example: `request-validator`
|Before|After|
|-|-|
|<img width="550" alt="Screenshot 2023-12-20 at 13 58 47" src="https://github.com/Kong/public-ui-components/assets/5277268/6b6d27f1-9a34-4d2a-8562-685b0b79d14b">|<img width="499" alt="Screenshot 2023-12-20 at 14 00 12" src="https://github.com/Kong/public-ui-components/assets/5277268/a99f26c0-b496-4249-ad9f-8ee58c078a29">|
Example: `rate-limiting-advanced`
|Before|After|
|-|-|
|<img width="439" alt="Screenshot 2023-12-20 at 13 59 12" src="https://github.com/Kong/public-ui-components/assets/5277268/392fcda1-769e-49bd-8083-d2154b6e9744">|<img width="606" alt="Screenshot …
> fix(*): schema desc transformation in plugin forms

- packages/portal/document-viewer/src/components/nodes/CodeBlock.vue
- packages/portal/document-viewer/src/prismjs.d.ts
- tsconfig.json
The dynamic imports will never properly resolve in a host app; this PR introduces a list of supported languages for `CodeBlock` syntax highlighting.
```markdown
bash
css
docker
go
http
javascript
jq
json
log
lua
makefile
markdown
python
regex
rust
rest
scss
sql
typescript
yaml
xml-doc
```
> fix(document-viewer): syntax highlighting

- packages/core/forms/src/generator/fields/advanced/FieldAutoSuggest.vue
- packages/entities/entities-plugins/src/composables/plugin-schemas/StatsD.ts
Fixing two bugs:
- According to [the backend schema](https://github.com/Kong/kong-ee/blob/master/kong/plugins/statsd/schema.lua), the `StatsD` plugin does not have a `custom_identifier` sub-field in the `metrics` field. If a user types something in its input box and then submits the form, both Admin API and KoKo will throw an error: 
- With the latest vue version, AutoSuggest needs to manually emit the `model-updated` event (observed [here](https://github.com/Kong/kong-admin/actions/runs/7327128857/job/19953671476)). This is more like a temporary solution and we will revisit AutoSuggest when the KSelect reskin is done.
> fix(*): issues in plugin form

- packages/core/forms/src/forms/schemas/OIDCCommon.js
- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-plugins/src/composables/plugin-schemas/BasicAuth.ts
- packages/entities/entities-plugins/src/composables/plugin-schemas/HMAC.ts
- packages/entities/entities-plugins/src/composables/plugin-schemas/JWT.ts
- packages/entities/entities-plugins/src/composables/plugin-schemas/KeyAuthEnc.ts
- packages/entities/entities-plugins/src/composables/plugin-schemas/OAuth2.ts
In plugin forms, password inputs are used for encrypted fields. This PR changes them to text inputs.
> fix(entities-plugins): use plain text input for encrypted fields in forms

- packages/entities/entities-gateway-services/src/components/GatewayServiceForm.vue
Nested label will break the click reactivity. Since the radio font weight is default to 600 now, there is no need to wrap with nested `<label />` and set the `font-weight` explicitly.
> fix(entities-gateway-services): fix broken radio label

- packages/entities/entities-consumer-groups/docs/consumer-group-list.md
- packages/entities/entities-consumer-groups/sandbox/pages/ConsumerGroupListPage.vue
- packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.cy.ts
- packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
- packages/entities/entities-consumer-groups/src/types/consumer-group-list.ts
- packages/entities/entities-consumers/docs/consumer-list.md
- packages/entities/entities-consumers/sandbox/pages/ConsumerListPage.vue
- packages/entities/entities-consumers/src/components/ConsumerList.cy.ts
- packages/entities/entities-consumers/src/components/ConsumerList.vue
- packages/entities/entities-consumers/src/types/consumer-list.ts
Adding pagination support for `consumers/<id>/consumer_groups` and `consumer_groups/<id>/consumers` endpoints.
> feat(*): add pagination for consumers/<id>/consumer_groups and consumer_groups/<id>/consumers

- packages/entities/entities-plugins/src/components/PluginForm.cy.ts
- packages/entities/entities-plugins/src/components/PluginForm.vue
The submit button already has `saveFormData` as its click handler: https://github.com/Kong/public-ui-components/blob/76d87a0a2f176b0687f90b4511f210db2115feee/packages/entities/entities-plugins/src/components/PluginForm.vue#L83
So the form doesn't need a submit handler. Otherwise, in some circumstances, `saveFormData` will run twice when the submit button is clicked, e.g. https://github.com/Kong/kong-test-automation/actions/runs/7393902026/job/20114469588.
> fix(entities-plugins): remove click handler from submit button

- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-shared/src/index.ts
This PR fixes `@kong-ui-public/entities-plugins` package `dist/types` directory. The correct `dist/types` directory should look like this:
But currently it is:
This makes linting in consuming apps to fail: https://github.com/Kong/kong-admin/actions/runs/7415707930/job/20179347265.
This PR also makes the package smaller:
| -- | -- |
|<img width="409" alt="image" src="https://github.com/Kong/public-ui-components/assets/10095631/cf100576-73dc-433e-989d-f5959df3188d">|<img width="406" alt="image" src="https://github.com/Kong/public-ui-components/assets/10095631/863bfb04-62f4-4d23-9b46-971b8d644087">|
> fix(entities-plugins): package dist

- packages/core/documentation/src/components/DocumentationContent.vue
- packages/core/documentation/src/components/DocumentationDisplay.vue
- packages/core/documentation/src/locales/en.json
Add document download functionality to the `documentation` package.
> feat(documentation): add document download

- packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
Fixing a bug where the empty service list has no title for users without create permission.
> fix(entities-gateway-serviecs): empty list title when readonly

- packages/entities/entities-certificates/sandbox/pages/CACertificateFormPage.vue
- packages/entities/entities-certificates/sandbox/pages/CertificateFormPage.vue
- packages/entities/entities-certificates/src/components/CACertificateForm.vue
- packages/entities/entities-certificates/src/components/CertificateForm.vue
- packages/entities/entities-consumer-groups/sandbox/pages/ConsumerGroupFormPage.vue
- packages/entities/entities-consumer-groups/src/components/ConsumerGroupForm.vue
- packages/entities/entities-consumers/sandbox/pages/ConsumerFormPage.vue
- packages/entities/entities-consumers/src/components/ConsumerForm.vue
- packages/entities/entities-gateway-services/sandbox/pages/GatewayServiceFormPage.vue
- packages/entities/entities-gateway-services/src/components/GatewayServiceForm.vue
- packages/entities/entities-key-sets/sandbox/pages/KeySetFormPage.vue
- packages/entities/entities-key-sets/src/components/KeySetForm.vue
- packages/entities/entities-keys/sandbox/pages/KeyFormPage.vue
- packages/entities/entities-keys/src/components/KeyForm.vue
- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-routes/sandbox/pages/RouteFormPage.vue
- packages/entities/entities-routes/src/components/RouteForm.vue
- packages/entities/entities-shared/src/components/common/JsonCodeBlock.vue
- packages/entities/entities-shared/src/components/common/YamlCodeBlock.vue
- packages/entities/entities-snis/sandbox/pages/SniFormPage.vue
- packages/entities/entities-snis/src/components/SniForm.vue
- packages/entities/entities-upstreams-targets/sandbox/pages/UpstreamFormPage.vue
- packages/entities/entities-upstreams-targets/src/components/TargetForm.vue
- packages/entities/entities-upstreams-targets/src/components/UpstreamsForm.vue
- packages/entities/entities-vaults/sandbox/pages/VaultFormPage.vue
- packages/entities/entities-vaults/src/components/VaultForm.vue
https://konghq.atlassian.net/browse/KHCP-10152
Extracted preprocessing form fields logic in reusable helpers, for use in both JSON/YAML config forms and form submission
> feat(*): reuse preprocessing form fields for config forms and save [khcp-10152]

- packages/core/i18n/README.md
- packages/core/i18n/sandbox/App.vue
- packages/core/i18n/sandbox/locales/en.json
- packages/core/i18n/src/i18n.spec.ts
- packages/core/i18n/src/i18n.ts
Adds an ICU message format `datetime` format exactly the same as `formatIsoDate` for usage from within ICU files, making it easier to use a standard format within longer form texts such as:
```
I want a present {value, select, 
0 { for Christmas! }
undefined { for Christmas! }
other { on { value, date, datetime } } 
}
```
Replaces https://github.com/Kong/public-ui-components/pull/967 along with additional README edits.
> feat: add ICU datetime date format

- packages/entities/entities-gateway-services/src/components/GatewayServiceForm.cy.ts
- packages/entities/entities-gateway-services/src/components/GatewayServiceForm.vue
https://konghq.atlassian.net/browse/KHCP-10152
Fixes bug `GatewayServiceForm` where json/yaml blocks are empty in https://github.com/Kong/public-ui-components/pull/1080
Verified unique name constraint is still enforced
Deploy Preview https://pr-7419--khcp-ui.cloud-preview.konghq.tech/
> fix(gatewayServicesForm): not use computed in gateway service form [khcp-10152]

- packages/entities/entities-plugins/src/composables/usePluginMeta.ts
This pull request enables more plugins to consumer groups:
1. rate-limiting
2. ip-restriction 
3. request-termination
4. proxy-cache
5. proxy-cache advanced
KAG-3449
> feat(entities-plugins): enable more plugins to consumer groups

- packages/analytics/analytics-chart/sandbox/pages/BarChartDemo.vue
- packages/analytics/analytics-chart/sandbox/pages/TimeSeriesChartDemo.vue
- packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
- packages/analytics/analytics-chart/src/utils/commonOptions.ts
https://konghq.atlassian.net/browse/MA-2457
Issue: Legend items only rendering with one item per row when there's definitely more room/ 
Fix: style tweaks, plus run the formatGrid() function on mounted and on resize (behind a debounce for performance) in order to consistently re-arrange the legend grid for the available space. 
> fix(analytics-chart): style tweaks

- packages/entities/entities-plugins/docs/plugin-form.md
- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-plugins/src/types/plugin-form.ts
Kong Manager OSS does not have consumer groups. So in its plugin forms, the consumer group scope should be hidden.
> feat(entities-plugins): add a prop to disable consumer group scope

- packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue
Now KTabs have a bottom margin, making it separated from base tables. As a result, base tables without top borders do not look right:
> fix(entities-shared): base tables should have top borders

- packages/core/app-layout/fixtures/sidebar-items.ts
- packages/core/app-layout/sandbox/pages/KongManagerLayoutExample.vue
- packages/core/app-layout/sandbox/pages/LayoutPage.vue
- packages/core/app-layout/sandbox/pages/SidebarPage.vue
- packages/core/app-layout/src/components/sidebar/AppSidebar.cy.ts
- packages/core/app-layout/src/components/sidebar/AppSidebar.vue
- packages/core/app-layout/src/components/sidebar/SidebarItem.vue
- packages/core/app-layout/src/types/sidebar.ts
Change the sidebar item 'icon' prop to accept a component instance rather than a KIcon name string.
**BREAKING CHANGE**: The SidebarPrimaryItem 'icon' property now accepts a component instance rather than a KIcon name string.
```html
<template>
<AppLayout
:sidebar-top-items="sidebarItemsTop"
>
</template>
<script setup lang="ts">
import { PeopleIcon } from '@kong/icons'
const sidebarItemsTop = computed((): SidebarPrimaryItem[] => {
return [
{
name: 'Organization',
to: '/global/organization',
key: 'organization',
icon: PeopleIcon, // New usage: pass the `@kong/icons` icon component instance directly to the object
},
]
})
</script>
```
```html
<template>
<AppLayout
:sidebar-top-items="sidebarItemsTop"
>
</template>
<script setup lang="ts">
const sidebarItemsTop = computed((): …
```
> feat(app-layout): use dynamic component for sidebar icons [KHCP-10350]

- packages/core/app-layout/README.md
- packages/core/app-layout/docs/sidebar.md
- packages/core/app-layout/fixtures/sidebar-items.ts
- packages/core/app-layout/sandbox/pages/KongManagerLayoutExample.vue
- packages/core/app-layout/sandbox/pages/LayoutPage.vue
- packages/core/app-layout/sandbox/pages/SidebarPage.vue
- packages/core/app-layout/src/components/AppLayout.vue
- packages/core/app-layout/src/components/sidebar/AppSidebar.cy.ts
- packages/core/app-layout/src/components/sidebar/AppSidebar.vue
- packages/core/app-layout/src/components/sidebar/SidebarItem.vue
- packages/core/app-layout/src/types/sidebar.ts
You must now slot in the sidebar icons rather than passing them in via slot.
BREAKING CHANGE: The AppLayout and AppSidebar components now require slotting in the sidebar icons via sidebar-icon-KEY slots.
```html
<template>
<AppLayout :sidebar-top-items="sidebarItemsTop">
<template #sidebar-icon-overview>
<OverviewIcon :size="KUI_ICON_SIZE_40" />
</template>
</AppLayout>
</template>
<script setup lang="ts">
import { OverviewIcon } from '@kong/icons'
import { KUI_ICON_SIZE_40 } from '@kong/design-tokens'
const sidebarItemsTop = [
{
key: 'overview',
name: 'Overview',
to: '/sidebar/?overview',
},
]
</script>
```
> feat(app-layout): sidebar icon slots

- packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
Show full legend item label text on hover regardless of chart orientation
https://kongstrong.slack.com/archives/C01RF6STU2F/p1706307888384229
> fix(analytics-chart): full legend label text on hover in all positions

- package.json
- packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue
- pnpm-lock.yaml
- vite.config.shared.ts
Add the new Vite plugin Vue DevTools
For our host apps that utilize KToaster, you will likely need to switch the active app in the DevTools
1. Click the Vue icon at the top-left of the DevTools
2. Click "App 1" dropdown, and select "App 2"
> chore(vue-devtools): add vue devtools

- packages/core/app-layout/src/components/pageHeader/AppPageHeader.vue
Provide a fallback for the `AppPageHeader` title prop to prevent prop validation errors when the component is on a page in the process of changing routes/determining the title.
> fix(app-page-header): provide title fallback

- packages/entities/entities-vaults/docs/vault-form.md
- packages/entities/entities-vaults/sandbox/pages/VaultFormPage.vue
- packages/entities/entities-vaults/src/components/VaultForm.vue
- packages/entities/entities-vaults/src/locales/en.json
- packages/entities/entities-vaults/src/types/vault-form.ts
For the HCV provider:
- Adding support for `approle` auth method
- Adding the missing `kube_auth_path` field which should have been added for Kong Gateway 3.5
> feat(entities-vaults): add approle method support

- packages/analytics/analytics-chart/sandbox/pages/BarChartDemo.vue
- packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
- packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
Make units reactive.
Fix some spacing issue when the legend is vertical (right) 
https://konghq.atlassian.net/browse/MA-2568
> fix: tooltip units were not reactive on timeseries charts

- CODEOWNERS
- packages/core/documentation/docs/DocumentationContent/README.md
- packages/core/documentation/src/components/DocumentationContent.vue
Adds an optional prop (defaulted to false) to wrap the documentation empty state with a KCard. This provides the ability to align empty state designs across Konnect.
> feat(documentation): add prop to wrap empty state in a KCard

- packages/core/app-layout/sandbox/pages/LayoutPage.vue
- packages/core/app-layout/src/components/sidebar/AppSidebar.vue
- packages/core/app-layout/src/styles/variables/_app-sidebar.scss
Fix the sidebar items from being cut off when expanded (notice the right edge)
> fix(app-layout): sidebar overflow

- packages/entities/entities-plugins/src/components/PluginSelect.vue
Remove the logic that prevents users from adding duplicate plugins of the same type to the same entity. We need to support creating multiple plugins of the same type for `consumers`/`consumer_groups` to allow scoping to multiple entities simultaneously (ie. I can create a plugin scoped to a specific `consumer_group`/`route` and have a different configuration for the same plugin when it's scoped to a specific `consumer_group`/`gateway-service` correctly).
Addresses [KHCP-10683](https://konghq.atlassian.net/browse/KHCP-10683).
[KHCP-10683]: https://konghq.atlassian.net/browse/KHCP-10683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(plugins): allow creating dup plugins [khcp-10683]

- packages/core/core/src/useAxios/index.ts
Wrap the `inject` axios instance with try/catch to provide a fallback instance if the `getAxiosInstance` method is called outside of the setup function.
> fix(core): catch an improper inject and provide fallback

- packages/analytics/analytics-utilities/package.json
- packages/analytics/analytics-utilities/src/timeframes.spec.ts
- packages/analytics/analytics-utilities/src/timeframes.ts
- packages/analytics/analytics-utilities/src/types/explore-v4.ts
- packages/analytics/analytics-utilities/src/types/timeframe-options.ts
- Bump version to 1.0.0; no breaking changes
- Add cacheKey method for improved usage with SWRV
- Add v4Query method for better explore v4 support
- Fix types
> feat(utilities): add new timeframe methods [MA-1960]

- packages/core/app-layout/src/components/sidebar/AppSidebar.vue
If a user chooses different options in their MacOS `Appearance > Show scroll bars` setting, it impacts the width and padding of the sidebar container.
This 💩 PR adjusts the padding of the scroll container based on a hidden element's rendered scrollbar width.
> fix(app-layout): sidebar scroll container padding

- packages/analytics/dashboard-renderer/src/components/layout/GridLayout.vue
Because cells are absolutely positioned, it's a bit more complicated to have the cells
start/end at the margins of the layout itself, while maintaining a gap betwen cells
In order to do this, the width of each cell needs to be increased by a fraction of the gap size
proportional to the number of tiles present in that row
Each cell then needs to be translated an additional fraction of the gap size based on its position
in the row
> fix: spacing issues in grid layout

- packages/entities/entities-plugins/src/components/PluginSelect.cy.ts
- packages/entities/entities-plugins/src/components/select/PluginSelectGrid.vue
We should still show custom plugins in KM, just not in a separate tab.
> fix(entities-plugins): custom plugins are hidden in select page for KM

- packages/analytics/analytics-chart/src/components/AnalyticsChart.cy.ts
- packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
- packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
- packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
- packages/analytics/analytics-chart/src/composables/useBarChartOptions.ts
- packages/analytics/analytics-chart/src/composables/useLineChartOptions.ts
- packages/analytics/analytics-chart/src/styles/chart.scss
- packages/analytics/dashboard-renderer/src/components/BarChartRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
- packages/analytics/dashboard-renderer/src/components/TimeseriesChartRenderer.vue
- packages/analytics/metric-cards/src/components/display/MetricsCard.vue
https://konghq.atlassian.net/browse/MA-2536
> fix(analytics-chart): chart height, legend padding, y-axis hover [MA-2536]

- packages/analytics/dashboard-renderer/sandbox/index.html
- packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
- packages/analytics/dashboard-renderer/src/components/BarChartRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue
- packages/analytics/dashboard-renderer/src/components/TimeseriesChartRenderer.vue
- packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts
- Add padding inside of tiles
- Allow providing a chart title for analytics charts
- Remove `showAnnotations` property since annotations are not currently supported
- Properly pass down synthetics data key
> fix(dashboards): improve styling; fix properties [MA-2648]

- packages/core/core/src/useAxios/index.ts
There's a warning if we don't provide `get-axios-instance` in the host app:
We need to explicitly provide a default value to clear the warning: https://github.com/vuejs/core/blob/89de26cdcdddef8096417ea494de113399629d5b/packages/runtime-core/src/apiInject.ts#L68
> fix(core): provide a default value for axios injection

- packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue
When encrypted fields are successfully copied, their values should be hidden from the toast.
> fix(entities-consumer-credentials): hide encrypted fields in toast

- packages/analytics/analytics-chart/sandbox/pages/BarChartDemo.vue
- packages/analytics/analytics-chart/sandbox/pages/ChartDemoSimple.vue
- packages/analytics/analytics-chart/src/components/TopNTable.vue
- packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
- packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
- packages/analytics/analytics-chart/src/styles/chart.scss
- packages/analytics/dashboard-renderer/package.json
- packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- packages/analytics/dashboard-renderer/src/components/TopNTableRenderer.vue
- packages/analytics/dashboard-renderer/src/components/layout/GridLayout.vue
- packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts
add optional prop to hide the default border on TopNTable
dynamically set the hight of the horizontal legend based on if there needs to be
more than one row or not.
Only need to allocate space for one row if there's only one row.
If there's more than one row, allocate space for 2 rows, the rest overflows.
Set the chart-container hight to 100% - 80px to account for the legend + chart title
when chart and legend is stacked
https://konghq.atlassian.net/browse/MA-2637
>  feat(dashboard-renderer): add TopN table support to dashboard renderer

- packages/analytics/analytics-metric-provider/src/components/MetricsConsumer.vue
- packages/analytics/analytics-metric-provider/src/components/MetricsProviderInternal.vue
- packages/analytics/analytics-metric-provider/src/components/metricsProviderUtil.ts
- packages/analytics/analytics-metric-provider/src/composables/useMetricFetcher.spec.ts
- packages/analytics/analytics-metric-provider/src/composables/useMetricFetcher.ts
- packages/analytics/analytics-metric-provider/src/locales/en.json
- Attempt to move away from `timeframeLength`; use the response coming back from the server.
- Use `withTrend` option to determine whether a trend was queried or not.
- Properly pluralize 'previous day' / 'previous N days'
> fix(metric-cards): determine trend range text from response [MA-2650]

- packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
- packages/analytics/dashboard-renderer/src/components/QueryDataProvider.vue
- packages/analytics/dashboard-renderer/src/components/TimeseriesChartRenderer.vue
- packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts
- Don't stack timeseries charts by default.
- If a timeseries chart is stacked, it should also be filled.
- Don't autorefresh charts on the dashboard.
> fix(dashboard-renderer): tweak default options [MA-2709]

- packages/entities/entities-plugins/src/components/PluginEntityForm.vue
- packages/entities/entities-plugins/src/composables/useSchemas.ts
- packages/entities/entities-plugins/src/types/plugin-form.ts
- packages/entities/entities-plugins/src/types/plugins/oas-validation.d.ts
Currently we have an `<input>` element for the `api_spec` field, making it impossible to input a JSON/YAML format spec:
After this PR:
> fix(entities-plugins): spec input for OAS

- packages/entities/entities-shared/src/composables/tests/useFetchUrlBuilder.spec.ts
- packages/entities/entities-shared/src/composables/useFetchUrlBuilder.ts
- packages/entities/entities-shared/src/types/app-config.ts
- packages/entities/entities-upstreams-targets/docs/upstreams-list.md
Ticket: https://konghq.atlassian.net/browse/KHCP-11054
Update `useFetchUrlBuilder` to allow using exact match search on upstream list from konnect.
[slack](https://kongstrong.slack.com/archives/C03LRB400TC/p1709217149772489?thread_ts=1709216110.973549&cid=C03LRB400TC): 
Upstreams are not being served from Kanalytics/Open Search. We are still hitting Koko for upstream.
In this case, the upstream page should be using the old way of getting by name/id not the filter call
> fix(entities-shared): update useFetchUrlBuilder to allow exact match search from host app. [KHCP-11054]

- packages/entities/entities-plugins/src/components/PluginSelect.vue
Make sure query params are peristed when changing tabs.
Fixes [KHCP-11068](https://konghq.atlassian.net/browse/KHCP-11068).
`konnect-ui-apps` [PR](https://github.com/Kong/konnect-ui-apps/pull/2661) and Preview:
https://pr-2661--gateway-manager.cloud-preview.konghq.tech/gateway-manager
Verification steps:
1. Create a custom plugin
2. Go to Routes -> view a specific route's details -> Plugins -> Click `+ New Plugin`
3. Notice the entity_type/entity_id query params in the URL
4. Click the Custom Plugins tab
5. Ensure the entity_type/entity_id query params are still in the URL
6. Click a custom plugin to create an instance of it
Expected:
The scope selection in the plugin form should be hidden and it should be scoped automatically to the current route upon creation.
- [Creating a package …
> fix(plugins): persist query params on tab change [khcp-11068]

- packages/core/forms/src/generator/FormGenerator.vue
- packages/entities/entities-plugins/docs/plugin-form.md
- packages/entities/entities-plugins/sandbox/pages/PluginFormPage.vue
- packages/entities/entities-plugins/src/components/PluginEntityForm.vue
- packages/entities/entities-plugins/src/components/PluginForm.cy.ts
- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-plugins/src/composables/useSchemas.ts
- packages/entities/entities-plugins/src/locales/en.json
- packages/entities/entities-plugins/src/types/plugin-form.ts
Add an optional feature to group plugin configuration fields into _Common Fields_, _Required Fields_, and _Advanced Fields_ sections in the unified plugin form component. Fields under each section are sorted by their alphabetical order.
**This feature is disabled by default** and can be enabled by setting `config.groupFields` to `true`.
KM-21
> feat(entities-plugins): support field grouping [KM-21]

- packages/entities/entities-plugins/src/components/PluginForm.cy.ts
This PR reverts the `it.only` in tests 🫢
> test(entities-plugins): revert it.only

- packages/entities/entities-plugins/fixtures/mockData.ts
- packages/entities/entities-plugins/src/components/PluginForm.cy.ts
- packages/entities/entities-plugins/src/components/PluginForm.vue
Revert changes on the `required` field introduced by https://github.com/Kong/public-ui-components/pull/1224
Tries to fix the regression caught in https://github.com/Kong/konnect-ui-apps/actions/runs/8292322240/job/22693574891?pr=2669
> fix(entities-plugins): revert the changes on the required field

- packages/entities/entities-certificates/sandbox/pages/CACertificateFormPage.vue
- packages/entities/entities-certificates/sandbox/pages/CertificateFormPage.vue
- packages/entities/entities-consumer-groups/sandbox/pages/ConsumerGroupFormPage.vue
- packages/entities/entities-consumers/sandbox/pages/ConsumerFormPage.vue
- packages/entities/entities-gateway-services/sandbox/pages/GatewayServiceFormPage.vue
- packages/entities/entities-gateway-services/src/components/GatewayServiceForm.cy.ts
- packages/entities/entities-key-sets/sandbox/pages/KeySetFormPage.vue
- packages/entities/entities-keys/sandbox/pages/KeyFormPage.vue
- packages/entities/entities-plugins/sandbox/pages/PluginFormPage.vue
- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-routes/sandbox/pages/RouteFormPage.vue
- packages/entities/entities-shared/docs/entity-base-config-card.md
- packages/entities/entities-shared/docs/entity-base-form.md
- packages/entities/entities-shared/sandbox/pages/ConfigCardDisplayPage.vue
- packages/entities/entities-shared/sandbox/pages/EntityBaseFormPage.vue
- packages/entities/entities-shared/src/components/common/JsonCodeBlock.cy.ts
- packages/entities/entities-shared/src/components/common/JsonCodeBlock.vue
- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardDisplay.cy.ts
- packages/entities/entities-shared/src/components/entity-base-config-card/EntityBaseConfigCard.cy.ts
- packages/entities/entities-shared/src/components/entity-base-form/EntityBaseForm.cy.ts
- packages/entities/entities-shared/src/components/entity-base-form/EntityBaseForm.vue
- packages/entities/entities-shared/src/types/entity-base-config-card.ts
- packages/entities/entities-shared/src/types/entity-base-form.ts
- packages/entities/entities-snis/sandbox/pages/SniFormPage.vue
- packages/entities/entities-upstreams-targets/sandbox/pages/UpstreamFormPage.vue
- packages/entities/entities-vaults/sandbox/pages/VaultFormPage.vue
https://konghq.atlassian.net/browse/KHCP-9971
* konnect-ui-apps: https://pr-2720--gateway-manager.cloud-preview.konghq.tech/gateway-manager 
* khcp-ui: https://pr-7761--khcp-ui.cloud-preview.konghq.tech/
> feat(jsonYamlForms): remove json yaml milestone 2 ff for all entity forms post GA [KHCP-9971]

- packages/entities/entities-plugins/docs/plugin-select.md
- packages/entities/entities-plugins/sandbox/pages/PluginSelectPage.vue
- packages/entities/entities-plugins/src/components/PluginSelect.cy.ts
- packages/entities/entities-plugins/src/components/PluginSelect.vue
- packages/entities/entities-plugins/src/components/select/PluginSelectGrid.vue
- packages/entities/entities-plugins/src/components/select/PluginSelectGroup.vue
- packages/entities/entities-plugins/src/locales/en.json
- packages/entities/entities-plugins/src/types/plugin.ts
1. Expand each plugin group by default
2. Add an optional `highlightedPlugins` field to `plugin-select`'s `config` to specify highlighted plugins which will appear at the top of the list (show as a separate plugin group)
KM-18
> feat(entities-plugins): UX improvements on plugin select [KM-18]

- CODEOWNERS
add team-devx to codeowners for swagger-ui-web-component
> chore(codeowners): add team-devx to codeowners for swagger-ui-web-component

- packages/portal/spec-renderer/src/components/SpecDetails.vue
- packages/portal/swagger-ui-web-component/src/element.js
This is a Proof-of-Concept to attempt a fix to some issues in an [upstream repository](https://github.com/Kong/konnect-portal) (`konnect-portal`). The issue is that for client-side-only OIDC "Try It Out" authorization, one needs to be able to initialize oauth with certain values available.
For SPA-based requests to the `/authorize` endpoint, one needs to invoke the following (where `swaggerUI` is an instance that has already been initialized.
```typescript
swaggerUI.initOAuth({
usePkceWithAuthorizationCodeGrant: true,
additionalQueryStringParams: {
nonce: Math.random().toString(36).substring(7)
}
})
```
Rather than initializing that within `spec-renderer` (really within `swagger-ui-web-component`), I think the better move is to allow more flexibility and to expose `#instance` so that …
> refactor: expose swagger UI to enable OAuth2 try-it-out in upstream applications

- packages/analytics/analytics-chart/sandbox/pages/TimeSeriesChartDemo.vue
- packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
- packages/analytics/analytics-chart/src/components/chart-types/DoughnutChart.vue
- packages/analytics/analytics-chart/src/types/chart-data.ts
- packages/analytics/dashboard-renderer/src/components/TimeseriesChartRenderer.vue
https://konghq.atlassian.net/browse/MA-2659
fill is now controlled by the stacked prop
BREAKING CHANGE: removed the fill prop from chart options
> fix(analytics-chart): remove fill prop [MA-2659]

- packages/entities/entities-consumer-groups/src/components/ConsumerGroupForm.vue
- packages/entities/entities-consumer-groups/src/locales/en.json
- packages/entities/entities-gateway-services/src/components/GatewayServiceForm.cy.ts
- packages/entities/entities-gateway-services/src/components/GatewayServiceForm.vue
- packages/entities/entities-gateway-services/src/locales/en.json
- packages/entities/entities-shared/src/composables/index.ts
- packages/entities/entities-shared/src/composables/useValidators.ts
- packages/entities/entities-shared/src/index.ts
- packages/entities/entities-shared/src/locales/en.json
1. Adding a `useValidators` composable in `entities-shared` for future extension
2. Allow UTF-8 characters in `name` fields in gateway-services and consumer-groups
Previously:
Dependencies:
- https://github.com/Kong/koko-private/pull/3092
KM-55
> fix(entities-*): allow UTF-8 chars in some fields [KM-55]

- packages/entities/entities-plugins/src/components/PluginConfigCard.vue
- packages/entities/entities-plugins/src/components/PluginList.vue
- packages/entities/entities-plugins/src/composables/usePluginMeta.ts
Fixing issues while displaying icons for plugins with `imageName` overrides
KM-56
> fix(entities-plugins): icons with imageName overrides [KM-56]

- packages/entities/entities-plugins/fixtures/mockData.ts
- packages/entities/entities-plugins/src/components/PluginForm.cy.ts
- packages/entities/entities-plugins/src/components/PluginForm.vue
Support arrays of custom schema objects in custom plugins, e.g.
```json
{
"config":{
"fields":[
{
"parent_foo":{
"elements":{
"fields":[
{
"child_bar":{
"required":true,
"type":"string"
}
},
{
"child_baz":{
"default":true,
"type":"boolean"
}
}
],
"type":"record"
},
"type":"array"
}
}
],
"required":true,
"type":"record"
}
}
```
| - | - |
| <img width="1514" alt="image" src="https://github.com/Kong/public-ui-components/assets/10095631/d95749a0-5a8a-49af-bfbc-bc5da374b47d"> | <img width="1504" alt="image" src="https://github.com/Kong/public-ui-components/assets/10095631/2f64ff41-668b-4220-99ad-f9725a890e49"> |
This PR also fixes a bug where default values are not prefilled for arrays of objects, e.g. `session_redis_cluster_nodes` of the SAML plugin:
| - …
> feat(entities-plugins): support array fields in custom plugins

- package.json
- packages/analytics/analytics-chart/package.json
- packages/analytics/analytics-metric-provider/package.json
- packages/analytics/dashboard-renderer/package.json
- packages/analytics/metric-cards/package.json
- packages/core/app-layout/package.json
- packages/core/app-layout/sandbox/pages/PageHeaderPage.vue
- packages/core/app-layout/src/components/pageHeader/AppPageHeader.cy.ts
- packages/core/app-layout/src/components/pageHeader/AppPageHeader.vue
- packages/core/documentation/package.json
- packages/core/expressions/package.json
- packages/core/forms/package.json
- packages/core/misc-widgets/package.json
- packages/core/sandbox-layout/package.json
- packages/entities/entities-certificates/package.json
- packages/entities/entities-consumer-credentials/package.json
- packages/entities/entities-consumer-groups/package.json
- packages/entities/entities-consumers/package.json
- packages/entities/entities-gateway-services/package.json
- packages/entities/entities-key-sets/package.json
- packages/entities/entities-keys/package.json
- packages/entities/entities-plugins/package.json
- packages/entities/entities-routes/package.json
- packages/entities/entities-shared/package.json
- packages/entities/entities-snis/package.json
- packages/entities/entities-upstreams-targets/package.json
- packages/entities/entities-vaults/package.json
- packages/portal/document-viewer/package.json
- packages/portal/spec-renderer/package.json
- pnpm-lock.yaml
Jira: https://konghq.atlassian.net/browse/KHCP-11172
Phase 10 adoption of components reskinned in alpha version of Kongponents v9 release. Includes these components:
- `KTreeList`
- `KBreadcrumb`
- `KSkeleton`
- `KMenu` (removed)
> fix(*): kongponents alpha phase 10 [KHCP-11172]

- packages/analytics/analytics-metric-provider/sandbox/App.vue
- packages/analytics/analytics-metric-provider/src/components/MetricsConsumer.vue
- packages/analytics/analytics-metric-provider/src/components/MetricsProviderInternal.vue
- packages/analytics/analytics-metric-provider/src/components/metricsProviderUtil.ts
- packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
- packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue
- packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts
- packages/analytics/metric-cards/sandbox/App.vue
- packages/analytics/metric-cards/src/components/MetricCardContainer.cy.ts
- packages/analytics/metric-cards/src/components/MetricCardContainer.vue
- packages/analytics/metric-cards/src/components/display/MetricsCard.vue
- packages/analytics/metric-cards/src/types/metric-card.ts
https://konghq.atlassian.net/browse/MA-2726
Allows us to add a Golden Signals card title in a Dashboard definition.
https://pr-2819--gateway-manager.cloud-preview.konghq.tech/gateway-manager
https://pr-7818--khcp-ui.cloud-preview.konghq.tech/us/overview/
https://pr-7818--khcp-ui.cloud-preview.konghq.tech/us/analytics/summary
> feat(metric-card-container): add optional title [MA-2726]

- packages/analytics/analytics-metric-provider/src/components/MetricsConsumer.vue
- packages/analytics/analytics-metric-provider/src/components/MetricsProvider.cy.ts
- packages/analytics/analytics-metric-provider/src/components/MetricsProvider.vue
- packages/analytics/analytics-metric-provider/src/components/MetricsTestHarness.vue
- packages/analytics/analytics-metric-provider/src/components/metricsProviderUtil.ts
- packages/analytics/analytics-metric-provider/src/composables/useMetricFetcher.ts
- packages/analytics/analytics-metric-provider/src/locales/en.json
- packages/analytics/analytics-metric-provider/src/types/fetcher-types.ts
- packages/analytics/analytics-utilities/src/types/query-bridge.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
- packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue
- packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts
- Add new `evaluateFeatureFlagFn` to query bridge [MA-2738]
- Use feature flag to determine whether to query average latencies [MA-2739]
- Add override property to force querying percentile latencies [MA-2740]
[MA-2738]: https://konghq.atlassian.net/browse/MA-2738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MA-2739]: https://konghq.atlassian.net/browse/MA-2739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MA-2740]: https://konghq.atlassian.net/browse/MA-2740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(analytics): allow checking feature flags in bridge [MA-2738]

- packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
- packages/entities/entities-gateway-services/src/locales/en.json
- packages/entities/entities-plugins/src/components/PluginList.cy.ts
- packages/entities/entities-plugins/src/components/PluginList.vue
- packages/entities/entities-plugins/src/locales/en.json
This PR removes the label next to the `Enabled` switch for `GatewayServiceList` and `PluginList`.
`GatewayServiceList`:
`PluginList`:
KM-65
> fix(entities): remove the label next to the enabled switch

- packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue
Due to recent `KTable` changes, we need to explicitly set the toolbar width now:
| - | - |
| <img width="1443" alt="image" src="https://github.com/Kong/public-ui-components/assets/10095631/96a48fa8-5dc2-48a6-a26f-0d22af924036"> | <img width="1446" alt="image" src="https://github.com/Kong/public-ui-components/assets/10095631/57785783-3ccd-49bc-81cd-e39757466109"> |
> fix(entities-shared): table toolbar width

- packages/entities/entities-plugins/README.md
- packages/entities/entities-plugins/src/components/PluginIcon.vue
- packages/entities/entities-plugins/src/definitions/metadata.spec.ts
- packages/entities/entities-plugins/src/definitions/metadata.ts
- if the `getPluginIconURL` method is not provided any icon name, default to `missing` icon
- move check for empty icon name from `PluginIcon` component to `getPluginIconURL` method
- only compute and use default icon URL in `PluginIcon` component if the URL passed in `src` attribute was invalid and the `img` tag emitted an error
- [Slack thread discussion](https://kongstrong.slack.com/archives/C05UE909XU5/p1712172404522979?thread_ts=1712153356.330669&cid=C05UE909XU5)
- [KHCP-11396](https://konghq.atlassian.net/browse/KHCP-11396?atlOrigin=eyJpIjoiOGQxMTNjOWJjNzQzNDQxNDkwNmUyNDA0ZDI4NjU3NDIiLCJwIjoiaiJ9)
[KHCP-11396]: https://konghq.atlassian.net/browse/KHCP-11396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(plugin-icon): use default icon when plugin icon name is undefined [KHCP-11396]

- packages/analytics/analytics-config-store/src/components/AnalyticsConfigCheck.cy.ts
- packages/analytics/analytics-config-store/src/components/AnalyticsConfigCheck.vue
- packages/analytics/analytics-config-store/src/constants.ts
- packages/analytics/analytics-config-store/src/index.ts
- packages/analytics/analytics-config-store/src/stores/analytics-config.ts
- packages/analytics/analytics-metric-provider/sandbox/App.vue
- packages/analytics/analytics-metric-provider/src/components/MetricsConsumer.vue
- packages/analytics/analytics-metric-provider/src/components/MetricsProvider.cy.ts
- packages/analytics/analytics-metric-provider/src/components/MetricsProvider.vue
- packages/analytics/analytics-metric-provider/src/components/MetricsTestHarness.vue
- packages/analytics/analytics-metric-provider/src/components/metricsProviderUtil.ts
- packages/analytics/dashboard-renderer/README.md
- packages/analytics/dashboard-renderer/package.json
- packages/analytics/dashboard-renderer/sandbox/mock-data.ts
- packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
- packages/analytics/dashboard-renderer/sandbox/sandbox-query-provider.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue
- packages/analytics/dashboard-renderer/src/components/QueryDataProvider.vue
- packages/analytics/dashboard-renderer/src/constants.ts
- packages/analytics/dashboard-renderer/src/locales/en.json
- packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts
- packages/analytics/dashboard-renderer/vite.config.ts
- packages/analytics/metric-cards/sandbox/App.vue
- packages/analytics/metric-cards/src/components/MetricCardContainer.vue
- packages/analytics/metric-cards/src/types/metric-card.ts
- pnpm-lock.yaml
BREAKING CHANGE: refactor interface for analytics config store
- Change analytics config store to fetch config when first instantiated and expose refs rather than functions.
- Update dashboard renderer to fill in a default time spec based on the org's retention if one isn't provided.
- Don't issue queries until a time spec is determined.
- Fix missing feature flag functions in tests.
- Fix display of "description" property in metric cards: show in container rather than broadcasting to all cards.
- Fix title and description reactivity in metrics provider.
- Replace special timeframe token in tile descriptions.
- Fill in missing context values in the top-level renderer to save code in the tile renderers.
- [Creating a package docs](https://github.com/Kong/public-ui-components/blob/main/docs/ …
> feat(analytics): improved dashboard time spec handling [MA-2759]

- packages/entities/entities-shared/docs/entity-form-section.md
- packages/entities/entities-shared/src/components/entity-form-section/EntityFormSection.vue
We were using `fieldset` element in `EnitityFormSection` component for a form group, but there was no corresponding `legend` element.
However, we can't use the `legend` element for the form title, since it's deeply nested and is not a direct child of the `fieldset` element ([`legend` need to be direct child of `fieldset`](https://www.accessibility-developer-guide.com/examples/forms/grouping-with-fieldset-legend/#legend-must-be-a-direct-child-of-fieldset)). 
Given how the component was structured, it would be a major breaking change to move the title as the direct child of the `fieldset` element. So instead opted to use ARIA roles ([ref](https://www.w3.org/WAI/tutorials/forms/grouping/#associating-related-controls-with-wai-aria)).
We're generating a unique ID for each `EnitityFormSection` …
> fix(EntityFormSection): use aria labels for fieldsets [KHCP-11030]

- packages/entities/entities-plugins/src/components/select/PluginSelectGrid.vue
- packages/entities/entities-plugins/src/components/select/PluginSelectGroup.vue
This PR fixes an issue where incorrect plugin icons were displayed while filtering plugins in `PluginSelect`. After inspecting the build result, the plugin icon mapping is deemed correct. I suspect this was caused by the index-based `key` in `v-for` being reused.
Plugin icons are correct without filtering:
Some plugin icons are incorrect while filtering:
KM-113
> fix(entities-plugins): incorrect icons caused by v-for keys [KM-113]

- packages/core/expressions/package.json
- packages/core/expressions/src/components/ExpressionsEditor.vue
- packages/core/expressions/src/index.ts
- packages/core/expressions/src/monaco.ts
- packages/core/expressions/src/schema.ts
- packages/core/expressions/vite.config.ts
- packages/entities/entities-routes/docs/route-form.md
- packages/entities/entities-routes/docs/route-list.md
- packages/entities/entities-routes/fixtures/mockData.ts
- packages/entities/entities-routes/package.json
- packages/entities/entities-routes/sandbox/pages/RouteFormPage.vue
- packages/entities/entities-routes/sandbox/pages/RouteListPage.vue
- packages/entities/entities-routes/src/components/RouteForm.cy.ts
- packages/entities/entities-routes/src/components/RouteForm.vue
- packages/entities/entities-routes/src/components/RouteFormConfigTabs.vue
- packages/entities/entities-routes/src/components/RouteFormExpressionsEditor.vue
- packages/entities/entities-routes/src/components/RouteFormExpressionsEditorLoader.vue
- packages/entities/entities-routes/src/components/RouteList.cy.ts
- packages/entities/entities-routes/src/components/RouteList.vue
- packages/entities/entities-routes/src/locales/en.json
- packages/entities/entities-routes/src/types/route-form.ts
- packages/entities/entities-routes/src/types/route-list.ts
- packages/entities/entities-routes/tsconfig.json
- packages/entities/entities-routes/vite.config.ts
- packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue
- packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTableCell.vue
- packages/entities/entities-shared/src/components/entity-filter/EntityFilter.vue
- packages/entities/entities-shared/src/components/entity-form-section/EntityFormSection.vue
- packages/entities/entities-shared/src/types/base.ts
- pnpm-lock.yaml
This PR adds support for creating/editing the Expressions routes in `@kong-ui-public/entities-routes`, and also:
- Adds Expressions schemas for the WS and WSS protocols
- Adds test cases to cover creating and editing both traditional and Expressions routes
- Updates the route form page in the sandbox to support testing the combination of different route flavors
KM-20
> feat(*): expressions routes support [KM-20]

- packages/analytics/analytics-metric-provider/package.json
- packages/core/expressions/package.json
Loosen the peer dependency versions from exact versions to "current minor" by adding the `^` prefix.
Signed-off-by: Philipp Rudloff <philipp.rudloff@konghq.com>
Note: Running `pnpm install` after these changes didn’t produce any other changes.
> chore: loosen peer dependency ranges

- packages/entities/entities-routes/README.md
- packages/entities/entities-routes/docs/route-form.md
- packages/entities/entities-routes/package.json
- packages/entities/entities-routes/vite.config.ts
- pnpm-lock.yaml
This PR moves `@kong-ui-public/expressions` to `peerDependencies` so that we can provide `@kong-ui-public/expressions` and `monaco-editor` in host apps. This allows us to reduce the bundle size of `@kong-ui-public/entities-routes` (several megabytes smaller) as the Expressions features are not always necessary (e.g., Konnect API Products/Overview).
In host apps with non-type imports from `@kong-ui-public/entities-routes` but without the need to use Expressions features, they will need to mark these peer dependencies as `external` (as https://github.com/Kong/konnect-ui-apps/pull/3018 demonstrated):
```ts
defineConfig({
build: {
rollupOptions: {
external: ['@kong-ui-public/expressions', 'monaco-editor'],
},
},
})
```
I've also updated the documentation for that package to note this.
> refactor(entities-routes): make expressions and monaco as optionalDependencies

- .github/workflows/ci.yaml
- packages/core/app-layout/README.md
Skip CI job actions that run on a Pull Request that require `secrets` if the author is not a `COLLABORATOR` or `OWNER`
> ci: skip secrets for pr forks [KHCP-11575]

- packages/entities/entities-routes/sandbox/pages/RouteListPage.vue
- packages/entities/entities-routes/src/components/RouteList.vue
Adding a prop to allow hiding traditional columns in the route list.
> fix(entities-routes): add prop to hide traditional columns

- packages/entities/entities-plugins/package.json
- packages/entities/entities-plugins/src/components/PluginForm.vue
- pnpm-lock.yaml
This PR fixed an issue where plugins with `config.redis.cluster_addresses` and `config.redis.sentinel_addresses` cannot be created or edited if the user tried to add some addresses but removed all addresses before submitting the form.
This bug affects the following four plugins:
- graphql-proxy-cache-advanced
- graphql-rate-limiting-advanced
- proxy-cache-advanced
- rate-limiting-advanced
This fix should be a temporary and straightforward workaround since we should ultimately fix it in the `core/forms` package.
KAG-4328
> fix(entities-plugins): omit redis cluster/sentinel addresses if empty [KAG-4328]

- packages/analytics/analytics-chart/sandbox/pages/BarChartDemo.vue
- packages/analytics/analytics-chart/src/components/AnalyticsChart.cy.ts
- packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
- packages/analytics/analytics-chart/src/composables/useExploreResultToDatasets.spec.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToDatasets.ts
Explore result meta used to contain an array `dimensions: []`. We use this to generate the resulting ChartJS datasets. It was an array so the order in which it came back from druid was maintained, we didn't have to use `Object.entries`. 
Now it's an object `display: {}`. Now we need to call Object.entries() in order to iterate over it to create datasets, order is not guaranteed, need to do manual sorting.
- Sort the pivot records lookup table by value and extract an array of entity IDs to keep track of the order in which the datasets should appear in the chart
- Sort the rowLabels by the index in which they appear in the sorted list by value. (rowLabels is used to then generate the chartJS datsets and labels array)
- [Creating a package …
> fix: fix sorting for cross sectional datasets (bar charts)

- packages/entities/entities-gateway-services/src/components/GatewayServiceForm.vue
**Ticket:**
https://konghq.atlassian.net/browse/KHCP-11838
**Changes**
Fixes the Gateway Service tags input field to be consistent with other tags input fields. Other tag input fields allow input such as `tag1, tag2, tag3`, but the Gateway Service input field currently only allows input without spaces, i.e. `tag1,tag2,tag3`. This PR should fix this.
> fix(gateway-services): fix gateway service tags input [KHCP-11838]

- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-plugins/src/types/plugin.ts
This PR fixes a Konnect bug where dynamic ordering configuration is lost when editing a plugin.
> fix(entities-plugins): keep dynamic ordering in edit payload [KM-148]

- packages/core/forms/src/forms/RLAForm.vue
- packages/core/forms/src/locales/en.json
This pull request adds the dedicated section for Redis configuration which will show/hide in the RLA form according to the value of the `config.strategy`.
KM-178
> feat(forms): dedicated redis configuration for RLA [KM-178]

- packages/core/forms/src/forms/RLAForm.vue
- packages/core/forms/src/generator/FormGenerator.vue
- packages/core/forms/src/generator/fields/advanced/FieldArray.vue
This pull request updates the FieldArray to use partially KInput as array items to show the help text right below the input
|Before|After|
|:-:|:-:|
|<img width="796" alt="Screenshot 2024-05-29 at 12 44 25" src="https://github.com/Kong/public-ui-components/assets/5277268/f46c5464-c263-4ab8-b2fc-7912a1bb803e">|<img width="688" alt="Screenshot 2024-05-29 at 12 38 45" src="https://github.com/Kong/public-ui-components/assets/5277268/49f4fce4-443e-43ce-9567-6931f100dfae">|
KM-185
> fix(forms): partially use KInput in FieldArray [KM-185]

- packages/entities/entities-plugins/src/components/PluginList.vue
Plugins that are scoped to a consumer group do not support dynamic ordering either.
> fix(entities-plugins): hide ordering for consumer group plugins

- packages/entities/entities-plugins/src/components/PluginForm.vue
This pull request fixes the nested array for custom plugins. An example schema looks like the following:
```json
{
"fields": [
{
"some_items": {
"elements": {
"fields": [
{
"some_nested_items": {
"elements": {
"type": "string"
},
"type": "array"
}
}
],
"type": "record"
},
"type": "array"
}
}
]
}
```
KM-213 / FTI-6014
> fix(entities-plugins): nested array for custom schema [KM-213/FTI-6014]

- packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTableCell.vue
Fixing a `MutationObserver` error in base table when the first col is wrapped in `KBadge` and `KTruncate`.
KHCP-12242
> fix(entities-shared): MutationObserver error in base table

- packages/analytics/analytics-config-store/src/stores/analytics-config.ts
- packages/analytics/analytics-metric-provider/src/components/MetricsProvider.cy.ts
- packages/analytics/analytics-metric-provider/src/components/MetricsProvider.vue
- packages/analytics/analytics-metric-provider/src/components/metricsProviderUtil.ts
- packages/analytics/analytics-metric-provider/src/composables/useMetricFetcher.ts
- packages/analytics/analytics-metric-provider/src/types/fetcher-types.ts
- packages/analytics/analytics-utilities/src/types/explore-v4.ts
- packages/analytics/analytics-utilities/src/types/query-bridge.ts
- packages/analytics/dashboard-renderer/README.md
- packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.spec.ts
- packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue
- packages/analytics/dashboard-renderer/src/components/QueryDataProvider.vue
- packages/analytics/dashboard-renderer/src/locales/en.json
- packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts
BREAKING CHANGE: change signature of `queryFn` in query bridge, and make `datasource` a required property in dashboard definitions.
- Change signature of `queryFn`.
- Add `datasource` parameter to MetricsProvider.
- Add `datasource` property to dashboard query definitions.
> feat(analytics): add support for basic datasource [MA-2931]

- packages/analytics/analytics-utilities/src/types/explore-v4.ts
Small cleanup to remove limiting the timeframes available in basic endpoint
> feat: allow all relative time values for basic

- packages/core/forms/src/forms/RLAForm.vue
- packages/core/forms/src/generator/fields/advanced/FieldSelectionGroup.vue
- packages/core/forms/src/index.ts
- packages/entities/entities-plugins/docs/plugin-form.md
- packages/entities/entities-plugins/sandbox/pages/PluginFormPage.vue
- packages/entities/entities-plugins/src/components/PluginEntityForm.vue
- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-plugins/src/composables/useSchemas.ts
- packages/entities/entities-plugins/src/types/plugin-form.ts
`useRLARedesignedForm` and `useHorizontalRadiosForPluginScoping` are no longer used and the redesigned RLA form will be available for all
This pull request rolls out the redesigned RLA form and cleans the unnecessary props.
KM-233
> feat(plugins): rollout redesigned RLA form [KM-233]

- packages/core/forms/src/generator/FormGenerator.vue
- packages/core/forms/src/generator/fields/advanced/FieldArray.vue
This PR makes the VFG use `KTextArea` in array fields.
`FieldTextArea` is not used anymore, but we will clean it in the refactor PR along with other unused fields.
KM-249
> fix(forms): use KTextArea in array fields [KM-249]

- renovate.json
This PR tries to pin `monaco-editor` by excluding it for `@kong-ui-public/expressions` and `@kong-ui-public/entities-routes` via `packageRules` in `renovate.json`.
`monaco-editor` is currently only used for the Expressions routes support in `@kong-ui-public/expressions` and `@kong-ui-public/entities-routes`. We encountered several issues while consuming the latest `monaco-editor` in the host app during the development. To deliver the Expressions routes support in time, we decided to downgrade it to [`v0.21.3`–which we used previously in Kong Manager](https://github.com/Kong/kong-admin/blob/9bae765787d9ea28cfa48e16bd3c56b65e82a2c7/package.json#L85) to prevent [the Renovate bot from bumping it](https://github.com/Kong/public-ui-components/pull/1352). 
We will try to update it to the latest …
> chore(renovate): pin monaco-editor `expressions` and `entities-routes`

- packages/entities/entities-plugins/docs/plugin-form.md
- packages/entities/entities-plugins/sandbox/pages/PluginFormPage.vue
- packages/entities/entities-plugins/src/components/PluginForm.cy.ts
- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-plugins/src/locales/en.json
- packages/entities/entities-plugins/src/types/plugin-form.ts
> **BREAKING CHANGE:**  The Back button on the form has been removed, and `backRoute` no longer exists in the form configuration
According to our discussion on Slack, we decided to remove the Back button on the plugin form page due to its low usage.
KM-273
> feat(entities-plugins): remove back button in the form [KM-273]

- packages/analytics/dashboard-renderer/src/components/layout/GridLayout.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-12507
Wrap `ResizeObserver` callback in `window.requestAnimationFrame` to reduce number of "ResizeObserver loop limit exceeded" errors in DD
> fix(dashboard-renderer): resize observer callback [KHCP-12507]

- packages/analytics/analytics-geo-map/README.md
- packages/analytics/analytics-geo-map/sandbox/App.vue
- packages/analytics/analytics-geo-map/src/components/AnalyticsGeoMap.vue
Remove the `initial-zoom` and `centre` props in favour of a `bounds` prop
Set the maxBounds of the map by default
> fix: set the max bounds to prevent zooming out too far

- packages/entities/entities-vaults/src/components/SecretForm.cy.ts
- packages/entities/entities-vaults/src/components/SecretForm.vue
The `key` field in the secret edit form should be disabled.
KM-343
> feat(entities-vaults): disable secret key input when editing

- packages/analytics/analytics-utilities/src/types/explore-v4.ts
- shift naming a bit
- add `cost`
> fix(ai-explore): Metric naming

- packages/entities/entities-vaults/src/components/VaultForm.vue
Fix compatibility of STS endpoint url field in AWS vault form when saving in Konnect
> fix(vaultform): fix compatibility of STS endpoint url in Konnect

- packages/core/forms/src/components/FormGroup.vue
Unifying the style of required indicators in plugin forms with other entity forms.
| - | - |
| <img width="704" alt="image" src="https://github.com/user-attachments/assets/66ef3576-e5f7-48c0-b302-63fadb59a6da"> | <img width="686" alt="image" src="https://github.com/user-attachments/assets/16e53fd9-7e8e-4a7d-b7d6-b54768e328e4"> |
This PR also removes required indicators for checkbox fields.
> fix(forms): required indicator style

- packages/entities/entities-routes/src/components/RouteConfigCard.vue
- packages/entities/entities-shared/docs/config-card-item.md
- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.cy.ts
- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.vue
- packages/entities/entities-shared/src/types/entity-base-config-card.ts
Addresses: https://konghq.atlassian.net/browse/KHCP-12781
Add new value `CopyBadge` to `ConfigurationSchemaType` enum in EntityBaseConfigCard.vue for rendering array of strings as KCopy components. Use new `CopyBadge` schema type in `paths` and `hosts` fields in RouteConfigCard.vue (screenshot).
> fix(entities-routes): make paths and hosts copy badges [KHCP-12781]

- packages/core/expressions/README.md
- packages/core/expressions/package.json
- packages/core/expressions/vite.config.ts
- packages/entities/entities-routes/README.md
- packages/entities/entities-routes/docs/route-form.md
- packages/entities/entities-routes/package.json
- packages/entities/entities-routes/vite.config.ts
- pnpm-lock.yaml
To streamline the installation process, `optionalDependencies` and `peerDependencies` have been moved to dependencies. Now, the host app only needs to install entities-routes itself.
before:
```json5
// package.json
"@kong-ui-public/entities-routes": "x.x.x"
"@kong-ui-public/forms": "x.x.x"
"@kong-ui-public/expressions": "x.x.x"
```
```js
// vue
import { RouteForm } from '@kong-ui-public/entities-routes'
import '@kong-ui-public/expressions/dist/style.css'
```
after:
```json5
// package.json
"@kong-ui-public/entities-routes": "x.x.x"
```
```js
// vue
import { RouteForm } from '@kong-ui-public/entities-routes'
```
All other dependencies are automatically installed.
By externalizing most of the module from `node_modules`, the bundle size has been reduced from …
> chore: adjusting dependencies of expressions and routers

- packages/entities/entities-consumer-groups/sandbox/pages/ConsumerGroupListPage.vue
- packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
- packages/entities/entities-shared/src/composables/useFetcher.ts
When apply filter in consumer group list in Konnect, response from backend is not tailored for the table, so this change is made to adapt that format.
KM-410
> fix(entitites-consumer-groups): filter response transform [KM-410]

- packages/core/expressions/src/components/RequestModal.vue
- packages/core/expressions/src/components/RouterPlayground.cy.ts
- packages/core/expressions/src/components/RouterPlayground.vue
- packages/core/expressions/src/utils.ts
* HTTP headers in requests appeared as [object Object] in the exported JSON
* Support HTTP headers with multiple values (should add context value per header value)
[KM-391](https://konghq.atlassian.net/browse/KM-391?atlOrigin=eyJpIjoiMzc3NTQ1MDAzMWVhNDRjZDllZDFkNDA4OGM4Mjg0MDIiLCJwIjoiaiJ9)
[KM-391]: https://konghq.atlassian.net/browse/KM-391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(expressions): router playground known issues [KM-391]

- packages/core/forms/sandbox/App.vue
- packages/core/forms/sandbox/FieldTester.vue
- packages/core/forms/src/components/fields/FieldRadio.vue
- packages/core/forms/src/components/fields/__tests__/FieldRadio.cy.ts
Convert `FieldRadio` to use kongponents for [KHCP-11342](https://konghq.atlassian.net/browse/KHCP-11342).
Adoption with passing E2Es: https://github.com/Kong/konnect-ui-apps/pull/3958
[KHCP-11342]: https://konghq.atlassian.net/browse/KHCP-11342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(vfg): convert field-radio [khcp-11342]

- .npmrc
- packages/analytics/analytics-chart/vite.config.ts
- packages/analytics/analytics-geo-map/vite.config.ts
- packages/analytics/analytics-metric-provider/vite.config.ts
- packages/entities/entities-certificates/package.json
- packages/entities/entities-certificates/vite.config.ts
- packages/entities/entities-consumer-credentials/package.json
- packages/entities/entities-consumer-groups/package.json
- packages/entities/entities-consumers/package.json
- packages/entities/entities-data-plane-nodes/package.json
- packages/entities/entities-gateway-services/package.json
- packages/entities/entities-key-sets/package.json
- packages/entities/entities-keys/package.json
- packages/entities/entities-plugins/package.json
- packages/entities/entities-routes/package.json
- packages/entities/entities-routes/vite.config.ts
- packages/entities/entities-shared/package.json
- packages/entities/entities-snis/package.json
- packages/entities/entities-upstreams-targets/package.json
- packages/entities/entities-vaults/package.json
- pnpm-lock.yaml
- vite.config.shared.ts
Update the build configuration of `entities-*` packages to externalize common dependencies.
Externalizes:
- `@kong-ui-public/entities-shared`
- `@kong/icons`
Switches the Kongponents external to utilize a Regular Expression
The `.npmrc` changes need to be replicated in `konnect-ui-apps`
```md
dist/style.css                      11.06 kB │ gzip:   2.37 kB
dist/entities-certificates.es.js   504.87 kB │ gzip: 111.05 kB
dist/style.css                      11.06 kB │ gzip:  2.37 kB
dist/entities-certificates.umd.js  363.66 kB │ gzip: 94.92 kB
```
```md
dist/style.css                      11.06 kB │ gzip:  2.37 kB
dist/entities-certificates.es.js   336.60 kB │ gzip: 69.73 kB
dist/style.css                      11.06 kB │ gzip:  2.37 kB
dist/entities-certificates.umd.js  246.57 kB │ gzip: 60.10 …
```
> feat(entities-*): externalize deps

- packages/entities/entities-plugins/fixtures/mockData.ts
- packages/entities/entities-plugins/src/components/VaultSecretPicker.cy.ts
- packages/entities/entities-plugins/src/components/VaultSecretPicker.vue
- packages/entities/entities-vaults/sandbox/pages/VaultListPage.vue
- packages/entities/entities-vaults/src/components/SecretForm.cy.ts
- packages/entities/entities-vaults/src/components/SecretForm.vue
- packages/entities/entities-vaults/src/components/SecretFormInner.vue
- packages/entities/entities-vaults/src/components/SecretList.cy.ts
- packages/entities/entities-vaults/src/components/SecretList.vue
- packages/entities/entities-vaults/src/components/SecretListInner.vue
- packages/entities/entities-vaults/src/components/VaultForm.vue
- packages/entities/entities-vaults/src/components/VaultList.vue
- packages/entities/entities-vaults/src/locales/en.json
- packages/entities/entities-vaults/src/secrets-endpoints.ts
- packages/entities/entities-vaults/src/types/vault-form.ts
- packages/entities/entities-vaults/src/vaults-endpoints.ts
Integrate Konnect Vault with Konnect Config Store
KM-445
> feat(entities): config store secret

- packages/core/expressions/package.json
- pnpm-lock.yaml
- renovate.json
> Need thorough tests in host apps
This pull request reverts:
- https://github.com/Kong/public-ui-components/pull/1354
The reason why we decided to pin `monaco-editor` for `core/expressions` was because the latest version by that time was causing errors. However, it seems we cannot reproduce those errors anymore with the latest version as of today. This pull request is to revert the previous change that pinned `monaco-editor`.
KM-390
> chore(deps): revert pinning monaco in core/expressions

- packages/entities/entities-certificates/src/components/CACertificateList.vue
- packages/entities/entities-certificates/src/components/CertificateList.vue
- packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue
- packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
- packages/entities/entities-consumers/src/components/ConsumerList.vue
- packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
- packages/entities/entities-key-sets/src/components/KeySetList.vue
- packages/entities/entities-keys/src/components/KeyList.vue
- packages/entities/entities-plugins/src/components/PluginList.vue
- packages/entities/entities-routes/src/components/RouteList.vue
- packages/entities/entities-snis/src/components/SniList.vue
- packages/entities/entities-upstreams-targets/src/components/TargetsList.vue
- packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
- packages/entities/entities-vaults/src/components/VaultList.vue
This PR uses `useActionOutside` to decide the size of the create entity button in the toolbar, so that:
1. the create entity button size aligns with the learning hub icon *in Gateway Manager*
2. the create entity button size aligns with the column toggle icon *in Kong Manager*
This PR also removes `use-action-outside` on `EntityBaseTable` because `EntityBaseTable` does not have this prop.
| Gateway Manager | Kong Manager |
| - | - |
| <img width="1727" alt="image" src="https://github.com/user-attachments/assets/c26c7611-6959-4040-852c-aa297fd71c7e"> | <img width="1723" alt="image" src="https://github.com/user-attachments/assets/ad730388-59eb-41a6-a779-a0c9e93bcb3f"> |
> fix(entities): toolbar create button size

- packages/analytics/analytics-utilities/src/types/explore/requests.ts
- Missed removing status code groups from metric fields
- Adding back `country_code`. It's baked into a few of our tests and I figure it's easier to not rip out the functionality that's already there
> fix: clean up request filter types

- packages/core/forms/src/components/FormGroup.vue
- packages/core/forms/src/components/fields/FieldArray.vue
- packages/core/forms/src/components/fields/FieldArrayCardContainer.vue
Add missing index info to deeply nested input ID, e.g. `targets` in the `ai-proxy-advanced` plugin:
| - | - |
| <img width="940" alt="image" src="https://github.com/user-attachments/assets/12956ad3-a1d0-4e67-95e7-e506fcd51b11"> | <img width="953" alt="image" src="https://github.com/user-attachments/assets/3806a76a-7fce-4d95-818e-ae9c2460d83d"> |
KM-521
> fix(forms): add index to deeply nested input id

- packages/core/forms/src/components/FormGenerator.vue
- packages/core/forms/src/components/FormGroup.vue
- packages/core/forms/src/components/fields/FieldArray.vue
- packages/core/forms/src/components/fields/FieldObject.vue
- packages/entities/entities-plugins/src/components/PluginEntityForm.vue
- packages/entities/entities-plugins/src/components/PluginForm.vue
> fix(forms): emit event for nested objects

- packages/core/core/src/useTablePreferences/index.ts
- packages/core/core/src/useTablePreferences/useTablePreferences.spec.ts
- packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
- packages/entities/entities-gateway-services/src/locales/en.json
- packages/entities/entities-routes/README.md
- packages/entities/entities-routes/src/components/RouteList.vue
- packages/entities/entities-routes/src/locales/en.json
- packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue
KM-517
Add "Created At"(Optional Field) and "Last Modified"(Default Field)  to the Services and Routes page, enabling `getTablePreferences` to take given preferences
> feat(gateway-manager): add columns for routes and services [KM-517]

- packages/core/forms/sandbox/model.json
- packages/core/forms/src/components/fields/FieldRadio.vue
- packages/core/forms/src/components/fields/FieldSelect.vue
- packages/core/forms/src/components/fields/FieldSwitch.vue
- packages/core/forms/src/components/fields/__tests__/FieldCheckbox.cy.ts
- packages/core/forms/src/components/fields/__tests__/FieldInput.cy.ts
- packages/core/forms/src/components/fields/__tests__/FieldRadio.cy.ts
- packages/core/forms/src/components/fields/__tests__/FieldSelect.cy.ts
- packages/core/forms/src/components/fields/__tests__/FieldSwitch.cy.ts
- packages/core/forms/src/components/fields/__tests__/FieldTextArea.cy.ts
- packages/core/forms/src/types/form-fields.ts
Convert VFG `FieldSelect` to use Kongponents + add more VFG component test coverage.
Addresses [KHCP-11336](https://konghq.atlassian.net/browse/KHCP-11336).
Adoption PR (with passing E2Es): https://github.com/Kong/konnect-ui-apps/pull/4209
[KHCP-11336]: https://konghq.atlassian.net/browse/KHCP-11336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(vfg): convert field-select + more tests [khcp-11336]

- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-plugins/src/components/PluginFormActionsWrapper.vue
Plugin buttons missing in workspaces whose name has dots
after fix:
[KM-547](https://konghq.atlassian.net/browse/KM-547)
[KM-547]: https://konghq.atlassian.net/browse/KM-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(entities-plugins): missing of action buttons [KM-547]

- packages/core/forms/src/components/fields/FieldInput.vue
- packages/core/forms/src/components/fields/__tests__/FieldInput.cy.ts
- packages/entities/entities-plugins/src/components/PluginForm.vue
KM-502
Some encrypted fields are required to be able to toggle visibility when edited in forms
> feat(forms): visibility toggle for password inputs [KM-502]

- packages/core/forms/sandbox/App.vue
- packages/core/forms/sandbox/index.ts
`provide` call should be moved into the `setup` block.
> fix(core): fix form sandbox

- packages/core/forms/sandbox/schema.json
- packages/core/forms/src/components/fields/FieldInput.vue
If not specified in css, edge will have built-in password toggling mechanism that interferes with ours.
KM-502
> fix(forms): hide edge built-in password handler [KM-502]

- renovate.json
Renovatebot should ignore updates to `swagger` packages until `@kong/swagger-ui-kong-theme-universal` is able to handle the latest version of swagger-ui or the `swagger-ui-web-component` package is removed.
> chore: ignore swagger package updates

- packages/portal/spec-renderer/sandbox/test.yaml
- packages/portal/spec-renderer/src/components/SpecDetails.vue
- packages/portal/swagger-ui-web-component/public/index.html
- packages/portal/swagger-ui-web-component/public/petstore_v3.json
- packages/portal/swagger-ui-web-component/public/test.yaml
- packages/portal/swagger-ui-web-component/src/styles/overrides.css
Context: Swagger UI Web Component uses shadow root, which makes overriding styles difficult from consuming applications.
Goal: Stop the operation path name from overflowing its container.
Solution: Add CSS Variables with sane defaults, and make changes to the renderer in order to prevent drastic overflow.
Before:
After:
NB: There is a [sister PR](https://github.com/Kong/swagger-ui-kong-theme/pull/183) to add the `title` property in order to get the full string to render on hover.
> fix: set custom max-widths for path names

- packages/analytics/analytics-chart/src/components/AnalyticsChart.cy.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToDatasets.spec.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToDatasets.ts
Sorting logic was only looking at one segment within the bar rather than taking all segments into account.
https://konghq.atlassian.net/browse/MA-3157
> fix: chart dataset sorting issue

- package.json
- pnpm-lock.yaml
- vite.config.shared.ts
[KM-579](https://konghq.atlassian.net/browse/KM-579)
Sass start to show a [deprecation warning](https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#js-api-2) since `1.79.0`.
~~This PR migrate the usage to its modern compiler [as we did for `konnect-ui-apps`](https://github.com/Kong/konnect-ui-apps/pull/4514).~~
* See https://github.com/Kong/shared-ui-components/pull/2872
[KM-579]: https://konghq.atlassian.net/browse/KM-579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(*): switch to sass modern api

- packages/analytics/analytics-utilities/src/queryTime.spec.tz.ts
- packages/analytics/analytics-utilities/src/queryTime.ts
- Absolute time frames that crossed DST boundaries didn't correctly calculate the start time for delta queries.
- This could result in delta queries returning extra records.
- This could also impact current / previous week / month determinations around DST changes.
> fix(analytics): fix delta queries for absolute timeframes [MA-3273]

- packages/core/forms/src/components/fields/FieldInput.vue
Now `KInput` supports toggling password input mask natively through https://github.com/Kong/kongponents/issues/2448. This PR adopts this feature.
KM-586
> fix(forms): adopt native mask support

- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-plugins/src/locales/en.json
In plugin forms:
1. Adding default values to the placeholder of the protocols field in GM
2. Removing all default values from placeholders in KM
| GM | KM |
| - | - |
| <img width="827" alt="image" src="https://github.com/user-attachments/assets/1fb7f979-a50d-4b02-8954-e4d9c0916e37"> | <img width="728" alt="image" src="https://github.com/user-attachments/assets/77b5414e-dad7-4d85-87d9-0b330c60eb00"> |
KM-526
> feat(entities-plugins): add default values in protocols placeholder

- packages/analytics/analytics-metric-provider/sandbox/App.vue
- packages/analytics/analytics-metric-provider/src/composables/useMetricFetcher.ts
- packages/analytics/analytics-metric-provider/src/mockExploreResponse.ts
In the case where we can't query a trend (either because the props said not to or because we're doing a multi-entity query), it doesn't make sense to render any trend text.
> fix(analytics): trend range text in multi-entity queries [MA-3250]

- packages/entities/entities-shared/src/composables/tests/useFetchUrlBuilder.spec.ts
- packages/entities/entities-shared/src/composables/useFetchUrlBuilder.ts
- packages/entities/entities-shared/src/types/entity-filter.ts
[KM-639](https://konghq.atlassian.net/browse/KM-639)
The following request URLs do not work unless we strip the trailing slash.
- `/v2/control-planes/{control-plane-id}/core-entities/key-sets/{query}/`
- `/v2/control-planes/{control-plane-id}/core-entities/key/{query}/`
- `/v2/control-planes/{control-plane-id}/core-entities/key-sets/{key-set-id}/keys/{query}/`
So we remove them to at least make them work.
Also added some comments for filter types.
[KM-639]: https://konghq.atlassian.net/browse/KM-639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(entities-shared): exact match should strip trailing slash

- packages/entities/entities-plugins/src/components/PluginConfigCard.vue
- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.vue
- packages/entities/entities-shared/src/components/entity-base-config-card/EntityBaseConfigCard.vue
- packages/entities/entities-shared/src/composables/index.ts
- packages/entities/entities-shared/src/composables/useSchema.ts
- packages/entities/entities-shared/src/index.ts
The schema information was lost in the nested rendering, this is a temporary solution for a quick fix to get the schema information in L2
**Before:**
**After:**
[KM-629](https://konghq.atlassian.net/browse/KM-629)
[KM-629]: https://konghq.atlassian.net/browse/KM-629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(*): add support for masking credentials fields at L2 [KM-629]

- packages/entities/entities-plugins/src/components/PluginSelect.vue
[KM-647](https://konghq.atlassian.net/browse/KM-647)
**Reproduction:**
1. accessing a serverless cp
2. go to the add plugin page
3. reload the page
4. the custom plugin tab can be clicked
**Expected:**
the custom plugin tab should always be disabled under the serverless CP
[preview link](https://pr-4751--gateway-manager.cloud-preview.konghq.tech/gateway-manager)
[KM-647]: https://konghq.atlassian.net/browse/KM-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(entities-plugins): wrong custom plugin tab active state [KM-647]

- packages/analytics/analytics-chart/sandbox/pages/TimeSeriesChartDemo.vue
- packages/analytics/analytics-chart/src/components/AnalyticsChart.cy.ts
- packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
- packages/analytics/analytics-chart/src/components/CsvExportButton.vue
- packages/analytics/analytics-chart/src/composables/index.ts
- packages/analytics/analytics-chart/src/composables/useEvauluateFeatureFlag.ts
- packages/analytics/analytics-chart/src/constants/index.ts
- packages/analytics/analytics-chart/src/locales/en.json
- packages/analytics/analytics-chart/src/types/chart-data.ts
CSV export link moved to inside an action menu
https://konghq.atlassian.net/browse/MA-3301
> feat(analytics-chart): move actions into kebab menu [MA-3301]

- packages/entities/entities-plugins/fixtures/mockData.ts
- packages/entities/entities-plugins/src/components/PluginList.vue
KM-662
Filtered plugin item in Konnect contains `ordering:{}` in response, this results in current UI showing dynamic badge for static ordering. This pr allows passing empty ordering object too.
> fix(pluginlist): adapt empty ordering object for filtered plugin

- packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
- packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
- packages/analytics/dashboard-renderer/src/components/BarChartRenderer.vue
- packages/analytics/dashboard-renderer/src/components/BaseAnalyticsChartRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue
- packages/analytics/dashboard-renderer/src/components/TimeseriesChartRenderer.vue
- packages/analytics/dashboard-renderer/src/locales/en.json
- packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts
https://konghq.atlassian.net/browse/MA-3367
- add new edit-tile event to dashboard renderer
- forward `go-to -explore` prop to analytics chart through tile definition
- add new editable property to tile definition that will add an "edit" item to the analytics chart kebab menu. Clicking on edit, will emit an @edit-tile event with the entire GridTile<T> object containing the tile layout, definition and index
```
{
"layout": {
"position": {
"col": 0,
"row": 2
},
"size": {
"cols": 3,
"rows": 2
}
},
"meta": {
"chart": {
"type": "horizontal_bar",
"chartTitle": "Horizontal bar chart of mock data",
"allowCsvExport": true
},
"query": {
"datasource": "basic",
"dimensions": [
"route"
]
},
"editable": true
},
"id": 3
}
```
> feat(dashboards and charts): editable tiles | slottable menu items

- packages/entities/entities-plugins/src/components/PluginList.vue
- packages/entities/entities-plugins/src/locales/en.json
[KM-667](https://konghq.atlassian.net/browse/KM-667)
If `<PluginList>` receives `config.isExactMatch: true`, the placeholder should reflect that.
[KM-659]: https://konghq.atlassian.net/browse/KM-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KM-660]: https://konghq.atlassian.net/browse/KM-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KM-667]: https://konghq.atlassian.net/browse/KM-667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(entities-plugins): placeholder should reflect actual behavior

- packages/entities/entities-plugins/src/components/PluginIcon.vue
- packages/entities/entities-plugins/src/components/custom-plugins/PluginCustomGrid.vue
- packages/entities/entities-plugins/src/components/select/PluginSelectGroup.vue
For the reproduction method, please refer to: [KM-658](https://konghq.atlassian.net/browse/KM-658)
in fact, this problem is caused by the konnect, which hides the app container during initialization ([see here](https://github.com/Kong/shared-ui-components/blob/defb8926e9a7ae6b2c29239fdd895d4d813dfe8d/packages/core/konnect-app-shell/src/components/KonnectAppShell.vue#L305)), during which the card height is always calculated to be 0px.
This is a quick and easy fix that provide a minimum height.
[preview link](https://pr-4755--gateway-manager.cloud-preview.konghq.tech/gateway-manager)
[KM-658]: https://konghq.atlassian.net/browse/KM-658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(entities-plugins): custom plugins disappeared after page reload [KM-658]

- packages/analytics/analytics-chart/src/locales/en.json
- packages/analytics/analytics-utilities/src/types/query-bridge.ts
- packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
- packages/analytics/dashboard-renderer/sandbox/sandbox-query-provider.ts
- packages/analytics/dashboard-renderer/src/components/BaseAnalyticsChartRenderer.vue
- Add optional `exploreBaseUrl` property to AnalyticsQueryBridge interface
- If Query Bridge is provided with an `exploreBaseUrl` this will be forwarded to `analytics-chart` along with the explore query, datasource and chart type as the `go-to-explore` link, which will show the go to explore option in the analytics chart kebab menu
- Updated "go to explore" text to match figma
https://konghq.atlassian.net/browse/MA-3380
> feat: add explore base url to query bridge for analytics jump to explore

- packages/entities/entities-routes/src/components/RouteList.vue
- packages/entities/entities-routes/src/locales/en.json
[KM-673](https://konghq.atlassian.net/browse/KM-673)
If `<RouteList>` receives `config.isExactMatch: true`, the placeholder should reflect that.
[KM-673]: https://konghq.atlassian.net/browse/KM-673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(entities-routes): placeholder should reflect actual behavior

- packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
- packages/analytics/analytics-chart/src/locales/en.json
- click event should be on the dropdown item not the span this was causing the export button click event to be missed sometimes it user is not clicking right on the span
- update text for export and explore options
> fix: address comment from host app pr

- packages/entities/entities-plugins/src/components/PluginConfigCard.vue
- packages/entities/entities-plugins/src/components/PluginList.vue
- packages/entities/entities-shared/src/components/common/TableTags.vue
This PR fixes the plugin icon size:
It also fixes a console warning:
> fix(entities): plugin icon size and tag warning

- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-plugins/src/composables/useSchemas.ts
- packages/entities/entities-plugins/src/definitions/schemas/AIProxyAdvanced.ts
- packages/entities/entities-plugins/src/types/plugin-form.ts
- packages/entities/entities-plugins/src/types/plugins/shared.d.ts
This is a temporary workaround for the issue that the `ai-proxy-advanced` plugin cannot be created if users don't provide `config.embeddings` or `config.vectordb`.
KM-675
> fix(entities-plugins): ai-proxy-advanced form

- packages/analytics/analytics-utilities/src/types/explore/advanced.ts
- packages/analytics/analytics-utilities/src/types/explore/ai.ts
- packages/analytics/analytics-utilities/src/types/explore/basic.ts
> feat: v2 filters in explore

- packages/core/i18n/src/i18n.spec.ts
- packages/core/i18n/src/i18n.ts
- packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
- packages/entities/entities-routes/src/components/RouteList.vue
- packages/entities/entities-vaults/src/components/SecretListInner.vue
The filter API is returning timestamps in milliseconds instead of seconds and `null` as `updated_at` values for those weren't modified since created. The issue affects both filtered services and routes.
Before:
After:
> fix(i18n): compatible with timestamp in milliseconds or null values

- packages/entities/entities-shared/sandbox/pages/ConfigCardItemPage.vue
- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.cy.ts
- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.vue
This pull request fixes the several issues with `<ConfigCardItem />`:
1. Incorrect `box-sizing`
2. Label text overflows when too long
|Before|After|
|:-|:-|
|![Screenshot 2024-11-19 at 12 32 45 2](https://github.com/user-attachments/assets/f1ebcd6c-cf0a-4918-b10c-9753b2487f7a)|<video src="https://github.com/user-attachments/assets/baad9400-e7ce-4b28-9489-1d5dc37358af">|
KM-719
> fix(entities-shared): truncate labels in config card items

- packages/core/forms/src/components/fields/FieldObjectAdvanced.vue
Problematic field example:
```json
{
"trace_services": {
"description": "Map of routes matchers with sampling rates, use when plugin mode is global",
"keys": {
"type": "string"
},
"type": "map",
"values": {
"between": [
0,
1
],
"default": 0,
"required": true,
"type": "number"
}
}
}
```
This PR ensures the form respects `"type": "number"` and `"default": 0`.
FTI-6360
> fix(forms): number values in map fields

- packages/entities/entities-routes/src/components/RouteForm.vue
- packages/entities/entities-routes/src/types/route-form.ts
This pull request fixes an issue where the expressions editor became invisible sometimes
KM-737
> fix(entities-routes): invisible expressions editor sometimes

- packages/analytics/dashboard-renderer/src/components/BaseAnalyticsChartRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
https://konghq.atlassian.net/browse/MA-3465
- Make the `.tile-boundary` have `display: flex` then create a new tile-content div to wrap the component rendered in the tile.
- Use `flex-grow: 1` on the `.tile-content` so that it takes up available space (taking siblings into account) 
- The analytics chart renderer component can now use `height: 100%` and it will gracefully stay within the bounds of its container, vertically. 
There should be visible effect on users from this change.
> fix: revert padding change for kebab menu ff

- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- packages/analytics/dashboard-renderer/src/locales/en.json
https://konghq.atlassian.net/browse/MA-3472
https://konghq.atlassian.net/browse/MA-3473
- align kebab menu dropdown `bottom-end`
- Rename "Open in Explorer" -> "Explore"
> fix: kebab menu dropdown placement and alignment

- packages/core/i18n/src/i18n.spec.ts
- packages/core/i18n/src/i18n.ts
This pull request includes changes to improve the date formatting in the i18n module. The most important changes include adding new test cases for various ISO date formats and modifying the `formatIsoDate` function to exclude milliseconds.
This resolves a bug where a timestamp with trailing 0s will result in dividing the number by 1000 twice, resulting in an incorrect date.
---
Improvements to date formatting:
* [`packages/core/i18n/src/i18n.spec.ts`](diffhunk://#diff-39efa8e72b2e74acd22901626beabcd9d5521455aaa59f62b17b491f0e39858bR161-R167): Added test cases to ensure `formatIsoDate` correctly formats ISO dates with and without milliseconds, and with different time zone offsets.
Codebase simplification:
* [`packages/core/i18n/src/i18n.ts`](diffhunk://#diff-e7652b19e52ba221117c0d8d125453ea …
> fix(i18n): formatIsoDate handles trailing 0s

- packages/core/forms/src/components/forms/RLAForm.vue
KM-752
Place the enable switch from hidden advanced fields into top of form like other plugins for rate limiting advanced form.
Before:
After:
> fix(rla-form): place enable switch in top of form

- packages/analytics/analytics-utilities/src/types/chart-types.ts
- packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
- packages/analytics/dashboard-renderer/sandbox/sandbox-query-provider.ts
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts
https://konghq.atlassian.net/browse/MA-3476
- Add support for `timeseries_bar` chart to chart types list in `analytics-utilities`
- Add support for `timeseries_bar` chart to dashboard renderer
- Also fix mock data in sandbox query provider. Seems like it was never updated to take into consideration that the query passed in is now a `DatasourceAwareQuery `
> feat: enable support for timeseries_bar chart

- packages/core/tracing/sandbox/pages/TraceViewerPage.vue
- packages/core/tracing/src/components/trace-viewer/TraceViewer.vue
This pull request fixes the height for skeleton containers to avoid shaking while switching between the ON and OFF states of skeletons in `TraceViewer`.
> fix(tracing): fix height for skeleton container

- packages/entities/entities-certificates/src/components/CACertificateList.vue
- packages/entities/entities-certificates/src/components/CertificateList.vue
- packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue
- packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
- packages/entities/entities-consumers/src/components/ConsumerList.vue
- packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
- packages/entities/entities-key-sets/src/components/KeySetList.vue
- packages/entities/entities-keys/src/components/KeyList.vue
- packages/entities/entities-plugins/src/components/PluginList.vue
- packages/entities/entities-routes/sandbox/pages/RouteListPage.vue
- packages/entities/entities-routes/src/components/RouteList.vue
- packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue
- packages/entities/entities-shared/src/composables/useFetcher.ts
- packages/entities/entities-shared/src/types/entity-base-table.ts
- packages/entities/entities-snis/src/components/SniList.vue
- packages/entities/entities-upstreams-targets/src/components/TargetsList.vue
- packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
- packages/entities/entities-vaults/src/components/SecretListInner.vue
- packages/entities/entities-vaults/src/components/VaultList.vue
[KM-747](https://konghq.atlassian.net/browse/KM-747)
Before:
https://github.com/user-attachments/assets/f267a6f1-9d23-486f-a82d-141f44d546ec
After:
https://github.com/user-attachments/assets/d4a6cce2-8440-4157-a794-eb3f8c49d3c9
Issue:
This PR addresses an issue where a flash of outdated list data appears when navigating away from and back to a list page after changes are made to the entity list. This happens because the `fetcher-cache-key` is reset every time the list page reloads.
To fix this, the PR introduces a global map to track fetcher cache keys by `cacheIdentifier` within the same session. This ensures the fetcher cache remains consistent, reducing flickers of stale data while still allowing revalidation to update the list seamlessly.
I also added a default `row-key` to …
> fix(entities-*): persist fetcher cache key within session

- packages/core/tracing/src/components/trace-viewer/TraceViewer.vue
This pull request fixes the URL truncation and `word-break` in its tooltip:
> fix(tracing): url truncation and tooltip work-break

- packages/portal/spec-renderer/src/components/SpecOperationsList.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-14300
> fix(spec-renderer): tolowercase is not a function [KHCP-14300]

- packages/analytics/analytics-chart/README.md
- packages/analytics/analytics-chart/sandbox/pages/TimeSeriesChartDemo.vue
- packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
- packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
- packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
- packages/analytics/analytics-chart/src/composables/useChartLegendValues.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToTimeDatasets.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToTimedDatasets.spec.ts
- packages/analytics/analytics-chart/src/locales/en.json
- packages/analytics/analytics-chart/src/types/chart-data.ts
- packages/analytics/analytics-chart/src/types/explore-to-dataset-deps.ts
- packages/analytics/analytics-utilities/src/format.ts
- packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
- packages/analytics/dashboard-renderer/src/components/BaseAnalyticsChartRenderer.vue
- packages/analytics/dashboard-renderer/src/types/dashboard-renderer-types.ts
https://konghq.atlassian.net/browse/MA-3442
> feat: add threshold line to timeseries charts [MA-3442]

- packages/analytics/analytics-utilities/src/granularity.ts
- packages/analytics/analytics-utilities/src/queryTime.spec.tz.ts
- packages/analytics/analytics-utilities/src/queryTime.ts
- packages/analytics/analytics-utilities/src/timeframes.spec.ts
- packages/analytics/analytics-utilities/src/timeframes.ts
- packages/analytics/analytics-utilities/src/types/druid-granularity.ts
- packages/analytics/analytics-utilities/src/types/explore/common.ts
- packages/analytics/analytics-utilities/src/types/query-time.ts
- packages/analytics/analytics-utilities/src/types/timeframe-options.ts
- packages/analytics/analytics-utilities/src/types/timeframe.ts
- Add new granularity values and definitions
- Add support for passing one feature flag to query time and `allowedGranularities`
- Add new timeframe -> granularity mappings
> feat(analytics): add new granularities with support for FF [MA-2149]

- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- If granularity is provided through the tile definition use that. Otherwise, fallback to the granularity which was determined and used at query time, which is available in the `meta` of the explore result.
https://konghq.atlassian.net/browse/MA-3488
> fix(dashboards): preserve granularity in explore link

- packages/analytics/analytics-utilities/src/timeframes.ts
Last 6 hours needs to support 1 hour granularity in order to remain compatible with its old set of allowed granularities.
> fix(analytics): backwards-compatible granularities [MA-2149]

- CODEOWNERS
This pull request adds Team KM as a code owner for the `core/tracing` package.
`core/tracing` is currently built for the Active Tracing feature on Konnect.
> chore(codeowners): update codeowners for core/tracing

- packages/core/tracing/src/components/trace-viewer/SpanAttribute.vue
- packages/core/tracing/src/types/trace-viewer.ts
This pull request adds support for linking upstream targets in span attributes.
KM-798
> feat(tracing): support linking to upstream targets in span attributes

- packages/analytics/analytics-utilities/src/types/explore/advanced.ts
- packages/analytics/analytics-utilities/src/types/explore/requests.ts
> feat: add filtering for country code

- packages/analytics/analytics-chart/src/locales/en.json
Update the Time based X-axis title.
> fix(analytics): shift numbers to digits instead of words

- packages/entities/entities-shared/src/composables/index.ts
- packages/entities/entities-shared/src/composables/useFetcher.ts
[KM-805](https://konghq.atlassian.net/browse/KM-805)
- `useFetcher` should return shared refs for `fetcherCacheKey`
- added a new `useFetcherCacheKey` composable that can be used alone
[KM-805]: https://konghq.atlassian.net/browse/KM-805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(entities-shared): persistent cache key should share the same refs

- packages/core/tracing/package.json
- packages/core/tracing/src/components/trace-viewer/SpanAttribute.vue
- packages/core/tracing/src/components/trace-viewer/SpanAttributeTable.vue
- packages/core/tracing/src/components/waterfall/WaterfallSpanBar.vue
- packages/core/tracing/src/components/waterfall/WaterfallSpanRow.vue
- packages/core/tracing/src/components/waterfall/WaterfallView.vue
- packages/core/tracing/src/constants/spans.ts
- packages/core/tracing/src/locales/en.json
- packages/core/tracing/src/types/spans.ts
- packages/core/tracing/src/types/waterfall.ts
- packages/core/tracing/src/utils/spans.ts
- packages/core/tracing/src/utils/time.ts
This pull request is mainly for these changes:
- Showing the start and end date and time of the selected span in the "Span attributes" section in ISO 8601 format with nanosecond precision (KM-797):
- Fixed the width and position calculation for span bars (KM-808):
|:-|:-|
|![image (30)](https://github.com/user-attachments/assets/e2f50b96-5af2-4e16-b25b-aae63864f5ba) ![image (31)](https://github.com/user-attachments/assets/25dfabdc-d00f-4a7f-8131-94f83fd94aa7)|<img width="1077" alt="Screenshot 2024-12-11 at 11 27 07" src="https://github.com/user-attachments/assets/b22b75a7-9afb-4611-bf7d-e9862836894a">|
The minimal width of a span bar was adjusted to `1px` to show the spans with a relatively short duration more accurately.
- Highlighting the span rows on hover (using the …
> fix(tracing): bar calculation and start and end time in span attributes

- packages/analytics/analytics-utilities/src/queryTime.spec.tz.ts
- packages/analytics/analytics-utilities/src/queryTime.ts
- packages/analytics/analytics-utilities/src/timeframes.ts
- packages/analytics/analytics-utilities/src/types/timeframe-options.ts
Allow specifying default values for fine-grained relative times.
> feat(analytics): specific defaults for granularities [MA-3507]

- README.md
Change linking tutorial to `pnpm link` since current package management tool is pnpm.
> chore(readme): change linking tutorial to pnpm link

- packages/entities/entities-shared/docs/entity-empty-state.md
- packages/entities/entities-shared/sandbox/pages/EntityEmptyStatePage.vue
- packages/entities/entities-shared/src/components/entity-empty-state/EntityEmptyState.vue
https://konghq.atlassian.net/browse/KHCP-14355
In EntityEmptyState component: 
Updates pricing prop from String -> Boolean as we're slotting it.
Also adjusts CSS spacing for a better look.
> fix(entity-empty-state): update pricing prop type and style fixes [khcp-14355]

- packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
When hovering, use terse display mode because space is less at a premium.
> fx(analytics): timeserieschart uses terse date format on hover

- packages/core/tracing/src/components/trace-viewer/SpanAttribute.vue
- packages/core/tracing/src/components/waterfall/WaterfallScale.vue
- packages/core/tracing/src/components/waterfall/WaterfallSpanBar.vue
- packages/core/tracing/src/components/waterfall/WaterfallView.vue
- packages/core/tracing/src/types/waterfall.ts
This pull request adds support for zooming interaction to the trace viewer.
https://github.com/user-attachments/assets/7eab6362-4a44-40cf-b0be-aa6bfcc2c6b0
- The `left` and `right` attributes of span bars are clamped within the viewport to ensure performance under a high zoom level.
- We will show color at the edge when the view is zoomed in and the span is out of the viewport to indicate that the span is in that direction.
- Cleaned up unused config `viewportShift` in the waterfall view
KM-755
> feat(tracing): allow zooming in trace viewer

- packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue
- packages/entities/entities-shared/src/composables/index.ts
- packages/entities/entities-shared/src/composables/useTableState.ts
- packages/entities/entities-shared/src/index.ts
[KM-827](https://konghq.atlassian.net/browse/KM-827)
Extract the composable for obtaining the `<KTableData>` state and the toolbar show/hide logic from `<EntityBaseTable>`, and export it. This will make it easier to use in scenarios where `<EntityBaseTable>` is not being utilized.
[KM-827]: https://konghq.atlassian.net/browse/KM-827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(entities-shared): add useTableState

- packages/core/tracing/src/components/waterfall/WaterfallSpanBar.vue
- packages/core/tracing/src/components/waterfall/WaterfallView.vue
- packages/core/tracing/src/types/spans.ts
- packages/core/tracing/src/utils/spans.ts
This pull request corrects the position calculation of span bars and fixes the `Cannot read properties of undefined (reading 'x')` error.
This pull request also contains misc bug fixes and clean-ups.
KM-823
> fix(tracing): incorrect span bar position and undefined access error

- packages/core/tracing/src/components/trace-viewer/SpanDescription.vue
This pull request updates the logic to check the availability of an i18n key to avoid printing errors in the console:
> fix(tracing): check i18n key in a better way

- packages/core/expressions/src/monaco.ts
This pull request fixes the issue where the autocompletion was not working while typing inside the parentheses.
|Before|After|
|:-|:-|
|![](https://github.com/user-attachments/assets/fd910b62-fa16-40f2-a077-24f4d7fe102d)|![Screen Recording 2024-12-20 at 11 34 37](https://github.com/user-attachments/assets/b262221d-fe72-4694-b8fa-c242b4484b2a)|
KM-839
> fix(expressions): autocompletion in parentheses

- packages/core/tracing/src/components/trace-viewer/SpanDescription.vue
- packages/core/tracing/src/locales/en.json
- packages/core/tracing/src/utils/spans.ts
This pull request maps the names of some spans to their new names.
KM-837
> fix(tracing): map some span names to their new names

- packages/core/tracing/src/components/trace-viewer/SpanBasicInfo.vue
- packages/core/tracing/src/components/trace-viewer/TraceViewer.vue
This pull request hides the basic info section when no description is available for the selected span to save space.
KM-849
> fix(tracing): hide basic info when no description is available

- .github/workflows/pr-on-close.yaml
- .github/workflows/renovate-auto-approve.yaml
Renaming workflow jobs in order to manually disable old workflows that used `pull_request_trigger`
> ci: rename workflow jobs [KHCP-14529]

- packages/core/app-layout/src/components/AppLayout.vue
Expose the `topOffset` from the `AppLayout` - can be used to determine the top offset for downstream apps
```vue
<template>
<AppLayout ref="appLayout" />
</template>
<script setup lang="ts">
const appLayout = useTemplateRef('appLayout')
// Calculate the top offset for the Learning Hub slideout, always adding 60 to account for the height of the navbar
const learningHubSlideoutTopOffset = computed((): number => (appLayout.value?.topOffset || 0) + 60)
</script>
```
> feat(app-layout): expose top offset

- packages/core/expressions/src/components/ExpressionsEditor.vue
Expose the editor instance for the consuming app.
> feat(expressions): expose editor

- packages/core/forms/sandbox/App.vue
- packages/core/forms/src/components/fields/FieldMultiselect.vue
- packages/core/forms/src/components/fields/FieldRadio.vue
- packages/core/forms/src/components/fields/__tests__/FieldCheckbox.cy.ts
- packages/core/forms/src/components/fields/__tests__/FieldInput.cy.ts
- packages/core/forms/src/components/fields/__tests__/FieldMultiselect.cy.ts
- packages/core/forms/src/components/fields/__tests__/FieldRadio.cy.ts
- packages/core/forms/src/components/fields/__tests__/FieldSelect.cy.ts
- packages/core/forms/src/components/fields/__tests__/FieldSwitch.cy.ts
- packages/core/forms/src/components/fields/__tests__/FieldTextArea.cy.ts
Convert KMultiselect to setup syntax for [KHCP-11341](https://konghq.atlassian.net/browse/KHCP-11341).
Other fixes:
- Add testing of style classes to other entities
- add support for missing props to FieldMultiselect:
- `id`
- `classNames`
- `disabled`
- `name`
- add `data-testid` to KPop
[KHCP-11341]: https://konghq.atlassian.net/browse/KHCP-11341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(field-multiselect): setup syntax [khcp-11341]

- packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
- packages/analytics/analytics-chart/src/components/chart-plugins/ChartTooltip.vue
- packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
- packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
- packages/analytics/analytics-chart/src/composables/useBarChartOptions.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToDatasets.spec.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToDatasets.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToTimeDatasets.ts
- packages/analytics/analytics-chart/src/composables/useExploreResultToTimedDatasets.spec.ts
- packages/analytics/analytics-chart/src/types/chart-data.ts
- packages/analytics/analytics-chart/src/types/chartjs-options.ts
- packages/analytics/analytics-chart/src/utils/colors.ts
- packages/analytics/analytics-chart/src/utils/commonOptions.ts
- Add `isSegmentEmpty` and `isLabelEmpty` to chart data to enable detection of empty entities.
- Refactor generation of various ChartJS properties.
- Removed unused `colorMap` property.
> feat(analytics-chart): style null / empty entities [MA-3510]

- packages/core/app-layout/docs/page-info-section.md
- packages/core/app-layout/sandbox/pages/LayoutPage.vue
- packages/core/app-layout/src/components/pageInfoSection/AppPageInfoSection.cy.ts
- packages/core/app-layout/src/components/pageInfoSection/AppPageInfoSection.vue
- packages/core/app-layout/src/index.ts
Rename AppPageInfoSection component as per discussion in https://github.com/Kong/public-ui-components/pull/1888#discussion_r1910692601
> fix(app-layout): rename apppageinfosection component

- packages/analytics/analytics-chart/README.md
- packages/analytics/analytics-chart/sandbox/pages/ChartDemoSimple.vue
- packages/analytics/analytics-chart/src/components/SimpleChart.cy.ts
- packages/analytics/analytics-chart/src/components/chart-types/GaugeChart.vue
- packages/analytics/analytics-chart/src/enums/chart-metric-display.enum.ts
- packages/analytics/analytics-chart/src/enums/index.ts
- packages/analytics/analytics-chart/src/types/chart-data.ts
- packages/analytics/analytics-utilities/package.json
- packages/analytics/analytics-utilities/src/dashboardSchema.ts
- packages/analytics/analytics-utilities/src/index.ts
- packages/analytics/dashboard-renderer/package.json
- packages/analytics/dashboard-renderer/src/components/BarChartRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.spec.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue
- packages/analytics/dashboard-renderer/src/components/QueryDataProvider.vue
- packages/analytics/dashboard-renderer/src/components/SimpleChartRenderer.vue
- packages/analytics/dashboard-renderer/src/components/TimeseriesChartRenderer.vue
- packages/analytics/dashboard-renderer/src/components/TopNTableRenderer.vue
- packages/analytics/dashboard-renderer/src/types/grid-layout-types.ts
- packages/analytics/dashboard-renderer/src/types/index.ts
- packages/analytics/dashboard-renderer/src/types/renderer-types.ts
- pnpm-lock.yaml
Move dashboard schema definitions to analytics-utilities.
- Update simple chart metric prop to align better with dashboard renderer.
- Move schema definitions from renderer to analytics-utilities.
BREAKING CHANGE: Dashboard schema definitions are in a different package.
BREAKING CHANGE: Simple chart no longer uses an enum for metric display prop.
> refactor(analytics): move dashboard schema [MA-3389]

- packages/core/app-layout/src/components/pageInfoSection/AppPageInfoSection.vue
Fixing AppPageInfoSection deeply slotted table and empty state background color
Before
After
> fix(app-layout): slotted elements style fix

- packages/core/forms/src/components/fields/FieldTextArea.vue
This PR makes the textarea resizable. It also changes the default `rows` to 3 because 2 seems too small.
KM-901
> fix(forms): make textarea resizable

- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
In order to properly test dashboards, elements within the tiles should have a unique `data-testid`. Pass in the `tile-id` to the `DashboardTile` which defaults to the index of the tile in the array of tiles. (It's always available)
> fix(dashboard-renderer): unique data-testid for tile elements

- packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue
Defining `preferencesStorageKey` cause missing prop warning in console. Since `preferencesStorageKey` has a default value, it can be removed.
> chore(entity-base-table): fix missing prop warning

- .github/workflows/renovate-auto-approve.yaml
Temporarily disabling auto-approve for security reasons.
Context: github.actor dependabot or renovate can cause security vulnerabilities. Pausing this auto approval until this can be looked into.
> chore(*): disable auto approve

- packages/entities/entities-plugins/docs/plugin-select.md
- packages/entities/entities-plugins/fixtures/mockData.ts
- packages/entities/entities-plugins/sandbox/pages/PluginSelectPage.vue
- packages/entities/entities-plugins/src/components/PluginSelect.cy.ts
- packages/entities/entities-plugins/src/components/PluginSelect.vue
- packages/entities/entities-plugins/src/components/custom-plugins/DeleteCustomPluginSchemaModal.vue
- packages/entities/entities-plugins/src/components/custom-plugins/PluginCustomGrid.vue
- packages/entities/entities-plugins/src/components/select/PluginSelectCard.vue
- packages/entities/entities-plugins/src/locales/en.json
- packages/entities/entities-plugins/src/plugins-endpoints.ts
- packages/entities/entities-plugins/src/types/plugin-form.ts
- packages/entities/entities-plugins/src/types/plugin.ts
Changes include:
1. Remove `disableCustomPlugins` 
2. A new prop `customPluginSupport` is added to indicate the which type of custom plugin should be created for the CP
3. The plugin grid now renders schema-only and streaming custom plugins correctly.
4. `getCustomEditRoute` now provides `type: 'schema' | 'streaming'` for custom plugin type indication
5. Text and sandbox change
JIRA: KM-895
> feat(entities-plugin): add streaming custom plugin support

- packages/core/expressions/docs/expressions-editor.md
- packages/core/expressions/sandbox/App.vue
- packages/core/expressions/src/components/ExpressionsEditor.vue
- packages/core/expressions/src/index.ts
- packages/core/expressions/src/monaco.ts
- packages/core/expressions/src/types.ts
* `<ExpressionsEditor />` now accepts `rhsValueCompletion` which is made up of `provide` and `shouldProvide`, where the 2nd function accepts an LHS identifier value and returns a `boolean` to indicate whether the RHS value autocompletion is necessary.
* Disposables associated with a `languageId` will now be disposed upon the next registration with the same `languageId`
> feat(expressions): add func to check if rhs autocompletion is necessary; dispose after use

- packages/analytics/analytics-utilities/src/format.ts
- packages/analytics/analytics-utilities/src/timeframes.ts
- packages/analytics/dashboard-renderer/sandbox/pages/DynamicDashboardDemo.vue
- packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- packages/analytics/dashboard-renderer/src/components/QueryDataProvider.vue
- If a tile has a description and a badge, show the badge.
- Generate text of badge based on relative timeframe description or absolute time range.
- Add timeframe lookup to analytics-utilities.
- Fix dashboard renderer sandbox.
- Make tiles with overridden timeframes ignore the global time when issuing queries.
> feat(dashboard-renderer): show badge for timeframe overrides [MA-3562]

- packages/entities/entities-shared/docs/entity-empty-state.md
- packages/entities/entities-shared/sandbox/pages/EntityEmptyStatePage.vue
- packages/entities/entities-shared/src/components/entity-empty-state/EntityEmptyState.vue
- packages/entities/entities-shared/src/types/entity-empty-state.ts
Summary
JIRA : https://konghq.atlassian.net/browse/KHCP-14905
- Added _appearance_  prop with 'primary' and 'secondary' options to support L2 empty states. The secondary appearance has a slightly smaller title font size.
- Fixed feature cards taking up unnecessary space when features are empty.
> feat(entityemptystate): added appreance prop support [KHCP-14905]

- package.json
- pnpm-lock.yaml
Bumps all vitest packages as recommended to patch security vulnerability:
- https://x.com/vitest_dev/status/1886691304039489773
- https://github.com/vitest-dev/vitest/security/advisories/GHSA-9crc-q9x8-hgqq
> chore: bump vitest

- packages/entities/entities-plugins/docs/plugin-list.md
- packages/entities/entities-plugins/src/components/PluginList.vue
- packages/entities/entities-plugins/src/locales/en.json
JIRA Ticket : https://konghq.atlassian.net/browse/KHCP-14824
Updated Plugins Empty State
Konnect Adoption Preview : https://pr-5720--gateway-manager.cloud-preview.konghq.tech/us/gateway-manager
Konnect PR : https://github.com/Kong/konnect-ui-apps/pull/5720
FF : khcp-14756-empty-states-m2
> feat: plugins list empty state

- packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
https://konghq.atlassian.net/browse/MA-3645
Also add a tooltip when title is truncated
> fix: tile header overflow issue

- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-plugins/src/definitions/schemas/AIProxyAdvanced.ts
Fixing a bug where `vectordb` or `embeddings` will be set to `null` when editing an `ai-proxy-advanced` plugin.
KM-945
> fix(entities-plugins): fields set to null

- packages/analytics/analytics-utilities/src/dashboardSchema.ts
- packages/analytics/dashboard-renderer/package.json
- packages/analytics/dashboard-renderer/sandbox/index.ts
- packages/analytics/dashboard-renderer/sandbox/pages/DynamicDashboardDemo.vue
- packages/analytics/dashboard-renderer/sandbox/pages/EditableDashboardDemo.vue
- packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- packages/analytics/dashboard-renderer/src/components/layout/DraggableGridLayout.vue
- packages/analytics/dashboard-renderer/src/icons/arrows_more_down.svg
- packages/analytics/dashboard-renderer/src/locales/en.json
https://konghq.atlassian.net/browse/MA-3668
https://konghq.atlassian.net/browse/MA-3622
https://konghq.atlassian.net/browse/MA-3621
- Tiles passed into the gridstack grid layout component inform the initial state of the dashboard.
- Use a copy of the passed in tiles in order to prevent circular event loops
- Gridstack responsible for all things related to position and dimensions of tiles. On the appropriate gridstack events, regenerate tile definitions with updated layout and emit them so the host app can update the dashboard definition
- Watch for changes to provided tile's length to handle adding new tiles. Wait for the dom to be updated `await nextTick()` then use `makeWidget` to make the newly added tile into a gridstack widget.
- Watch for changes to the provided tile's metadata and …
> fix: handle adding/removing tiles (widgets)

- packages/core/tracing/src/components/lifecycle/LifecycleEdgeSeamlessSmoothstep.vue
- packages/core/tracing/src/components/lifecycle/LifecycleLegend.vue
- packages/core/tracing/src/components/lifecycle/LifecycleView.vue
- packages/core/tracing/src/components/lifecycle/LifecycleViewNode.vue
- packages/core/tracing/src/components/payload/PayloadDisplay.vue
- packages/core/tracing/src/constants/lifecycle.ts
- packages/core/tracing/src/locales/en.json
- packages/core/tracing/src/partials/SummaryViewTab.vue
- packages/core/tracing/src/types/lifecycle.ts
- packages/core/tracing/src/types/payloads.ts
- packages/core/tracing/src/utils/lifecycle.ts
* Implement the new design for the lifecycle view
* Custom layout function
* Fix the fit viewport helper to keep clear from the actions toolbar and legend
KM-939
|Full flow|
|:-|
|<img width="1171" alt="Screenshot 2025-02-13 at 18 06 16" src="https://github.com/user-attachments/assets/04722835-796e-42c5-9a81-44c98792f814" />|
|Flow without pre-upstream plugins|
|:-|
|<img width="1170" alt="Screenshot 2025-02-13 at 18 06 46" src="https://github.com/user-attachments/assets/0649f2bf-6ec4-4a88-8de8-6c129ba24cf1" />|
|Flow without post-upstream plugins|
|:-|
|<img width="1173" alt="Screenshot 2025-02-13 at 18 06 33" src="https://github.com/user-attachments/assets/d2b4d49f-ee4d-43fe-8f71-57309fea624d" />|
|Flow without pre and post-upstream phases|
|:-|
|<img width="1173" alt="Screenshot …
> feat(tracing): display more info in the lifecycle view

- packages/entities/entities-consumer-groups/docs/consumer-group-list.md
- packages/entities/entities-consumer-groups/sandbox/pages/ConsumerGroupListPage.vue
- packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.cy.ts
- packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
- packages/entities/entities-consumer-groups/src/locales/en.json
- packages/entities/entities-consumers/docs/consumer-list.md
- packages/entities/entities-consumers/sandbox/pages/ConsumerListPage.vue
- packages/entities/entities-consumers/src/components/ConsumerList.vue
- packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue
New empty state usage in consumer groups.
Part of [KHCP-14827](https://konghq.atlassian.net/browse/KHCP-14827).
Preview: https://github.com/Kong/konnect-ui-apps/pull/5741
[KHCP-14827]: https://konghq.atlassian.net/browse/KHCP-14827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(consumer-groups): new empty state [khcp-14827]

- packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
- packages/analytics/analytics-chart/src/composables/useLineChartOptions.spec.ts
- packages/analytics/analytics-chart/src/composables/useLineChartOptions.ts
- packages/analytics/analytics-chart/src/types/chartjs-options.ts
- packages/analytics/analytics-chart/src/utils/commonOptions.spec.ts
- packages/analytics/analytics-chart/src/utils/commonOptions.ts
Second attempt at: https://github.com/Kong/public-ui-components/pull/1872
When a line chart is asked to display a single data point, display that datapoint with a radius smaller than the hover radius instead of displaying a deceptive "No data" error.
Test dataset:
```
{
"data": [
{
"event": {
"request_count": 100000
},
"timestamp": "2024-12-23T07:00:00.000Z"
}
],
"meta": {
"start_ms": 1734937200000,
"end_ms": 1735023600000,
"limit": 50,
"granularity_ms": 86400000,
"metric_names": [
"request_count"
],
"truncated": false,
"display": {},
"metric_units": {
"request_count": "count"
}
}
}
```
Before:
After:
> fix(analytics-chart): render timeseries charts with a single point [MA-2682]

- packages/entities/entities-keys/src/components/KeyForm.vue
This PR removes the character limit on all `<KTextArea>` instances on the key form page.
KM-907
> fix(entities-keys): text area char limit

- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
Addresses: https://konghq.atlassian.net/browse/MA-3523
Make sure dashboard dropdown only renders when it has items
Before
After
1. Open [adoption PR](https://github.com/Kong/konnect-ui-apps/pull/5876) preview deployment
2. Head to service catalog -> service  -> dashboard tab
3. Gateway manager chart dashboard renderer should not have the dropdown menu
> fix(dashboard-renderer): empty csv export dropdown [MA-3523]

- packages/core/app-layout/src/components/sidebar/SidebarItem.vue
Addresses: https://konghq.atlassian.net/browse/TDX-5119
Fix `itemHasBadge` computed logic in SidebarItem component so that it doesn't give a false positive when `badgeCount` is 0 (in which case badge isn't rendered but truncation class is applied)
Before
After
> fix(app-layout): fix subnav item badge condition [TDX-5119]

- packages/analytics/analytics-utilities/package.json
- packages/analytics/analytics-utilities/src/types/query-bridge.ts
- packages/analytics/dashboard-renderer/package.json
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
- packages/analytics/dashboard-renderer/src/components/FallbackEntityLink.vue
- packages/analytics/dashboard-renderer/src/components/TopNTableRenderer.vue
- pnpm-lock.yaml
- Move `ajv` to a dev dependency, since it's only used in the sandbox [MA-3247]
- Don't require `entities-shared` since it's a large package that's only useful within Konnect [MA-3246]
- Create a component registry in the analytics bridge that allows the host app to provide optional components.
- Attempt to fetch `EntityLink` from the bridge; if it's not available, provide a fallback.
[MA-3247]: https://konghq.atlassian.net/browse/MA-3247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MA-3246]: https://konghq.atlassian.net/browse/MA-3246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dashboard-renderer): reduce required dependencies

- packages/core/tracing/sandbox/fixtures/trace-batches.json
- packages/core/tracing/src/components/lifecycle/LifecycleView.vue
- packages/core/tracing/src/components/lifecycle/LifecycleViewNode.vue
- packages/core/tracing/src/constants/lifecycle.ts
- packages/core/tracing/src/constants/spans.ts
- packages/core/tracing/src/locales/en.json
- packages/core/tracing/src/types/lifecycle.ts
- packages/core/tracing/src/utils/lifecycle.ts
- packages/core/tracing/src/utils/spans.ts
This pull request splits the "Upstream" node into three nodes
* Incorrect node ordering
* Request/Response group will show a message if empty
* Use the dotted background
KM-959
> feat(tracing): split upstream node into three nodes

- packages/core/tracing/src/utils/lifecycle.ts
Fix an issue where the durations on client in/out nodes were swapped
KM-975
> fix(tracing): swap incorrect durations on client in/out nodes

- packages/analytics/dashboard-renderer/src/components/layout/DraggableGridLayout.vue
Changes to a tile's meta properties are done externally so whenever props.tiles changes it needs to be synced with the internal map.
> fix: keep tiles prop and map synced

- .github/workflows/auto-assignee.yml
This PR added a CI workflow to auto-assign the PR's author as an assignee.
It can help us easily identify whose PR it is.
KM-1010
> chore: auto-assign PR author as assignee [KM-1010]

- packages/core/forms/src/components/fields/FieldArray.vue
- packages/core/forms/src/components/fields/FieldInput.vue
This reverts commit 92a7ec26bbc5898e93191f0b214b9bbdd2e4a55d.
KAG-6576
We need to pass `NaN` to form component for it to function as expected, save `null` value when number input is cleared.
> Revert "fix(forms): use Number.isFinite (#1996)"

- packages/entities/entities-plugins/src/components/PluginForm.vue
KAG-6576
Since we only need to override redis fields when a partial is selected, we use PUT when partials is set and redis field is removed from request. In other cases(partials is null or partials is not set in request), we will be using PATCH like before in Kong Manager.
> fix(plugin-form): only use put when partials field is passed for plugin

- packages/entities/entities-upstreams-targets/src/components/UpstreamsForm.cy.ts
- packages/entities/entities-upstreams-targets/src/components/UpstreamsForm.vue
- packages/entities/entities-upstreams-targets/src/components/UpstreamsFormActiveHealthCheck.cy.ts
- packages/entities/entities-upstreams-targets/src/components/UpstreamsFormActiveHealthCheck.vue
- packages/entities/entities-upstreams-targets/src/components/UpstreamsFormPassiveHealthCheck.cy.ts
- packages/entities/entities-upstreams-targets/src/components/UpstreamsFormPassiveHealthCheck.vue
- packages/entities/entities-upstreams-targets/src/composables/useHelpers.ts
- packages/entities/entities-upstreams-targets/src/types/upstreams-form.ts
This PR mainly addresses the following issues:
• It fixes the problem where some field values (`client_cerficate`, `tags`, `http_sni`, and `host_header` etc.) cannot be set to null during editing.
• It refactors the type definitions for active health and passive health to avoid confusion between the definitions of Active and Passive.
KM-970
FTI-6493
> fix(upstreams): unable remove some fields' value [KM-970]

- packages/entities/entities-upstreams-targets/src/components/UpstreamsForm.cy.ts
- packages/entities/entities-upstreams-targets/src/components/UpstreamsForm.vue
This PR fixed where disabling the active healthy didn't include the timeout field in the request body.
> fix(upstreams-targets): should returns timeouts disable active health [KM-1056]

- packages/core/forms/src/components/forms/OIDCForm.vue
- packages/core/forms/src/components/forms/__tests__/OIDCForm.spec.ts
KM-1067
OIDC form doesn't select default values of auth methods, and the UI is inconsistent with form model
> fix(forms): fix oidc form UI-model consistency

- packages/analytics/analytics-utilities/src/types/explore/advanced.ts
regoinal/external consumers will be exposed via the `consumers` dimension.
> fix(ext-consumers-are-consumers): Adding realm instead of regional_consumer

- packages/core/forms/src/components/RedisConfigSelect.vue
KM-1087
Pre select of redis config should not be blocked by `loadConfigs`. If the network is too slow, this could cause late update of form model after user toggles to inline redis config fields.
> fix(redis): unblock preselect of default redis config

- packages/analytics/analytics-chart/sandbox/pages/TimeSeriesChartDemo.vue
- packages/analytics/analytics-utilities/src/types/query-bridge.ts
- packages/analytics/dashboard-renderer/sandbox/sandbox-query-provider.ts
- packages/analytics/dashboard-renderer/src/components/BaseAnalyticsChartRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardTile.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- Allow permissions checks to happen before generating an explore URL.
- Clean up dead code.
BREAKING CHANGE: change signature of analytics bridge
> feat(analytics): make explore URL determination async [MA-3590]

- packages/entities/entities-shared/fixtures/mockData.ts
- packages/entities/entities-shared/sandbox/pages/ConfigCardItemPage.vue
- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.cy.ts
- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.vue
- packages/entities/entities-shared/src/components/entity-base-config-card/EntityBaseConfigCard.cy.ts
[KM-1066](https://konghq.atlassian.net/browse/KM-1066)
| -- | -- |
| <img width="1626" alt="image" src="https://github.com/user-attachments/assets/e7d8c906-6ab0-4b72-b34d-aa09922a4eab" /> | <img width="1626" alt="image" src="https://github.com/user-attachments/assets/88d12577-57ed-4aac-bd18-a88febd7fe62" /> |
[KM-1066]: https://konghq.atlassian.net/browse/KM-1066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(entities-shared): improve display for config card json text

- packages/core/forms/README.md
- packages/core/forms/sandbox/App.vue
- packages/core/forms/sandbox/CatFoodField.vue
- packages/core/forms/src/components/FormGroup.vue
- packages/core/forms/src/components/fields/FieldArray.vue
- packages/core/forms/src/composables/useAbstractFields.ts
- packages/core/forms/src/index.ts
- packages/core/forms/src/types/form-fields.ts
In this PR, we expose a `component` field in the `FormFieldSchema`, which can point to a Vue component and override the default field render.
This gives us more flexibility when handling complex requirements
Test result:
* Konnect adoption test: https://github.com/Kong/konnect-ui-apps/pull/6264
* Kong admin adoption test: https://github.com/Kong/kong-admin/pull/3837
* Kong admin cross browser test: https://github.com/Kong/kong-admin/actions/runs/14079674561
JIRA: KM-1035
> feat(vfg): introduce custom field component

- packages/analytics/analytics-chart/sandbox/index.ts
- packages/analytics/analytics-chart/sandbox/pages/MultiChartDemo.vue
- packages/analytics/analytics-chart/src/components/chart-plugins/DragSelectPlugin.ts
- packages/analytics/analytics-chart/src/components/chart-plugins/HighlightPlugin.ts
- packages/analytics/analytics-chart/src/components/chart-plugins/VerticalLinePlugin.ts
- packages/analytics/analytics-chart/src/components/chart-types/DonutChart.vue
- packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
- packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
- packages/analytics/analytics-chart/src/composables/useBarChartOptions.ts
- packages/analytics/analytics-chart/src/composables/useDonutChartOptions.ts
- packages/analytics/analytics-chart/src/composables/useLineChartOptions.ts
- packages/analytics/analytics-chart/src/types/chartjs-options.ts
https://konghq.atlassian.net/browse/MA-3723
- Add a new sandbox page displaying multiple charts
- Refactored plugins to use class-based instances. Each chart now creates its own plugin instance rather than relying on a shared singleton.
- Custom tooltip positioning logic was leaking between chart instances of the same type. This was due to Chart.js requiring custom tooltip positioners to be registered globally. As a result, the shared positioner always accessed tooltipState from the last chart instance of that chart type, leading to unexpected behavior. To fix this, each chart instance registers its own unique positioner function. See https://konghq.atlassian.net/browse/MA-3820 
- Cleanup tooltip positioners `onUnomunted`
> fix: custom chart plugin states leaking across chart instances

- packages/entities/entities-upstreams-targets/src/components/TargetForm.vue
KM-1156
Upstream target form has wrong style inheritance so that is shows white background.
**Before:**
**After:**
> fix(style): fix style in upstream target form

- packages/entities/entities-gateway-services/src/index.ts
The useUrlValidators composable was exported to improve reusability, as part of [this PR](https://github.com/Kong/konnect-ui-apps/pull/6363).
> chore: export gateway service composables

- packages/analytics/analytics-utilities/src/types/explore/requests.ts
this allows realm for api requests as well (while not being part of the realm/consumer stuff elsewhere)
> feat(realm): adding in realm into api-requests responses

- packages/analytics/analytics-utilities/src/types/explore/ai.ts
no other dimension includes the `_id` suffix
> fix(ai_plugin): remove the _id portion

- packages/analytics/dashboard-renderer/sandbox/mock-data.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
Column count should remain fixed; don't reduce the number of columns if a definition doesn't use them all.
> fix(dashboards): don't auto-adjust column count [MA-3855]

- packages/analytics/analytics-chart/sandbox/pages/BarChartDemo.vue
- packages/analytics/analytics-chart/sandbox/pages/DonutChartDemo.vue
- packages/analytics/analytics-chart/sandbox/pages/TimeSeriesChartDemo.vue
- packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
- packages/analytics/analytics-utilities/src/utils/chartDataGenerator.ts
Fixes [MA-3830](https://konghq.atlassian.net/browse/MA-3830) and [MA-1889](https://konghq.atlassian.net/browse/MA-1889).
* Limit/truncate warning tooltip works when hovering over the icon
* Tooltip content is restricted to 50% viewport width so it doesn't bleed off screen
* Sandbox "No Limit" toggle now actually does something
The tooltip wasn't working before because if an icon has the `decorative` prop, it applies the css `pointer-events: none` which means hover effects don't actually trigger. In this case, the icon was the only component that could trigger the tooltip. Merely wrapping it in a `<div>` would have fixed it as well, but I figured it was better to just remove the `decorative` prop.
"No Limit" I don't think has been working [since …
> fix: show tooltip on warning icon and limit size ma-3830 ma-1889

- packages/entities/entities-plugins/sandbox/pages/PluginFormPlayground.vue
- packages/entities/entities-plugins/src/components/fields/KeyAuthIdentityRealms.vue
This is a workaround to address a DP-side identity realm issue https://kongstrong.slack.com/archives/C06FJ632KJS/p1745429119460859
JIRA: KM-1205
> fix(key-auth-plugin): temporary add region info to the realm scope

- packages/core/app-layout/sandbox/pages/PageHeaderPage.vue
- packages/core/app-layout/src/components/aboutSection/AppAboutSection.cy.ts
- packages/core/app-layout/src/components/aboutSection/AppAboutSection.vue
This can help us do more customization on the title of the `<AppAboutSection />` component.
The `defineProps` now changes to the TypeScript-style definition with `withDefaults`, which makes Cypress typing system happy in the component test file
JIRA: KM-1134
> feat(app-layout): expose slot `title` for `<AppAboutSection />`

- packages/analytics/analytics-chart/src/components/SimpleChart.cy.ts
- packages/analytics/analytics-chart/src/components/SimpleChart.vue
Addresses: https://konghq.atlassian.net/browse/KHCP-16024
When metric value is `null`, show empty state instead of error message in SingleValue chart
https://github.com/user-attachments/assets/78a62887-36a1-4772-8dfa-c1a28990d4db
> fix(analytics): single value chart show empty when null [KHCP-16024]

- packages/analytics/dashboard-renderer/package.json
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardTile.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- packages/analytics/dashboard-renderer/src/locales/en.json
Satisfies [MA-3824](https://konghq.atlassian.net/browse/MA-3824)
* Add a `duplicate-tile` event to `<DashboardTile>`
* Bubble up the `duplicate-tile` event in `<DashboardRenderer>` - anything that uses DashboardRenderer will need to handle this event.
* Slightly refactor `DashboardTile.cy.ts` to have a common `mount` method so that the tests are easier to read.
* **fix**: long tile titles looked very bad (visible in prod). Now they don't.
In action:
https://github.com/user-attachments/assets/036caf05-9563-49e7-bbbf-783f2a6b4c96
**Before tile title fix:**
**After tile title fix:**
[MA-3824]: https://konghq.atlassian.net/browse/MA-3824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(analytics): support dashboard tile duplication [ma-3824]

- packages/entities/entities-routes/src/components/RouteFormExpressionsEditor.vue
- packages/entities/entities-routes/src/components/RouteFormExpressionsEditorLoader.vue
> fix(entities-routes): expressions playground tooltip on entry

- packages/entities/entities-plugins/src/components/free-form/RequestCallout/ConfigForm.vue
- packages/entities/entities-plugins/src/components/free-form/RequestCallout/RequestCalloutForm.vue
- packages/entities/entities-plugins/src/components/free-form/shared/PluginFormWrapper.vue
[KM-1261](https://konghq.atlassian.net/browse/KM-1261)
Creating a common plugin form wrapper from the request callout form to reuse it in other free forms.
[KM-1261]: https://konghq.atlassian.net/browse/KM-1261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(request-callout): extract plugin wrapper as a shared component

- packages/entities/entities-routes/docs/route-form-rules-composer.md
- packages/entities/entities-routes/src/components/RouteFormRulesComposer.vue
Adding a prop to hide the protocols selector. It is useful in AI Manager.
KM-1266
> feat(entities-routes): add prop to hide the protocols selector

- packages/entities/entities-certificates/src/components/CACertificateList.vue
- packages/entities/entities-certificates/src/components/CertificateList.vue
- packages/entities/entities-consumer-credentials/src/components/ConsumerCredentialList.vue
- packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
- packages/entities/entities-consumers/src/components/ConsumerList.vue
- packages/entities/entities-gateway-services/src/components/GatewayServiceList.vue
- packages/entities/entities-key-sets/src/components/KeySetList.vue
- packages/entities/entities-keys/src/components/KeyList.vue
- packages/entities/entities-plugins/src/components/PluginList.vue
- packages/entities/entities-redis-configurations/src/components/RedisConfigurationList.vue
- packages/entities/entities-routes/src/components/RouteList.vue
- packages/entities/entities-shared/src/composables/useFetchUrlBuilder.ts
- packages/entities/entities-shared/src/composables/useFetcher.ts
- packages/entities/entities-snis/src/components/SniList.vue
- packages/entities/entities-upstreams-targets/src/components/TargetsList.vue
- packages/entities/entities-upstreams-targets/src/components/UpstreamsList.vue
- packages/entities/entities-vaults/src/components/SecretListInner.vue
- packages/entities/entities-vaults/src/components/VaultList.vue
This PR fixes a bug where `config` reactivity is lost in `useFetchUrlBuilder`.
KM-920
KM-1264
> fix(entities): fetcher url reactivity

- packages/entities/entities-plugins/src/components/free-form/RequestCallout/ConfigForm.vue
- packages/entities/entities-plugins/src/components/free-form/RequestCallout/types.ts
- packages/entities/entities-plugins/src/components/free-form/shared/AdvancedFields.vue
- packages/entities/entities-plugins/src/components/free-form/shared/EnumField.vue
- packages/entities/entities-plugins/src/components/free-form/shared/Field.vue
- packages/entities/entities-plugins/src/components/free-form/shared/PluginFormWrapper.vue
- packages/entities/entities-plugins/src/components/free-form/shared/StringField.vue
- packages/entities/entities-plugins/src/components/free-form/shared/TagField.vue
- packages/entities/entities-plugins/src/components/free-form/shared/composables.ts
- packages/entities/entities-plugins/src/components/free-form/shared/utils.ts
- packages/entities/entities-plugins/src/locales/en.json
[KM-1265](https://konghq.atlassian.net/browse/KM-1265)
Let the three fixed advanced fields (instance_name, tags and protocols) be handled by the free form.
[KM-1265]: https://konghq.atlassian.net/browse/KM-1265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(free-form): handle advanced fields in free form [KM-1265]

- packages/entities/entities-shared/docs/config-card-display.md
- packages/entities/entities-shared/sandbox/pages/EntityBaseConfigCardPage.vue
- packages/entities/entities-shared/src/components/entity-base-config-card/EntityBaseConfigCard.vue
- packages/entities/entities-shared/src/types/entity-base-config-card.ts
This pull request adds an optional prop to persist the format preference. When omitted, the preference will not be persisted.
KM-1278
> feat(entities-shared): add a prop to persist format preference

- packages/entities/entities-consumer-groups/src/components/ConsumerGroupForm.vue
Stop fetching consumers data when the consumer field is hidden from the user.
> feat(consumer-groups): stop fetching the consumers when no need

- packages/entities/entities-shared/docs/entity-base-table.md
- packages/entities/entities-shared/src/components/entity-base-table/EntityBaseTable.vue
EntityBaseTable component changes:
- deprecate `disablePaginationPageJump` prop (still supported for backwards compatibility) in favour of new `paginationAttributes` prop
- deprecate `paginationType` prop (still supported for backwards compatibility) in favour of new `paginationAttributes` prop
- introduce `paginationAttributes` prop
- introduce `hidePaginationWhenOptional` prop
> feat(entities-shared): replace pagination props

- packages/entities/entities-plugins/src/components/free-form/RequestCallout/ConfigForm.vue
- packages/entities/entities-plugins/src/components/free-form/RequestCallout/types.ts
- packages/entities/entities-plugins/src/components/free-form/shared/PluginFormWrapper.vue
- packages/entities/entities-plugins/src/types/plugins/free-form.ts
* Fixing the `scope` can't be updated when users edit a plugin.
* Optimizing the type definition of free form `data` props
> fix(free-form): scope data overwritten by free form

- packages/entities/entities-vaults/src/components/VaultForm.vue
- packages/entities/entities-vaults/src/locales/en.json
- packages/entities/entities-vaults/src/types/vault-form.ts
[KM-1191](https://konghq.atlassian.net/browse/KM-1191)
* Add `auth_type` to the payload but hide it in the UI.
* Add `account`.
* Add new Conjur Icon.
* Rename `api_token` to `api_key`.
[KM-1191]: https://konghq.atlassian.net/browse/KM-1191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(entities-vault): adjustment fields of conjur [KM-1191]

- packages/entities/entities-vaults/src/components/VaultForm.vue
Add `base64_decode` to the HCV payload when it is available.
> fix(vault-form): missing base64 decode in hcv

- packages/analytics/analytics-utilities/src/dashboardSchema.ts
- packages/analytics/analytics-utilities/src/format.ts
- packages/analytics/dashboard-renderer/README.md
- packages/analytics/dashboard-renderer/sandbox/mock-data.ts
- packages/analytics/dashboard-renderer/sandbox/pages/EditableDashboardDemo.vue
- packages/analytics/dashboard-renderer/sandbox/pages/RendererDemo.vue
- packages/analytics/dashboard-renderer/sandbox/sandbox-query-provider.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.spec.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
- packages/analytics/dashboard-renderer/src/components/TopNTableRenderer.vue
- packages/analytics/dashboard-renderer/src/components/layout/DraggableGridLayout.cy.ts
- packages/analytics/dashboard-renderer/src/components/layout/DraggableGridLayout.vue
- packages/analytics/dashboard-renderer/src/components/layout/GridLayout.vue
- packages/analytics/dashboard-renderer/src/components/layout/grid-utils.spec.ts
- packages/analytics/dashboard-renderer/src/components/layout/grid-utils.ts
- packages/analytics/dashboard-renderer/src/constants.ts
- packages/analytics/dashboard-renderer/src/types/grid-layout-types.ts
[satisfies ma-3916](https://konghq.atlassian.net/browse/MA-3916)
* set default columns in a dashboard to 6 (using the `DASHBOARD_COLS` constant
* remove `gridSize` everywhere it exists in this repo
* calculate the values of gridsize where it was used from tile definitions instead
After this is merged, will need to merge the following PRs as well, please consider reviewing them:
* https://github.com/Kong/flink-jobs/pull/1639
* https://github.com/Kong/konnect-ui-apps/pull/6829
* https://github.com/Kong/kanalytics/pull/948
* https://github.com/Kong/portal/pull/1120
> feat: make gridSize optional (and unused) calculate from tiles instead [ma-3916]

- packages/analytics/dashboard-renderer/src/components/layout/DraggableGridLayout.vue
Fix [MA-3955](https://konghq.atlassian.net/browse/MA-3955)
Gridstack automatically applies positioning to each tile within the stack, which in turn will move the tile inwards 10px on all sides. Within our container for the page, this would leave a 10px space on each side of the full width container causing the tiles to never line up properly with the rest of a page layout.
This will add negative margin to all sides of the `DraggableGridLayout` component.
**Before**
**After**
[MA-3955]: https://konghq.atlassian.net/browse/MA-3955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add negative margin to override gridstack gutters [MA-3955]

- packages/entities/entities-plugins/src/composables/useSchemas.ts
- packages/entities/entities-plugins/src/definitions/schemas/Confluent.ts
- packages/entities/entities-plugins/src/definitions/schemas/ConfluentConsume.ts
- packages/entities/entities-plugins/src/definitions/schemas/KafkaConsume.ts
- packages/entities/entities-plugins/src/definitions/schemas/KafkaLog.ts
- packages/entities/entities-plugins/src/definitions/schemas/KafkaUpstream.ts
- packages/entities/entities-plugins/src/types/plugin-form.ts
- packages/entities/entities-plugins/src/utils/helper.ts
A new field `schema_registry` was [added](https://github.com/Kong/gateway-schema-watcher/pull/141) to 5 plugins: we are facing the same problem as `ai-proxy-advanced` where a non-required parent object has required fields. Before submitting, we need to check the payload and delete the parent object if it's empty.
https://github.com/user-attachments/assets/e8779b03-d65d-422b-88f5-45283c91e071
> fix(entities-plugins): delete empty `basic` before submitting

- packages/entities/entities-plugins/src/components/free-form/Datakit/DatakitForm.vue
[KM-1304](https://konghq.atlassian.net/browse/KM-1304)
This PR adds a code example for Datakit YAML editor when users are creating a plugin instance.
[KM-1304]: https://konghq.atlassian.net/browse/KM-1304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(plugins): add code example for datakit yaml editor

- packages/analytics/analytics-chart/src/components/chart-plugins/ChartTooltip.vue
- packages/analytics/analytics-chart/src/components/chart-types/DonutChart.vue
- packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
- packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
- packages/analytics/analytics-chart/src/composables/index.ts
- packages/analytics/analytics-chart/src/composables/useTooltipAbsolutePosition.ts
https://konghq.atlassian.net/browse/MA-3663
- Teleport tooltip to body, adjust position relative to chart parent container.
- Prevent tooltip drag from selecting text on the page
> fix: chart tooltip cutoff when dragged outside chart boundary

- packages/entities/entities-consumer-groups/docs/consumer-group-list.md
- packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.cy.ts
- packages/entities/entities-consumer-groups/src/components/ConsumerGroupList.vue
- packages/entities/entities-consumers/docs/consumer-list.md
- packages/entities/entities-consumers/src/components/ConsumerList.cy.ts
- packages/entities/entities-consumers/src/components/ConsumerList.vue
**Description:**
This PR is dedicated to cleaning up the feature flag `khcp-14756-empty-states-m2`.
**Entities Cleaned Up:**
* **Cosumers**
* **Cosumer Groups**
> chore(consumers): cleaned up feature flags

- packages/core/tracing/sandbox/pages/TraceViewPage.vue
- packages/core/tracing/src/components/trace/SpanBasicInfo.vue
- packages/core/tracing/src/partials/TraceViewTab.vue
We need to add a prop to `TraceViewTab` to disable the "View span logs" button because the feature is behind a feature flag
https://github.com/user-attachments/assets/7395077b-9574-4f66-8417-7611aff317c6
> feat(tracing): add prop for view span logs button [KHCP-16669]

- packages/core/forms/sandbox/index.ts
- packages/core/forms/src/components/FormGenerator.vue
- packages/core/forms/src/components/fields/FieldAdvanced.vue
- packages/core/forms/src/components/fields/FieldObject.vue
- packages/core/forms/src/components/fields/FieldObjectAdvanced.vue
- packages/core/forms/src/components/fields/FieldSelectionGroup.vue
- packages/core/forms/src/index.ts
- packages/core/forms/vfg.md
- packages/entities/entities-plugins/package.json
- packages/entities/entities-plugins/sandbox/index.ts
- packages/entities/entities-plugins/src/components/PluginEntityForm.vue
- packages/entities/entities-plugins/src/components/PluginForm.cy.ts
- packages/entities/entities-plugins/src/index.ts
- packages/entities/entities-plugins/vite.config.ts
- pnpm-lock.yaml
Two packages were affected by this change:
- `@kong-ui-public/entities-plugins`
* This package already had the `@kong-ui-public/forms` dependency, so it was straightforward to use the `VueFormGenerator` component locally. The re-export of the `VueFormGenerator` component was removed from this package. Tests were updated accordingly.
- `@kong-ui-public/forms`
* Fields implemented in the options-style previously had to use the globally registered `<vue-form-generator>` to avoid circular dependencies. This behavior was difficult to track in the past. Now, for options-style components, we use `<script setup>` to import  `<VueFormGenerator>` and explicitly declare the `expose` in the `<script>` section.
* `VueFormGenerator` was no longer recommended to be used as a global component. So the Vue …
> refactor: avoid declaring the `VueFormGenerator` gloablly

- packages/entities/entities-routes/src/index.ts
- packages/entities/entities-routes/src/utilities/helpers.ts
This PR exports utility functions so that the consuming apps can leverage them. Plus, `isRoutePayloadValid` is removed because it is not used anywhere, and the logic itself is problematic.
> feat(entities-routes): export utils

- packages/entities/entities-routes/src/components/rules-composer/TraditionalRules.vue
- packages/entities/entities-routes/src/components/rules-composer/rules/DestinationRules.vue
- packages/entities/entities-routes/src/components/rules-composer/rules/HeaderRules.vue
- packages/entities/entities-routes/src/components/rules-composer/rules/HostRules.vue
- packages/entities/entities-routes/src/components/rules-composer/rules/MethodRules.vue
- packages/entities/entities-routes/src/components/rules-composer/rules/PathRules.vue
- packages/entities/entities-routes/src/components/rules-composer/rules/SniRules.vue
- packages/entities/entities-routes/src/components/rules-composer/rules/SourceRules.vue
- packages/entities/entities-routes/src/locales/en.json
1. Removed "Prefix with \`~\` to enable regex-based matching." from the tooltip for `hosts`.
2. Added code format support for route form tooltips.
KM-1398
> fix(entities-routes): update form tooltip content

- packages/entities/entities-gateway-services/src/components/GatewayServiceForm.vue
- packages/entities/entities-gateway-services/src/components/LegacyGatewayServiceForm.vue
- packages/entities/entities-gateway-services/src/types/gateway-service-form.ts
This PR fixes a bug where editing a "disabled" service will enable it after saving.
KM-1475
> fix(entities-gateway-services): edit disabled service

- packages/core/app-layout/sandbox/pages/SidebarPage.vue
- packages/core/app-layout/src/components/sidebar/AppSidebar.vue
- packages/core/app-layout/src/types/sidebar.ts
Support grouped L1 sidebar navigation items.
> feat(app-layout): grouped sidebar l1 items [KHCP-16758]

- packages/entities/entities-plugins/package.json
- packages/entities/entities-plugins/src/components/free-form/Datakit/CodeEditor.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/DatakitForm.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/visual-editor/composables.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/visual-editor/modal/EditorContent.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/visual-editor/modal/EditorMain.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/visual-editor/modal/EditorModal.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/visual-editor/modal/EditorNav.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/visual-editor/modal/EditorPanel.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/visual-editor/types.ts
- packages/entities/entities-plugins/src/components/free-form/shared/FormSection.vue
- packages/entities/entities-plugins/src/components/free-form/shared/layout/StandardLayout.vue
- packages/entities/entities-plugins/src/locales/en.json
- packages/entities/entities-plugins/vite.config.ts
- pnpm-lock.yaml
[KM-1453](https://konghq.atlassian.net/browse/KM-1453)
[KM-1455](https://konghq.atlassian.net/browse/KM-1455)
In this PR:
- Refactored `StandardLayout` to allow adding the editor mode toggle.
- Extracted the YAML code editor into a separate component.
- Added a toggle between code editor and visual editor, with the preference saved to `localStorage`
- Implemented basic functionality to open the visual editor modal from the plugin form
- Built the initial layout and interactions for the editor modal, including sidebar toggle and overall structure, scroll locking, focus trapping, etc.
[KM-1453]: https://konghq.atlassian.net/browse/KM-1453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KM-1455]: …
> feat(entities-plugins): datakit visual editor modal

- packages/entities/entities-routes/src/components/RouteForm.cy.ts
- packages/entities/entities-routes/src/components/RouteForm.vue
- packages/entities/entities-routes/src/components/RouteFormRulesComposer.vue
1. The route form now allows submission when only the `port` field is filled (and `ip` is empty) for both Sources and Destinations.
2. Fixed an issue in Konnect Gateway Manager where the form couldn’t be submitted if only the `ip` field was filled and `port` was left empty.
KM-1482
> fix(entities-routes): source and destination port

- packages/entities/entities-plugins/vite.config.ts
Externalize the plugin-icons from the bundle of entities-plugins.
**Before**
```
dist/entities-plugins.umd.js  703.05 kB │ gzip: 359.03 kB │ map: 1,609.54 kB
```
**After**
```
dist/entities-plugins.umd.js  326.59 kB │ gzip: 90.52 kB │ map: 1,227.16 kB
```
-269 kB after gzip
> chore(entities-plugins): externalize plugin-icons

- packages/entities/entities-consumers/docs/consumer-list.md
- packages/entities/entities-consumers/src/components/ConsumerList.vue
Add `empty-state-toolbar` slot for displaying switch control for toggling the view between scoped and global consumers in empty state.
> fix(entities-consumers): consumers list empty state toolbar slot

- packages/entities/entities-plugins/src/components/free-form/shared/StringField.vue
Group the `<Input />` and `<VaultPicker />` of the `<StringField />` by wrapping them in a single `<div>` container.
> refactor(free-form): wrap string field with a div

- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorMain.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/FlowNode.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/HandleTwig.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/node.ts
This pull request fixes the issues with the node handle placements in the "reversed" phases. 
Meanwhile, it also cleans up the codebase a bit to use the freshly added types, adds some node helpers, and unifies the position properties to use VueFlow's `Position`.
> fix(entities-plugins): datakit handles, adopt types, add helpers

- packages/analytics/analytics-metric-provider/src/components/MetricsProvider.cy.ts
- packages/analytics/analytics-metric-provider/src/composables/useMetricFetcher.ts
- packages/analytics/analytics-utilities/src/dashboardSchema.v2.ts
- packages/analytics/analytics-utilities/src/index.ts
- packages/analytics/analytics-utilities/src/types/explore/all.ts
- packages/analytics/analytics-utilities/src/types/query-bridge.ts
- packages/analytics/dashboard-renderer/sandbox/mock-data.ts
- packages/analytics/dashboard-renderer/src/components/BaseAnalyticsChartRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.spec.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardTile.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- packages/analytics/dashboard-renderer/src/components/GoldenSignalsRenderer.vue
- packages/analytics/dashboard-renderer/src/components/QueryDataProvider.vue
- packages/analytics/dashboard-renderer/src/components/SimpleChartRenderer.vue
- packages/analytics/dashboard-renderer/src/components/TopNTableRenderer.vue
- packages/analytics/dashboard-renderer/src/components/layout/grid-utils.spec.ts
- packages/analytics/dashboard-renderer/src/components/layout/grid-utils.ts
- Change the default export 
- Support v2 definitions in the renderer.
- Requires changes to existing hardcoded dashboards.
- Should support new custom dashboard API endpoint.
- Rename 'advanced' and 'ai' datasources to 'api_usage' and 'llm_usage'.
- Requires changes to analytics bridges.
BREAKING CHANGE: dashboards only support v2 schemas; analytics-utilities exports v2 schema by default.
> feat(analytics): move dashboards to version 2 [MA-3935]

- packages/analytics/dashboard-renderer/sandbox/mock-data.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
- packages/analytics/dashboard-renderer/src/types/grid-layout-types.ts
The object being passed to GridStack wasn't preserving the new top-level 'type' field on tiles, which caused the field to be lost when tiles were sorted.
> fix(dashboards): preserve tile type field

- packages/entities/entities-gateway-services/src/components/GatewayServiceForm.vue
KM-1514
The tag error is not cleared after tag input change so the user is not able to re-submit, this PR fix this.
https://github.com/user-attachments/assets/f665db49-3878-40f4-9f82-a0e6f9f7a9ab
> fix(service-form): clear tag error when tag input changes

- packages/entities/entities-shared/src/components/entity-form-block/EntityFormBlock.vue
A `flex: 0 0 auto;` is added to step badge to prevent it from shrinking, ensuring it maintains its size.
JIRA: KM-1434
> fix(entity-form-block): fix layout for step badge

- packages/entities/entities-plugins/src/components/free-form/Datakit/DatakitForm.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/composables.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/FlowEditor.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorContent.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorMain.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/FlowNode.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/NodeBadge.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/NodePanel.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/NodePanelItem.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/NodePropertiesPanel.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/node.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/helpers.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/history.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/init.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/store.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/validation.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/types.ts
[KM-1518](https://konghq.atlassian.net/browse/KM-1518)
- Type updates: `UserNode` → `ConfigNode`, `NodeData` → `NodeInstance`
- Added edge-related types and state
- Provide global store via `provideEditorState` / `useEditorState`
- Expose core state: `nodes`, `edges`, lookup maps
- Support node/field/edge operations
- Undo/redo with tagged history
- Built-in validation: structure, cycles, phase rules
- VueFlow adapters and connection validation
[KM-1518]: https://konghq.atlassian.net/browse/KM-1518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(entities-plugins): datakit store, improve types

- packages/entities/entities-plugins/package.json
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/FlowEditor.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/composables/useFlow.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/constants.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorCanvasFlow.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorMain.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/FlowNode.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/init.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/store.ts
- pnpm-lock.yaml
* (Initial) Auto-layout with Dagre + Implicit nodes placement
* Move eligible nodes (ultimately connected to `request` or `service_request`) to the request phase on editor init
* Populate VueFlow nodes and edges inside a new composable
* No collapse for handles with field-level connections
* Hovered/Selected state on nodes
|Hovered/Selected|Node-level I/O handle vs. Field-level I/O handle|
|:-:|:-:|
|![Kapture 2025-08-05 at 17 54 41](https://github.com/user-attachments/assets/9d042d07-9405-483a-8517-ae33e5b0fe59)|![Kapture 2025-08-05 at 17 58 31](https://github.com/user-attachments/assets/12eafee4-c79e-4c87-858d-4a3ea653bc4c)|
* VueFlow didn't provide built-in dashed edges
* Hovered/Selected states for edges are not implemented, as it takes more effort to change the markers (arrows) on …
> feat(entities-plugins): datakit auto-layout and store improvements

- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/NodeFormProperty.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/property.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/FlowNode.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/store.ts
* Show only valid (readable?/writable?) handles on property nodes
* Add `disconnectInEdges` and `disconnectOutEdges` helpers to disconnect all the in/out-edges associated with a node
* Add a `isReadableProperty` helper for property nodes
https://github.com/user-attachments/assets/f26f36a1-30c8-4930-b3e9-f5e8d57e03f1
KM-1562
> feat(entities-plugins): datakit show valid handles in property nodes and update edges

- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/composables/useFlow.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorCanvasFlow.vue
* Remove nodes or disconnect edges while deleting nodes or edges from the VueFlow canvas
* Move some listeners from the component to the `useFlow` composable
* Move all event listeners (if possible) to the `useFlow` composable
> feat(entities-plugins): datakit remove nodes and edges upon deletion from canvas

- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/composables/useFlow.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorCanvasFlow.vue
Clear all history after initialization, as the state by that point should be treated as the origin.
KM-1571
> fix(entities-plugins): datakit clear all history after init

- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/composables/useFlow.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/FlowNode.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/NodeBadge.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/NodePanel.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/NodePropertiesPanel.vue
[KM-1572](https://konghq.atlassian.net/browse/KM-1572)
- Refine styles for handle labels  
- Rename `inputNotCollapsible` / `outputNotCollapsible` → `inputCollapsible` / `outputCollapsible` for improved clarity  
- Resolve VueFlow warnings  
- Prevent slideout padding from clipping the left side of focus rings
[KM-1572]: https://konghq.atlassian.net/browse/KM-1572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(entities-plugins): improve datakit flow node styles, reduce warnings

- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/composables/useFlow.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorCanvasFlow.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/FlowNode.vue
* Stop click events on handle triggers
* Disallow implicit node removal
* Disallow multiselect
KM-1583
> fix(entities-plugins): datakit several canvas issues

- packages/analytics/analytics-chart/src/components/chart-plugins/DragSelectPlugin.ts
- packages/analytics/dashboard-renderer/sandbox/pages/EditableDashboardDemo.vue
- packages/analytics/dashboard-renderer/src/components/BaseAnalyticsChartRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardRenderer.vue
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- packages/analytics/dashboard-renderer/src/types/index.ts
- packages/analytics/dashboard-renderer/src/types/tile-zoom-event.ts
Part 1 of [ma-4135](https://konghq.atlassian.net/browse/MA-4135)
Behind new [FF](https://app.launchdarkly.com/projects/default/flags/ma-4135-allow-zooming-all-dashboard-tiles/targeting?env=local&env=dev&selected-env=local)
BREAKING CHANGE: zoom-time-range event signature changed
- Renamed dashboard renderer `zoom-time-range` emit to `tile-time-range-zoom` 
- Enable zooming on all tiles. When the feature flag is enabled, tiles with a pinned time range can now be zoomed, triggering a zoom event.
(Note: Host app must update handling for zoom events on pinned time range tiles.)
- Include tileId in the tile-time-range-zoom event payload:
```
interface TileZoomEvent {
tileId: string
timeRange: AbsoluteTimeRangeV4
}
```
Fixed a bug where the zoom area highlight no longer appeared after moving a …
> fix(ma-4135): allow zooming on all tiles behind FF

- packages/entities/entities-plugins/src/components/free-form/AIMcp/AIMcpForm.vue
- packages/entities/entities-plugins/src/components/free-form/AIMcp/ConfigForm.vue
- packages/entities/entities-plugins/src/components/free-form/AIMcp/index.ts
- packages/entities/entities-plugins/src/components/free-form/AIMcp/types.ts
- packages/entities/entities-plugins/src/components/free-form/AIMcp/utils.ts
- packages/entities/entities-plugins/src/components/free-form/index.ts
- packages/entities/entities-plugins/src/components/free-form/shared/EnhancedInput.vue
- packages/entities/entities-plugins/src/components/free-form/shared/Field.vue
- packages/entities/entities-plugins/src/components/free-form/shared/JsonField.vue
- packages/entities/entities-plugins/src/components/free-form/shared/NumberField.vue
- packages/entities/entities-plugins/src/locales/en.json
- packages/entities/entities-plugins/src/utils/free-form.ts
Supporting the `ai-mcp` plugin, using free form:
1. Implements `JsonField` for `parameters` and `request_body`. It can be used for all future JSON-typed fields.
2. Adds logic for `headers` and `query` to handle array-typed map values.
Plugin schema: https://github.com/Kong/gateway-schema-watcher/blob/main/plugins/ai-mcp.json.
KM-1594
> feat(entities-plugins): support ai-mcp

- packages/analytics/analytics-metric-provider/sandbox/App.vue
- packages/analytics/analytics-metric-provider/src/components/MetricsProvider.cy.ts
- packages/analytics/analytics-metric-provider/src/components/MetricsTestHarness.vue
- packages/analytics/analytics-metric-provider/src/composables/useMetricFetcher.ts
- packages/analytics/analytics-metric-provider/src/locales/en.json
- packages/analytics/analytics-metric-provider/src/mockExploreResponse.ts
https://konghq.atlassian.net/browse/MA-4160
This fixes the golden signals trend text so it correctly describes trends for absolute time ranges. The trend wording will no longer be "vs previous 0 days" for any sub-day time range.
- Adjusted trend text logic for absolute time ranges.
- Added hour and minute trend text handling for sub-day absolute time ranges.
- Added/updated unit tests to cover absolute/fine-grain scenarios.
- Component tests added/updated.
- Manually verified trend text for relative ranges and multiple absolute, fine-grain ranges.
Any sub-day absolute time range would display as `vs previous 0 days`
> fix: update golden signals trend text for fine grain absolute time

- .github/workflows/ci.yaml
we do not publish to google artifactory anymore so this step is no longer needed. (forgot to remove in prev PR)...
> fix: remove call to google auth call [KHCP-17670]

- packages/analytics/analytics-chart/src/components/chart-plugins/ChartTooltip.vue
- packages/analytics/analytics-chart/src/components/chart-types/StackedBarChart.vue
- packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
- packages/analytics/analytics-chart/src/composables/useTooltipAbsolutePosition.ts
- packages/analytics/dashboard-renderer/sandbox/pages/EditableDashboardDemo.vue
https://konghq.atlassian.net/browse/MA-4133 
- use position:fixed rather than teleporting to body
- when computing the tooltip's absolute position use `useElementBounding()` to get reactive bounding rect of the parent. This allows offsetting if any parent is scrolled not just the document body.
- use `useDraggable` from vueuse in favour of custom drag handling - simplifies the code
- sync the drag position with the tooltip's absolute position when not dragging - this is what accounts for scroll offset and also allows the dragging state to start from the tooltip's last position,
https://github.com/user-attachments/assets/873fd890-afed-428c-bfe0-0b02c6da47cd
> fix(analytics-chart): chart tooltip improvements

- packages/entities/entities-plugins-metadata/src/index.ts
Now the `kafka-consume` plugin does not support scoping to a service: https://github.com/Kong/kong-ee/pull/13648.
KM-1623
> feat(plugins-metadata): update kafka-consume scope

- packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
- packages/analytics/dashboard-renderer/src/components/DashboardTile.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
Fix [MA-4246](https://konghq.atlassian.net/browse/MA-4246)
This will disable the Jump to Requests action when zooming or selecting the action dropdown menu for a DashboardTile when the datasource is `llm_usage`. 
Added a computed property to clean up other sections of the component that use the same conditions.
[MA-4246]: https://konghq.atlassian.net/browse/MA-4246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dashboardrenderer): disable jump to request for llm datasource [MA-4246]

- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/composables/useFlow.ts
Fix the issue where the old edge is left untouched in some conditions while updating the edge
> fix(entities-plugins): datakit disconnect before update edges

- packages/analytics/dashboard-renderer/src/components/DashboardTile.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
https://konghq.atlassian.net/browse/MA-4219
ui-apps pr: https://github.com/Kong/konnect-ui-apps/pull/8086
In order to reflect the effective query time range, use `start_ms` and `end_ms` returned in the explore result meta when generating the request link for a dashboard tile.
> fix: use start and end from chart data for requests link

- packages/entities/entities-plugins/src/components/PluginForm.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/CodeEditor.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/DatakitForm.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/init.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/types.ts
- packages/entities/entities-plugins/src/definitions/metadata.ts
- packages/entities/entities-plugins/src/types/plugin.ts
* Utilise the `?__ui_data` endpoint to save and restore the UI data
* Add a `useUIData` field to plugin metadata for future usage
* Add more types
https://github.com/user-attachments/assets/98edfce7-9ddf-48c7-8d89-be9447468961
KM-1462
> feat(entities-plugins): datakit save and restore ui data

- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/OutputValueField.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node/FlowNode.vue
* Expand handles on I/O fields update (add, rename)
* Collapse handles when all I/O fields are removed
* Fix a `z-index` issue (the removal button is hard to interact with)
https://github.com/user-attachments/assets/86ee3311-50a9-471d-afef-0b04e51014eb
KM-1655
> fix(entities-plugins): datakit expand handles on i/o fields update

- packages/entities/entities-plugins/src/components/free-form/Datakit/CodeEditor.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/DatakitForm.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/FlowEditor.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/types.ts
- packages/entities/entities-plugins/src/components/free-form/shared/PluginFormWrapper.vue
- packages/entities/entities-plugins/src/components/free-form/shared/layout/StandardLayout.vue
- packages/entities/entities-plugins/src/types/plugins/free-form.ts
The `flowEditor` and the `codeEditor` shared the local states from `DatakitForm`, then sync the local states to freeform, then freeform will send the data to the outside.
The `flowEditor` and the `codeEditor` shared form data from freeform directly
> refactor(entities-plugins): datakit - data flow

- packages/entities/entities-plugins/package.json
- packages/entities/entities-redis-configurations/package.json
- pnpm-lock.yaml
KM and Konnect do not list the `@kong-ui-public/entities-plugins-icon` package as their dependency. So, for `@kong-ui-public/entities-plugins`, the icons package should not be a peer dependency.
> fix(entities-plugins): move the icons package to dependencies

- packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
Fix [MA-4286](https://konghq.atlassian.net/browse/MA-4286)
The returns for each analytics chart axis title type had a few inconsistencies. Namely:
- Returning localized strings that may not exist
- Returning `boolean`'s when a string is expected
- Not having proper fallbacks in place if a localized string didn't exist
This will add a few fallbacks to return a metric/dimension/granularity property when a localized string is not found; If neither is found, only then will `undefined` be returned.
[MA-4286]: https://konghq.atlassian.net/browse/MA-4286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(analytics): improve fallback axes titles [MA-4286]

- packages/analytics/dashboard-renderer/src/components/DashboardTile.cy.ts
- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
Fix [MA-4289](https://konghq.atlassian.net/browse/MA-4289)
This will ensure that the `allow_csv_export` property defaults to `true` when the `chart.definition` does not include the prop.
[MA-4289]: https://konghq.atlassian.net/browse/MA-4289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(dashboard-renderer): allow csv export by default [MA-4289]

- packages/analytics/dashboard-renderer/src/components/DashboardTile.cy.ts
- packages/analytics/dashboard-renderer/src/composables/useContextLinks.spec.ts
- packages/analytics/dashboard-renderer/src/composables/useContextLinks.ts
- packages/analytics/dashboard-renderer/src/stores/tests/setupPiniaTestStore.ts
https://konghq.atlassian.net/browse/MA-4284
Do not show explore and view request options on dashboard/tile context menus if user does not have advanced analytics
> fix: dont generate links if no advanced analytics

- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/FlowCanvas.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/icons/AutoLayoutIcon.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/icons/FitIcon.vue
- packages/entities/entities-plugins/src/locales/en.json
[KM-1708](https://konghq.atlassian.net/browse/KM-1708)
[KM-1708]: https://konghq.atlassian.net/browse/KM-1708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(entities-plugins): datakit control icons/tooltips

- cypress.config.ts
- packages/core/documentation/src/components/DiscardChangesPrompt.vue
- packages/core/documentation/src/components/DocumentationDisplay.cy.ts
- packages/core/documentation/src/components/DocumentationDisplay.vue
- packages/core/documentation/src/locales/en.json
This introduces a user-friendly prompt for handling unsaved changes when toggling the publish state of documentation pages. The main improvement is the addition of a modal dialog that asks users to confirm discarding unsaved changes, helping prevent accidental data loss. 
**Notable Changes: **
* Added a new `DiscardChangesPrompt.vue` component that displays a modal dialog when the user attempts to publish/unpublish with unsaved changes. The modal provides options to discard changes or continue editing.
* Integrated the discard changes prompt into `DocumentationDisplay.vue`, showing it when unsaved changes are detected during publish/unpublish actions.
* Added helper to attach/detach a native input listener on the editor textarea to better-detect changes. There was a bug where you could go …
> feat(documentation): show discard changes warning and allow revert [TDX-6534]

- packages/analytics/analytics-chart/src/components/AnalyticsChart.cy.ts
- packages/analytics/analytics-chart/src/components/AnalyticsChart.vue
- packages/analytics/analytics-chart/src/components/ZoomActions.vue
- packages/analytics/analytics-chart/src/components/chart-types/TimeSeriesChart.vue
- packages/analytics/analytics-chart/src/types/zoom-action-item.ts
Addresses https://konghq.atlassian.net/browse/MA-4288 
If any zoom option is provided allow brushing the chart to select an area.
- Rename internal zoom prop in `TimeSeriesChart` to `brush` since `zoom` pertains to the specific zoom action. 
- Allow "brushing" if `timeseriesZoom` `exploreLink` or `requestsLink` is provided
- Add component test cases around interactivity
> fix: allow view requests and explore independent of zoom

- packages/entities/entities-shared/fixtures/mockData.ts
- packages/entities/entities-shared/sandbox/pages/ConfigCardItemPage.vue
- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.cy.ts
- packages/entities/entities-shared/src/components/entity-base-config-card/ConfigCardItem.vue
Event gateway API endpoints return ISO format date string for `created_at` and `updated_at` fields
JIRA: KM-1726
> feat(config-card-item): add iso date string rendering support

- packages/analytics/dashboard-renderer/src/components/DashboardTile.vue
- packages/analytics/dashboard-renderer/src/composables/useContextLinks.spec.ts
- packages/analytics/dashboard-renderer/src/composables/useContextLinks.ts
https://konghq.atlassian.net/browse/MA-4288
One more fix needed for this. 
`exploreLinkZoomActions` and `requestsLinkZoomActions` were initialized as undefined and only set after an event from the dragSelect plugin (onSelectChartRange).
When `timeseries-zoom` was disabled, the dragSelect plugin could not register with the chart because it required either the explore link or requests link to be defined.
Initialize `exploreLinkZoomActions` and `requestsLinkZoomActions` with an empty href as soon as the `canGenerate`... composables become true.
> fix: initialize zoom action links

- packages/entities/entities-plugins/src/components/PluginSelect.vue
Add a `before-custom-tab-content` slot before the content of the Custom Plugins tab.
KM-1713
> feat(entities-plugins): add a before-custom-tab-content slot

- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/store.ts
[KM-1737](https://konghq.atlassian.net/browse/KM-1737)
Only commit when `expanded` does change. Otherwise this will contaminate the history records especially when tagged with `*`.
[KM-1737]: https://konghq.atlassian.net/browse/KM-1737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(entities-plugins): fix toggle node expanded

- packages/entities/entities-plugins/src/components/PluginForm.vue
Strip the `__ui_data` field (it will still be submitted via the UI) from the config displayed in the View Configuration slideout while editing the plugin. This applies to all plugins, as `__ui_data` should be considered a special field that should not be displayed for any plugin.
KM-1759
> fix(entities-plugins): hide __ui_data in config view while editing

- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/composables/useNodeForm.ts
Fix an issue where history was not committed when an edge is replaced via the node form.
> fix(entities-plugins): datakit commit on replacing edge via node form

- packages/analytics/analytics-geo-map/src/components/AnalyticsGeoMap.vue
- packages/analytics/analytics-geo-map/src/locales/en.json
https://konghq.atlassian.net/browse/MA-4276
Require ctrl/cmd + scroll to zoom analytics geo map
See [maplibre cooperative gestures](https://maplibre.org/maplibre-gl-js/docs/examples/cooperative-gestures/)
> fix: require ctrl/cmnd + scroll to zoom the map by default

- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/FlowEditor.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/FlowPanels.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/init.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/store/store.ts
- packages/entities/entities-plugins/src/components/free-form/Datakit/types.ts
Introduce a `pendingFitView` (like `needLayout` which was renamed to `pendingLayout` for more clarity) in the editor state to prevent unexpected `fitView` calls on nodes/edges change, especially while adding nodes via drag and drop or duplicating nodes.
KM-1783
> fix(entities-plugins): datakit incorrect fitView calls on DND and duplicate

- packages/entities/entities-plugins/src/components/PluginConfigCard.vue
Remove unsupported scoping fields in the plugin detail view according to the plugin metadata. This does not affect Konnect, as their API does not return the unsupported fields in the first place.
1. If the scope definition is missing for a plugin, keep it as is, as it could be a new bundled plugin or a custom plugin with an incorrect schema.
2. If a scoping field is not empty, but the plugin metadata does not have that scope (unsupported if telling from the metadata), keep the scoping field in case we have incorrect metadata.
|Structured|JSON|
|:-|:-|
|<img width="732" height="698" alt="Screenshot 2025-09-18 at 16 16 37" src="https://github.com/user-attachments/assets/34c04c96-42f2-44bc-9e06-500c67cadddc" />|<img width="704" height="747" alt="Screenshot 2025-09-18 at 16 16 22" …
> fix(entities-plugins): remove unsupported scoping fields in detail view

- packages/analytics/analytics-geo-map/src/components/AnalyticsGeoMap.vue
- packages/analytics/analytics-geo-map/src/locales/en.json
Adds a new empty state to `AnalyticsGeoMap` that displays when there are no country metrics to display and no country focused on.
Customizable via the following slots: 
- no-location-icon
- Icon for the empty state
- no-location-title
- Title for the empty state
-  no-location-description
- description for the empty state
> feat: analytics geo map empty state

- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/modal/EditorMain.vue
- packages/entities/entities-plugins/src/components/free-form/Datakit/flow-editor/node-forms/InputsField.vue
- packages/entities/entities-plugins/src/locales/en.json
[KM-1801](https://konghq.atlassian.net/browse/KM-1801)
Also fixed an issue that the debug tooltip was covered by the node properties panel.
[KM-1801]: https://konghq.atlassian.net/browse/KM-1801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(entities-plugins): improve datakit source selector copy

- packages/analytics/analytics-chart/package.json
- packages/analytics/analytics-chart/sandbox/pages/TimeSeriesChartDemo.vue
- packages/analytics/analytics-chart/src/components/chart-plugins/ThresholdPlugin.cy.ts
- packages/analytics/analytics-chart/src/components/chart-plugins/ThresholdPlugin.ts
- packages/analytics/analytics-chart/src/components/chart-plugins/thresholdPlugin.spec.ts
- packages/analytics/analytics-chart/src/types/chart-data.ts
- packages/analytics/analytics-utilities/src/dashboardSchema.v2.ts
https://konghq.atlassian.net/browse/MA-4302
Detect when data crosses thresholds and brush the area
figure out where each datasource intersects the threshold, merge overlapping "intersections" so we don't draw overlapping brushes
> feat: draw threshold intersection brush

- packages/analytics/analytics-chart/src/locales/en.json
- packages/analytics/analytics-chart/src/utils/queryError.spec.ts
- packages/analytics/analytics-chart/src/utils/queryError.ts
- packages/analytics/dashboard-renderer/src/components/QueryDataProvider.vue
Related [MA-4332](https://konghq.atlassian.net/browse/MA-4332)
This will fix an issue with the "Forbidden" error state for dashboard tiles by removing a duplicate `KEmptyState` component that was specific to a forbidden state. Instead it will combine the two and conditionally load the correct icon for a forbidden state.
[MA-4332]: https://konghq.atlassian.net/browse/MA-4332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(analytics): remove duplicate error state when forbidden [MA-4332]

- packages/analytics/analytics-chart/sandbox/pages/TimeSeriesChartDemo.vue
- packages/analytics/analytics-geo-map/sandbox/App.vue
- packages/analytics/analytics-geo-map/src/components/AnalyticsGeoMap.cy.ts
- packages/analytics/analytics-geo-map/src/components/AnalyticsGeoMap.vue
- packages/analytics/dashboard-renderer/sandbox/pages/EditableDashboardDemo.vue
Fix [MA-4125](https://konghq.atlassian.net/browse/MA-4125)
Contains chore from https://github.com/Kong/public-ui-components/pull/2532
This will add the ability to specify if a metric should be truncated within the GeoMap and also truncate them by default for non-latency type metrics in dashboards.
There are also a few updates to the sandbox to make things a bit cleaner, fix some typing, and add some functionality to the geo map sandbox.
[sandbox.webm](https://github.com/user-attachments/assets/79a7a190-698b-46db-a6f3-d4612f9f7373)
[MA-4125]: https://konghq.atlassian.net/browse/MA-4125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(analytics): keep consistent metric formatting for geo maps [MA-4125]
